// Code generated from docs/spec/target/contracts/publisher-contract.schema.json; DO NOT EDIT.
package publisherjson

import "google.golang.org/protobuf/reflect/protoreflect"

var enumNames = map[protoreflect.FullName]map[protoreflect.EnumNumber]string{
	"opl.cloud.api.ImagePlatformOsEnum":                               {1: "linux"},
	"opl.cloud.api.ImagePlatformArchitectureEnum":                     {1: "amd64", 2: "arm64"},
	"opl.cloud.api.RecipeArtifactMediaTypeEnum":                       {1: "application/vnd.opl.build-recipe.v1+tar"},
	"opl.cloud.api.PackageBuildInputContextNameEnum":                  {1: "agent_package"},
	"opl.cloud.api.WebuiBuildInputContextNameEnum":                    {1: "webui"},
	"opl.cloud.api.BuildRecipeContractVersionEnum":                    {1: "opl-build-recipe/v1"},
	"opl.cloud.api.BuildRecipeContractRuntimeContextNameEnum":         {1: "runtime"},
	"opl.cloud.api.BuildRecipeContractNetworkPolicyEnum":              {1: "none"},
	"opl.cloud.api.ModelConfigurationContractProtocolEnum":            {1: "opl-model-config/v1"},
	"opl.cloud.api.ModelConfigurationContractRequestFieldsEnum":       {1: "version", 2: "selections"},
	"opl.cloud.api.ModelConfigurationContractReadbackFieldsEnum":      {1: "appliedVersion", 2: "selections"},
	"opl.cloud.api.DataUpgradeContractModeEnum":                       {1: "compatible", 2: "publisher_migration"},
	"opl.cloud.api.RuntimePublisherContractSchemaVersionEnum":         {1: "opl-publisher-contract/v1"},
	"opl.cloud.api.RuntimePublisherContractKindEnum":                  {1: "runtime"},
	"opl.cloud.api.WebuiPublisherContractSchemaVersionEnum":           {1: "opl-publisher-contract/v1"},
	"opl.cloud.api.WebuiPublisherContractKindEnum":                    {1: "webui"},
	"opl.cloud.api.WebuiPublisherContractUiProtocolVersionEnum":       {1: "opl-webui/v1"},
	"opl.cloud.api.WebuiPublisherContractIntegrationModeEnum":         {1: "bundled_static"},
	"opl.cloud.api.WebuiPublisherContractAuthenticationProtocolEnum":  {1: "opl-application-session/v1"},
	"opl.cloud.api.PublisherContractReferenceKindEnum":                {1: "runtime", 2: "webui"},
	"opl.cloud.api.DeploymentDescriptorSchemaVersionEnum":             {1: "opl-deployment-descriptor/v1"},
	"opl.cloud.api.DeploymentDescriptorProvenanceEnum":                {1: "build", 2: "legacy_application"},
	"opl.cloud.api.WorkspaceApplicationCredentialKindEnum":            {1: "workspace_admin_password", 2: "workspace_session_secret", 3: "gateway_key"},
	"opl.cloud.api.WorkspaceApplicationPortProtocolEnum":              {1: "TCP", 2: "UDP"},
	"opl.cloud.api.WorkspaceApplicationDependencyHealthCheckTypeEnum": {1: "tcp", 2: "http", 3: "exec"},
	"opl.cloud.api.WorkspaceApplicationRevisionExposurePolicyEnum":    {1: "anonymous", 2: "application", 3: "cloud_private"},
	"opl.cloud.api.ApplicationOwnedAccessContractModeEnum":            {1: "application"},
	"opl.cloud.api.CloudPrivateAccessContractModeEnum":                {1: "cloud_private"},
	"opl.cloud.api.CloudPrivateAccessContractEntryContractEnum":       {1: "WorkspaceApplicationEntry"},
	"opl.cloud.api.AnonymousAccessContractModeEnum":                   {1: "anonymous"},
	"opl.cloud.api.PackageFormatContractReferenceOwnerEnum":           {1: "framework"},
}

var required = map[protoreflect.Name]map[string]bool{
	"ImagePlatform":                             {"os": true, "architecture": true},
	"ArtifactReference":                         {"repository": true, "digest": true, "platform": true},
	"RecipeArtifact":                            {"repository": true, "digest": true, "mediaType": true, "dockerfilePath": true},
	"PackageBuildInput":                         {"contextName": true, "formatVersion": true, "sourceRoot": true, "targetPath": true, "uid": true, "gid": true},
	"WebuiBuildInput":                           {"contextName": true, "sourcePath": true, "targetPath": true, "uid": true, "gid": true},
	"BuildRecipeContract":                       {"version": true, "frontend": true, "recipe": true, "runtimeContextName": true, "packageInput": true, "webuiInput": true, "networkPolicy": true, "outputPlatform": true, "outputImageCommand": true},
	"BuildRecipeContractOutputImageCommand":     {"entrypoint": true, "cmd": true},
	"ModelConfigurationContract":                {"protocol": true, "portName": true, "applyPath": true, "readbackPath": true, "requestFields": true, "readbackFields": true, "authorizationSecretInputName": true},
	"DataUpgradeContract":                       {"mode": true, "compatibleFromSchemaVersions": true, "backupRequired": true},
	"DataRollbackContract":                      {"safe": true, "compatibleSchemaVersions": true},
	"DataContract":                              {"schemaVersion": true, "upgrade": true, "rollback": true, "mountPolicies": true},
	"RuntimePublisherContract":                  {"schemaVersion": true, "publisherNamespaceId": true, "image": true, "kind": true, "runtimeAbiVersion": true, "packageFormatVersions": true, "buildRecipe": true, "modelConfiguration": true, "applicationAccess": true, "data": true, "applicationRevisionTemplate": true, "packageFormatContracts": true},
	"WebuiPublisherContract":                    {"schemaVersion": true, "publisherNamespaceId": true, "image": true, "kind": true, "runtimeAbiVersions": true, "uiProtocolVersion": true, "integrationMode": true, "staticRoot": true, "entryFile": true, "assetBasePath": true, "apiBasePath": true, "authenticationProtocol": true, "supportsSse": true, "supportsWebsocket": true},
	"PublisherContractReference":                {"publisherNamespaceId": true, "versionId": true, "kind": true, "descriptorDigest": true, "descriptorObjectRef": true},
	"DeploymentDescriptor":                      {"schemaVersion": true, "artifact": true, "provenance": true, "applicationRevision": true},
	"WorkspaceApplicationCredential":            {"name": true, "kind": true, "target": true},
	"WorkspaceApplicationPort":                  {"name": true, "port": true, "protocol": true},
	"WorkspaceApplicationHealthCheck":           {"port": true, "path": true},
	"WorkspaceApplicationMount":                 {"name": true, "mountPath": true},
	"WorkspaceApplicationSecretInput":           {"name": true},
	"WorkspaceApplicationConfigInput":           {"name": true, "target": true},
	"WorkspaceApplicationDependencyHealthCheck": {"type": true, "port": true},
	"WorkspaceApplicationDependency":            {"name": true, "image": true},
	"WorkspaceApplicationRevision":              {"schemaVersion": true, "applicationId": true, "version": true, "platform": true, "image": true, "exposurePolicy": true},
	"DataMountPolicy":                           {"mountName": true, "concurrentWritersSupported": true},
	"ApplicationOwnedAccessContract":            {"mode": true, "loginPath": true, "logoutPath": true},
	"CloudPrivateAccessContract":                {"mode": true, "entryContract": true, "admissionReceiptId": true},
	"AnonymousAccessContract":                   {"mode": true},
	"PackageFormatContractReference":            {"owner": true, "formatVersion": true, "schemaObjectRef": true, "schemaDigest": true, "validatorArtifact": true, "admissionReceiptId": true},
}
