import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import type { TestContext } from "node:test";
import {
  generationInputs,
  generatedOutputs,
  verifyGeneratedContracts
} from "../../tools/verify-generated-contracts.ts";
import type { GenerationCommand, GenerationRunner } from "../../tools/verify-generated-contracts.ts";

const proto = "packages/contracts/proto";
const target = "docs/spec/target";

function put(root: string, path: string, data: string | Buffer) {
  mkdirSync(dirname(join(root, path)), { recursive: true });
  writeFileSync(join(root, path), data);
}

// A deterministic dependency-aware runner, not an assertion/hash manifest.
// Real generator execution runs through `npm run verify:generated-contracts`.
// These fixtures exercise freshness, not W01 migration or source-copy parity.
function fakeGeneration({ args, cwd }: GenerationCommand) {
  assert.equal(args[0], `${proto}/generate.sh`);
  const contents = (...paths: string[]) => Buffer.concat(paths.map((path) => readFileSync(join(cwd, path))));
  switch (args[1]) {
    case "bindings":
      for (const output of generatedOutputs.slice(0, 2)) {
        put(cwd, output, contents(`${proto}/generate.sh`, `${proto}/internal.proto`));
      }
      break;
    case "public-json":
      put(cwd, generatedOutputs[2], contents(
        `${proto}/generate.sh`, `${proto}/generate_public_json_shape.py`, `${target}/contracts/internal.proto`,
        `${target}/03_api_contract_complete.yaml`, `${target}/contracts/publisher-contract.schema.json`
      ));
      break;
    case "event-identity":
      put(cwd, generatedOutputs[3], contents(`${proto}/generate.sh`, `${proto}/generate_event_identity.py`, `${proto}/events.json`));
      break;
    case "policy":
      for (const output of generatedOutputs.slice(4)) {
        put(cwd, output, contents(`${proto}/generate.sh`, "services/gateway-integration/identity/generate_policy.py", `${target}/03_api_contract_complete.yaml`));
      }
      break;
    default: throw new Error(`unexpected generation chain: ${args[1]}`);
  }
}

function fixture(t: TestContext) {
  const root = mkdtempSync(join(tmpdir(), "opl-freshness-test-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  for (const path of generationInputs) put(root, path, `input: ${path}\n`);
  for (const chain of ["bindings", "public-json", "event-identity", "policy"]) {
    fakeGeneration({ command: "bash", args: [`${proto}/generate.sh`, chain], cwd: root });
  }
  return root;
}

test("freshness passes by regenerating isolated inputs into empty outputs without rewriting the repository", (t) => {
  const root = fixture(t);
  const originals = new Map([...generationInputs, ...generatedOutputs].map((path) => [path, readFileSync(join(root, path))]));
  const calls: GenerationCommand[] = [];
  const runner: GenerationRunner = (command) => {
    assert.notEqual(command.cwd, root);
    if (calls.length === 0) {
      for (const output of generatedOutputs) assert.equal(existsSync(join(command.cwd, output)), false);
      for (const input of generationInputs) assert.deepEqual(readFileSync(join(command.cwd, input)), originals.get(input));
    }
    calls.push(command);
    fakeGeneration(command);
  };
  const result = verifyGeneratedContracts({ root, runner });
  assert.equal(result.passed, true);
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.compared, [...generatedOutputs].sort());
  assert.match(result.uncovered.join("\n"), /events.json.*NOT regenerated/);
  assert.equal(calls.length, 4);
  for (const call of calls) assert.equal(call.command, "bash");
  for (const call of calls) assert.equal(existsSync(call.cwd), false, "temporary workspace leaked");
  for (const [path, bytes] of originals) assert.deepEqual(readFileSync(join(root, path)), bytes);
});

test("freshness accepts current generated bytes when production and target sources intentionally differ", (t) => {
  const root = fixture(t);
  put(root, `${target}/contracts/internal.proto`, "target migration remains incomplete\n");
  put(root, `${target}/contracts/events.json`, JSON.stringify({ description: "target migration remains incomplete" }));
  // Public JSON consumes the target proto; generate its current bytes without
  // forcing the production and target copies to agree.
  fakeGeneration({ command: "bash", args: [`${proto}/generate.sh`, "public-json"], cwd: root });
  const result = verifyGeneratedContracts({ root, runner: fakeGeneration });
  assert.equal(result.passed, true, result.errors.join("\n"));
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.compared, [...generatedOutputs].sort());
});

test("freshness covers the existing identity policy and BFF status generator", (t) => {
  const root = fixture(t);
  const outputs = [
    "services/gateway-integration/identity/policy_generated.go",
    "apps/console-bff/internal/httpapi/status_generated.go"
  ];
  const result = verifyGeneratedContracts({ root, runner: fakeGeneration });
  assert.equal(result.passed, true, result.errors.join("\n"));
  for (const output of outputs) assert.ok(result.compared.includes(output), `unchecked output: ${output}`);
});

for (const [input, outputs] of [
  [`${proto}/internal.proto`, generatedOutputs.slice(0, 2)],
  [`${target}/contracts/internal.proto`, [generatedOutputs[2]]],
  [`${target}/03_api_contract_complete.yaml`, [generatedOutputs[2], ...generatedOutputs.slice(4)]],
  [`${target}/contracts/publisher-contract.schema.json`, [generatedOutputs[2]]],
  [`${proto}/events.json`, [generatedOutputs[3]]],
  [`${proto}/generate_public_json_shape.py`, [generatedOutputs[2]]],
  [`${proto}/generate_event_identity.py`, [generatedOutputs[3]]],
  ["services/gateway-integration/identity/generate_policy.py", generatedOutputs.slice(4)],
  [`${proto}/generate.sh`, generatedOutputs]
] as const) {
  test(`freshness detects ${input} drift only through its real output consumers`, (t) => {
    const root = fixture(t);
    put(root, input, "changed input\n");
    const result = verifyGeneratedContracts({ root, runner: fakeGeneration });
    assert.equal(result.passed, false);
    assert.deepEqual(result.errors.sort(), outputs.map((output) => `generated bytes differ: ${output}`).sort());
    assert.deepEqual(result.compared, generatedOutputs.filter((output) => !outputs.some((affected) => affected === output)).sort());
  });
}

for (const output of generatedOutputs) {
  test(`freshness rejects byte tampering in ${output}`, (t) => {
    const root = fixture(t);
    // Same length, different byte: this must be content comparison, not size/mtime.
    const bytes = readFileSync(join(root, output));
    bytes[0] ^= 1;
    put(root, output, bytes);
    const result = verifyGeneratedContracts({ root, runner: fakeGeneration });
    assert.equal(result.passed, false);
    assert.ok(result.errors.includes(`generated bytes differ: ${output}`));
    assert.deepEqual(readFileSync(join(root, output)), bytes, "verification repaired a tampered output");
  });
}

test("freshness rejects no-op generators instead of comparing seeded generated files", (t) => {
  const result = verifyGeneratedContracts({ root: fixture(t), runner: () => {} });
  assert.equal(result.passed, false);
  assert.equal(result.compared.length, 0);
  for (const output of generatedOutputs) assert.ok(result.errors.some((error) => error.includes(output)));
});

for (const [chain, missing] of [
  ["bindings", generatedOutputs.slice(0, 2)],
  ["public-json", [generatedOutputs[2]]],
  ["event-identity", [generatedOutputs[3]]],
  ["policy", generatedOutputs.slice(4)]
] as const) {
  test(`freshness rejects a no-op ${chain} chain without hiding independent results`, (t) => {
    const result = verifyGeneratedContracts({ root: fixture(t), runner: (command) => {
      if (command.args[1] !== chain) fakeGeneration(command);
    } });
    assert.equal(result.passed, false);
    for (const output of missing) assert.ok(result.errors.includes(
      `missing regenerated output (or obsolete checked-in generated output): ${output}`
    ));
    assert.deepEqual(result.compared, generatedOutputs.filter((output) => !missing.some((path) => path === output)).sort());
  });
}

for (const [directory, suffix] of [
  ["packages/contracts/go/api", ".pb.go"],
  ["packages/contracts/go/publicjson", "_generated.go"],
  ["services/gateway-integration/identity", "_generated.go"],
  ["apps/console-bff/internal/httpapi", "_generated.go"]
]) {
  test(`freshness rejects obsolete and new generated files in ${directory}`, (t) => {
    const root = fixture(t);
    const obsolete = `${directory}/nested/obsolete${suffix}`;
    const added = `${directory}/nested/new${suffix}`;
    put(root, obsolete, "obsolete\n");
    const result = verifyGeneratedContracts({ root, runner: (command) => {
      fakeGeneration(command);
      put(command.cwd, added, "new\n");
    } });
    assert.equal(result.passed, false);
    assert.ok(result.errors.includes(`missing regenerated output (or obsolete checked-in generated output): ${obsolete}`));
    assert.ok(result.errors.includes(`missing checked-in generated output: ${added}`));
  });
}

test("freshness fails closed on missing tools while still checking the independent event chain", (t) => {
  const root = fixture(t);
  let temporary = "";
  const result = verifyGeneratedContracts({ root, runner: (command) => {
    temporary = command.cwd;
    if (command.args[1] === "bindings") throw new Error("missing generator: protoc-gen-go; expected protoc-gen-go v1.36.6");
    fakeGeneration(command);
  } });
  assert.equal(result.passed, false);
  assert.ok(result.errors.some((error) => error.includes("missing generator: protoc-gen-go")));
  assert.ok(result.compared.includes(generatedOutputs[3]));
  assert.equal(existsSync(temporary), false);
});

test("freshness fails on missing inputs and missing checked-in outputs", (t) => {
  const root = fixture(t);
  rmSync(join(root, generatedOutputs[0]));
  assert.ok(verifyGeneratedContracts({ root, runner: fakeGeneration }).errors.includes(
    `missing checked-in generated output: ${generatedOutputs[0]}`
  ));
  rmSync(join(root, generationInputs[0]));
  assert.throws(() => verifyGeneratedContracts({ root, runner: fakeGeneration }), /ENOENT/);
});

// Execute the actual shell preflight with only fake executable tools. No Python
// package, Go installation, network, or regeneration is required for unit tests.
for (const [tool, version, expected] of [
  ["protoc-gen-go", null, /missing generator: protoc-gen-go/],
  ["protoc-gen-go", "protoc-gen-go v0.0.0", /protoc-gen-go version mismatch/],
  ["protoc-gen-go-grpc", null, /missing generator: protoc-gen-go-grpc/],
  ["protoc-gen-go-grpc", "protoc-gen-go-grpc 0.0.0", /protoc-gen-go-grpc version mismatch/],
  ["gofmt", null, /missing formatter: gofmt/],
  ["python3", null, /missing Python: python3/],
  ["python3", "libprotoc 0.0", /protoc version mismatch/]
] as const) {
  test(`actual shell preflight rejects ${tool} ${version ?? "missing"}`, (t) => {
    const root = fixture(t);
    const bin = join(root, "bin");
    mkdirSync(bin);
    symlinkSync("/usr/bin/dirname", join(bin, "dirname"));
    const versions: Record<string, string> = {
      "protoc-gen-go": "protoc-gen-go v1.36.6",
      "protoc-gen-go-grpc": "protoc-gen-go-grpc 1.5.1",
      gofmt: "",
      python3: "libprotoc 31.1"
    };
    if (version === null) delete versions[tool];
    else versions[tool] = version;
    for (const [name, output] of Object.entries(versions)) {
      const script = `#!${process.execPath}\nif (process.argv[2] !== '-') process.stdout.write(${JSON.stringify(output + "\n")});\n`;
      put(root, `bin/${name}`, script);
      chmodSync(join(bin, name), 0o755);
    }
    put(root, `${proto}/generate.sh`, readFileSync(new URL(`../../${proto}/generate.sh`, import.meta.url)));
    const result = spawnSync("/bin/bash", [join(root, `${proto}/generate.sh`)], {
      env: { ...process.env, PATH: bin, PYTHON: "python3" }, encoding: "utf8"
    });
    assert.equal(result.status, 1, result.stderr);
    assert.match(result.stderr, expected);
  });
}

// The integration lane executes the existing Python/protoc generators, not the
// dependency-aware fixture. Locked tools must be supplied explicitly; no skips
// or fallback generators inside an enabled integration run.
if (process.env.OPL_TEST_GENERATED_CONTRACTS === "1") {
  function realFixture(t: TestContext) {
    const root = fixture(t);
    for (const path of [...generationInputs, ...generatedOutputs]) {
      put(root, path, readFileSync(new URL(`../../${path}`, import.meta.url)));
    }
    return root;
  }

  test("real freshness reproduces all existing output bytes despite target/production migration gaps", (t) => {
    const root = realFixture(t);
    put(root, `${target}/contracts/events.json`, "unused target migration source\n");
    const originals = new Map([...generationInputs, ...generatedOutputs].map((path) => [path, readFileSync(join(root, path))]));
    const result = verifyGeneratedContracts({ root });
    assert.equal(result.passed, true, result.errors.join("\n"));
    assert.deepEqual(result.compared, [...generatedOutputs].sort());
    for (const [path, bytes] of originals) assert.deepEqual(readFileSync(join(root, path)), bytes);
  });

  test("real freshness detects a changed owner event identity without updating generated products", (t) => {
    const root = realFixture(t);
    const path = `${proto}/events.json`;
    const events = JSON.parse(readFileSync(join(root, path), "utf8"));
    events.oneOf[0].properties.schemaVersion.const += 1;
    put(root, path, JSON.stringify(events));
    const original = readFileSync(join(root, generatedOutputs[3]));
    const result = verifyGeneratedContracts({ root });
    assert.equal(result.passed, false);
    assert.deepEqual(result.errors, [`generated bytes differ: ${generatedOutputs[3]}`]);
    assert.deepEqual(result.compared, generatedOutputs.filter((output) => output !== generatedOutputs[3]).sort());
    assert.deepEqual(readFileSync(join(root, generatedOutputs[3])), original);
  });
  test("real API permission changes reach only the existing identity policy output", async (t) => {
    const root = realFixture(t);
    const path = `${target}/03_api_contract_complete.yaml`;
    const { parse, stringify } = await import("yaml");
    const api = parse(readFileSync(join(root, path), "utf8"));
    const operation = api.paths["/api/v2/catalog/compute-plans"].get;
    assert.deepEqual(operation["x-permission"], ["member"]);
    operation["x-permission"] = ["owner"];
    put(root, path, stringify(api));
    const result = verifyGeneratedContracts({ root });
    assert.equal(result.passed, false);
    assert.deepEqual(result.errors, [`generated bytes differ: ${generatedOutputs[4]}`]);
    assert.deepEqual(result.compared, generatedOutputs.filter((output) => output !== generatedOutputs[4]).sort());
  });

  test("real API success status changes reach only the existing BFF status output", async (t) => {
    const root = realFixture(t);
    const path = `${target}/03_api_contract_complete.yaml`;
    const { parse, stringify } = await import("yaml");
    const api = parse(readFileSync(join(root, path), "utf8"));
    const responses = api.paths["/api/v2/auth/context"].get.responses;
    responses["201"] = responses["200"];
    delete responses["200"];
    put(root, path, stringify(api));
    const result = verifyGeneratedContracts({ root });
    assert.equal(result.passed, false);
    assert.deepEqual(result.errors, [`generated bytes differ: ${generatedOutputs[5]}`]);
    assert.deepEqual(result.compared, generatedOutputs.filter((output) => output !== generatedOutputs[5]).sort());
  });

  for (const [chain, packageName, version] of [
    ["bindings", "grpcio-tools", "1.80.0"],
    ["policy", "PyYAML", "6.0.3"]
  ]) {
    for (const fault of ["missing", "mismatch"]) {
      test(`real ${chain} preflight refuses ${packageName} ${fault} before changing any output`, (t) => {
        const root = realFixture(t);
        const python = spawnSync(process.env.PYTHON || "python3", ["-c", "import sys; print(sys.executable)"], { encoding: "utf8" });
        assert.equal(python.status, 0, python.stderr);
        const wrapper = "python-package-fault";
        // Execute the shell's actual metadata preflight with one controlled
        // package result. No package files or product sources are changed.
        put(root, wrapper, `#!${python.stdout.trim()}
import importlib.metadata as metadata
import sys
original_version = metadata.version
def version(package):
    if package == ${JSON.stringify(packageName)}:
        ${fault === "missing" ? "raise metadata.PackageNotFoundError(package)" : 'return "0.0.0"'}
    return original_version(package)
metadata.version = version
if sys.argv[1] != "-":
    raise SystemExit("unexpected execution past package preflight")
sys.argv = sys.argv[1:]
exec(compile(sys.stdin.read(), "<package-preflight>", "exec"))
`);
        chmodSync(join(root, wrapper), 0o755);
        const originals = new Map(generatedOutputs.map((path) => [path, readFileSync(join(root, path))]));
        const result = spawnSync("/bin/bash", [join(root, `${proto}/generate.sh`), chain], {
          env: { ...process.env, PYTHON: join(root, wrapper), PYTHONDONTWRITEBYTECODE: "1" }, encoding: "utf8"
        });
        assert.equal(result.status, 1, result.stderr);
        assert.ok(result.stderr.includes(fault === "missing"
          ? `missing ${packageName}==${version}`
          : `${packageName} version mismatch: expected ${version}, got 0.0.0`), result.stderr);
        for (const [path, bytes] of originals) assert.deepEqual(readFileSync(join(root, path)), bytes);
      });
    }
  }

}
