// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/applicationrevision"
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationRevisionUpdate is the builder for updating ApplicationRevision entities.
type ApplicationRevisionUpdate struct {
	config
	hooks    []Hook
	mutation *ApplicationRevisionMutation
}

// Where appends a list predicates to the ApplicationRevisionUpdate builder.
func (aru *ApplicationRevisionUpdate) Where(ps ...predicate.ApplicationRevision) *ApplicationRevisionUpdate {
	aru.mutation.Where(ps...)
	return aru
}

// SetCreatedAt sets the "created_at" field.
func (aru *ApplicationRevisionUpdate) SetCreatedAt(t time.Time) *ApplicationRevisionUpdate {
	aru.mutation.SetCreatedAt(t)
	return aru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aru *ApplicationRevisionUpdate) SetNillableCreatedAt(t *time.Time) *ApplicationRevisionUpdate {
	if t != nil {
		aru.SetCreatedAt(*t)
	}
	return aru
}

// SetUpdatedAt sets the "updated_at" field.
func (aru *ApplicationRevisionUpdate) SetUpdatedAt(t time.Time) *ApplicationRevisionUpdate {
	aru.mutation.SetUpdatedAt(t)
	return aru
}

// SetApplicationID sets the "application_id" field.
func (aru *ApplicationRevisionUpdate) SetApplicationID(s string) *ApplicationRevisionUpdate {
	aru.mutation.SetApplicationID(s)
	return aru
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (aru *ApplicationRevisionUpdate) SetNillableApplicationID(s *string) *ApplicationRevisionUpdate {
	if s != nil {
		aru.SetApplicationID(*s)
	}
	return aru
}

// SetVersion sets the "version" field.
func (aru *ApplicationRevisionUpdate) SetVersion(s string) *ApplicationRevisionUpdate {
	aru.mutation.SetVersion(s)
	return aru
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (aru *ApplicationRevisionUpdate) SetNillableVersion(s *string) *ApplicationRevisionUpdate {
	if s != nil {
		aru.SetVersion(*s)
	}
	return aru
}

// SetDigest sets the "digest" field.
func (aru *ApplicationRevisionUpdate) SetDigest(s string) *ApplicationRevisionUpdate {
	aru.mutation.SetDigest(s)
	return aru
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (aru *ApplicationRevisionUpdate) SetNillableDigest(s *string) *ApplicationRevisionUpdate {
	if s != nil {
		aru.SetDigest(*s)
	}
	return aru
}

// SetPayload sets the "payload" field.
func (aru *ApplicationRevisionUpdate) SetPayload(s string) *ApplicationRevisionUpdate {
	aru.mutation.SetPayload(s)
	return aru
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (aru *ApplicationRevisionUpdate) SetNillablePayload(s *string) *ApplicationRevisionUpdate {
	if s != nil {
		aru.SetPayload(*s)
	}
	return aru
}

// SetAdmittedByUserID sets the "admitted_by_user_id" field.
func (aru *ApplicationRevisionUpdate) SetAdmittedByUserID(s string) *ApplicationRevisionUpdate {
	aru.mutation.SetAdmittedByUserID(s)
	return aru
}

// SetNillableAdmittedByUserID sets the "admitted_by_user_id" field if the given value is not nil.
func (aru *ApplicationRevisionUpdate) SetNillableAdmittedByUserID(s *string) *ApplicationRevisionUpdate {
	if s != nil {
		aru.SetAdmittedByUserID(*s)
	}
	return aru
}

// Mutation returns the ApplicationRevisionMutation object of the builder.
func (aru *ApplicationRevisionUpdate) Mutation() *ApplicationRevisionMutation {
	return aru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aru *ApplicationRevisionUpdate) Save(ctx context.Context) (int, error) {
	aru.defaults()
	return withHooks(ctx, aru.sqlSave, aru.mutation, aru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aru *ApplicationRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := aru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aru *ApplicationRevisionUpdate) Exec(ctx context.Context) error {
	_, err := aru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aru *ApplicationRevisionUpdate) ExecX(ctx context.Context) {
	if err := aru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aru *ApplicationRevisionUpdate) defaults() {
	if _, ok := aru.mutation.UpdatedAt(); !ok {
		v := applicationrevision.UpdateDefaultUpdatedAt()
		aru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aru *ApplicationRevisionUpdate) check() error {
	if v, ok := aru.mutation.ApplicationID(); ok {
		if err := applicationrevision.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.application_id": %w`, err)}
		}
	}
	if v, ok := aru.mutation.Version(); ok {
		if err := applicationrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.version": %w`, err)}
		}
	}
	if v, ok := aru.mutation.Digest(); ok {
		if err := applicationrevision.DigestValidator(v); err != nil {
			return &ValidationError{Name: "digest", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.digest": %w`, err)}
		}
	}
	if v, ok := aru.mutation.Payload(); ok {
		if err := applicationrevision.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.payload": %w`, err)}
		}
	}
	if v, ok := aru.mutation.AdmittedByUserID(); ok {
		if err := applicationrevision.AdmittedByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "admitted_by_user_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.admitted_by_user_id": %w`, err)}
		}
	}
	return nil
}

func (aru *ApplicationRevisionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(applicationrevision.Table, applicationrevision.Columns, sqlgraph.NewFieldSpec(applicationrevision.FieldID, field.TypeString))
	if ps := aru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aru.mutation.CreatedAt(); ok {
		_spec.SetField(applicationrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := aru.mutation.UpdatedAt(); ok {
		_spec.SetField(applicationrevision.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aru.mutation.ApplicationID(); ok {
		_spec.SetField(applicationrevision.FieldApplicationID, field.TypeString, value)
	}
	if value, ok := aru.mutation.Version(); ok {
		_spec.SetField(applicationrevision.FieldVersion, field.TypeString, value)
	}
	if value, ok := aru.mutation.Digest(); ok {
		_spec.SetField(applicationrevision.FieldDigest, field.TypeString, value)
	}
	if value, ok := aru.mutation.Payload(); ok {
		_spec.SetField(applicationrevision.FieldPayload, field.TypeString, value)
	}
	if value, ok := aru.mutation.AdmittedByUserID(); ok {
		_spec.SetField(applicationrevision.FieldAdmittedByUserID, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aru.mutation.done = true
	return n, nil
}

// ApplicationRevisionUpdateOne is the builder for updating a single ApplicationRevision entity.
type ApplicationRevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApplicationRevisionMutation
}

// SetCreatedAt sets the "created_at" field.
func (aruo *ApplicationRevisionUpdateOne) SetCreatedAt(t time.Time) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetCreatedAt(t)
	return aruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aruo *ApplicationRevisionUpdateOne) SetNillableCreatedAt(t *time.Time) *ApplicationRevisionUpdateOne {
	if t != nil {
		aruo.SetCreatedAt(*t)
	}
	return aruo
}

// SetUpdatedAt sets the "updated_at" field.
func (aruo *ApplicationRevisionUpdateOne) SetUpdatedAt(t time.Time) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetUpdatedAt(t)
	return aruo
}

// SetApplicationID sets the "application_id" field.
func (aruo *ApplicationRevisionUpdateOne) SetApplicationID(s string) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetApplicationID(s)
	return aruo
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (aruo *ApplicationRevisionUpdateOne) SetNillableApplicationID(s *string) *ApplicationRevisionUpdateOne {
	if s != nil {
		aruo.SetApplicationID(*s)
	}
	return aruo
}

// SetVersion sets the "version" field.
func (aruo *ApplicationRevisionUpdateOne) SetVersion(s string) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetVersion(s)
	return aruo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (aruo *ApplicationRevisionUpdateOne) SetNillableVersion(s *string) *ApplicationRevisionUpdateOne {
	if s != nil {
		aruo.SetVersion(*s)
	}
	return aruo
}

// SetDigest sets the "digest" field.
func (aruo *ApplicationRevisionUpdateOne) SetDigest(s string) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetDigest(s)
	return aruo
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (aruo *ApplicationRevisionUpdateOne) SetNillableDigest(s *string) *ApplicationRevisionUpdateOne {
	if s != nil {
		aruo.SetDigest(*s)
	}
	return aruo
}

// SetPayload sets the "payload" field.
func (aruo *ApplicationRevisionUpdateOne) SetPayload(s string) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetPayload(s)
	return aruo
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (aruo *ApplicationRevisionUpdateOne) SetNillablePayload(s *string) *ApplicationRevisionUpdateOne {
	if s != nil {
		aruo.SetPayload(*s)
	}
	return aruo
}

// SetAdmittedByUserID sets the "admitted_by_user_id" field.
func (aruo *ApplicationRevisionUpdateOne) SetAdmittedByUserID(s string) *ApplicationRevisionUpdateOne {
	aruo.mutation.SetAdmittedByUserID(s)
	return aruo
}

// SetNillableAdmittedByUserID sets the "admitted_by_user_id" field if the given value is not nil.
func (aruo *ApplicationRevisionUpdateOne) SetNillableAdmittedByUserID(s *string) *ApplicationRevisionUpdateOne {
	if s != nil {
		aruo.SetAdmittedByUserID(*s)
	}
	return aruo
}

// Mutation returns the ApplicationRevisionMutation object of the builder.
func (aruo *ApplicationRevisionUpdateOne) Mutation() *ApplicationRevisionMutation {
	return aruo.mutation
}

// Where appends a list predicates to the ApplicationRevisionUpdate builder.
func (aruo *ApplicationRevisionUpdateOne) Where(ps ...predicate.ApplicationRevision) *ApplicationRevisionUpdateOne {
	aruo.mutation.Where(ps...)
	return aruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aruo *ApplicationRevisionUpdateOne) Select(field string, fields ...string) *ApplicationRevisionUpdateOne {
	aruo.fields = append([]string{field}, fields...)
	return aruo
}

// Save executes the query and returns the updated ApplicationRevision entity.
func (aruo *ApplicationRevisionUpdateOne) Save(ctx context.Context) (*ApplicationRevision, error) {
	aruo.defaults()
	return withHooks(ctx, aruo.sqlSave, aruo.mutation, aruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aruo *ApplicationRevisionUpdateOne) SaveX(ctx context.Context) *ApplicationRevision {
	node, err := aruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aruo *ApplicationRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := aruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aruo *ApplicationRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := aruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aruo *ApplicationRevisionUpdateOne) defaults() {
	if _, ok := aruo.mutation.UpdatedAt(); !ok {
		v := applicationrevision.UpdateDefaultUpdatedAt()
		aruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aruo *ApplicationRevisionUpdateOne) check() error {
	if v, ok := aruo.mutation.ApplicationID(); ok {
		if err := applicationrevision.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.application_id": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.Version(); ok {
		if err := applicationrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.version": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.Digest(); ok {
		if err := applicationrevision.DigestValidator(v); err != nil {
			return &ValidationError{Name: "digest", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.digest": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.Payload(); ok {
		if err := applicationrevision.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.payload": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.AdmittedByUserID(); ok {
		if err := applicationrevision.AdmittedByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "admitted_by_user_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.admitted_by_user_id": %w`, err)}
		}
	}
	return nil
}

func (aruo *ApplicationRevisionUpdateOne) sqlSave(ctx context.Context) (_node *ApplicationRevision, err error) {
	if err := aruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(applicationrevision.Table, applicationrevision.Columns, sqlgraph.NewFieldSpec(applicationrevision.FieldID, field.TypeString))
	id, ok := aruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApplicationRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationrevision.FieldID)
		for _, f := range fields {
			if !applicationrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != applicationrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aruo.mutation.CreatedAt(); ok {
		_spec.SetField(applicationrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := aruo.mutation.UpdatedAt(); ok {
		_spec.SetField(applicationrevision.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aruo.mutation.ApplicationID(); ok {
		_spec.SetField(applicationrevision.FieldApplicationID, field.TypeString, value)
	}
	if value, ok := aruo.mutation.Version(); ok {
		_spec.SetField(applicationrevision.FieldVersion, field.TypeString, value)
	}
	if value, ok := aruo.mutation.Digest(); ok {
		_spec.SetField(applicationrevision.FieldDigest, field.TypeString, value)
	}
	if value, ok := aruo.mutation.Payload(); ok {
		_spec.SetField(applicationrevision.FieldPayload, field.TypeString, value)
	}
	if value, ok := aruo.mutation.AdmittedByUserID(); ok {
		_spec.SetField(applicationrevision.FieldAdmittedByUserID, field.TypeString, value)
	}
	_node = &ApplicationRevision{config: aruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aruo.mutation.done = true
	return _node, nil
}
