// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/applicationdatamaterial"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationDataMaterialCreate is the builder for creating a ApplicationDataMaterial entity.
type ApplicationDataMaterialCreate struct {
	config
	mutation *ApplicationDataMaterialMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (admc *ApplicationDataMaterialCreate) SetCreatedAt(t time.Time) *ApplicationDataMaterialCreate {
	admc.mutation.SetCreatedAt(t)
	return admc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (admc *ApplicationDataMaterialCreate) SetNillableCreatedAt(t *time.Time) *ApplicationDataMaterialCreate {
	if t != nil {
		admc.SetCreatedAt(*t)
	}
	return admc
}

// SetUpdatedAt sets the "updated_at" field.
func (admc *ApplicationDataMaterialCreate) SetUpdatedAt(t time.Time) *ApplicationDataMaterialCreate {
	admc.mutation.SetUpdatedAt(t)
	return admc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (admc *ApplicationDataMaterialCreate) SetNillableUpdatedAt(t *time.Time) *ApplicationDataMaterialCreate {
	if t != nil {
		admc.SetUpdatedAt(*t)
	}
	return admc
}

// SetApplicationID sets the "application_id" field.
func (admc *ApplicationDataMaterialCreate) SetApplicationID(s string) *ApplicationDataMaterialCreate {
	admc.mutation.SetApplicationID(s)
	return admc
}

// SetVersion sets the "version" field.
func (admc *ApplicationDataMaterialCreate) SetVersion(s string) *ApplicationDataMaterialCreate {
	admc.mutation.SetVersion(s)
	return admc
}

// SetDigest sets the "digest" field.
func (admc *ApplicationDataMaterialCreate) SetDigest(s string) *ApplicationDataMaterialCreate {
	admc.mutation.SetDigest(s)
	return admc
}

// SetPayload sets the "payload" field.
func (admc *ApplicationDataMaterialCreate) SetPayload(s string) *ApplicationDataMaterialCreate {
	admc.mutation.SetPayload(s)
	return admc
}

// SetAdmittedByUserID sets the "admitted_by_user_id" field.
func (admc *ApplicationDataMaterialCreate) SetAdmittedByUserID(s string) *ApplicationDataMaterialCreate {
	admc.mutation.SetAdmittedByUserID(s)
	return admc
}

// SetID sets the "id" field.
func (admc *ApplicationDataMaterialCreate) SetID(s string) *ApplicationDataMaterialCreate {
	admc.mutation.SetID(s)
	return admc
}

// Mutation returns the ApplicationDataMaterialMutation object of the builder.
func (admc *ApplicationDataMaterialCreate) Mutation() *ApplicationDataMaterialMutation {
	return admc.mutation
}

// Save creates the ApplicationDataMaterial in the database.
func (admc *ApplicationDataMaterialCreate) Save(ctx context.Context) (*ApplicationDataMaterial, error) {
	admc.defaults()
	return withHooks(ctx, admc.sqlSave, admc.mutation, admc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (admc *ApplicationDataMaterialCreate) SaveX(ctx context.Context) *ApplicationDataMaterial {
	v, err := admc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (admc *ApplicationDataMaterialCreate) Exec(ctx context.Context) error {
	_, err := admc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (admc *ApplicationDataMaterialCreate) ExecX(ctx context.Context) {
	if err := admc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (admc *ApplicationDataMaterialCreate) defaults() {
	if _, ok := admc.mutation.CreatedAt(); !ok {
		v := applicationdatamaterial.DefaultCreatedAt()
		admc.mutation.SetCreatedAt(v)
	}
	if _, ok := admc.mutation.UpdatedAt(); !ok {
		v := applicationdatamaterial.DefaultUpdatedAt()
		admc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (admc *ApplicationDataMaterialCreate) check() error {
	if _, ok := admc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApplicationDataMaterial.created_at"`)}
	}
	if _, ok := admc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ApplicationDataMaterial.updated_at"`)}
	}
	if _, ok := admc.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "ApplicationDataMaterial.application_id"`)}
	}
	if v, ok := admc.mutation.ApplicationID(); ok {
		if err := applicationdatamaterial.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.application_id": %w`, err)}
		}
	}
	if _, ok := admc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ApplicationDataMaterial.version"`)}
	}
	if v, ok := admc.mutation.Version(); ok {
		if err := applicationdatamaterial.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.version": %w`, err)}
		}
	}
	if _, ok := admc.mutation.Digest(); !ok {
		return &ValidationError{Name: "digest", err: errors.New(`ent: missing required field "ApplicationDataMaterial.digest"`)}
	}
	if v, ok := admc.mutation.Digest(); ok {
		if err := applicationdatamaterial.DigestValidator(v); err != nil {
			return &ValidationError{Name: "digest", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.digest": %w`, err)}
		}
	}
	if _, ok := admc.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "ApplicationDataMaterial.payload"`)}
	}
	if v, ok := admc.mutation.Payload(); ok {
		if err := applicationdatamaterial.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.payload": %w`, err)}
		}
	}
	if _, ok := admc.mutation.AdmittedByUserID(); !ok {
		return &ValidationError{Name: "admitted_by_user_id", err: errors.New(`ent: missing required field "ApplicationDataMaterial.admitted_by_user_id"`)}
	}
	if v, ok := admc.mutation.AdmittedByUserID(); ok {
		if err := applicationdatamaterial.AdmittedByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "admitted_by_user_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.admitted_by_user_id": %w`, err)}
		}
	}
	if v, ok := admc.mutation.ID(); ok {
		if err := applicationdatamaterial.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.id": %w`, err)}
		}
	}
	return nil
}

func (admc *ApplicationDataMaterialCreate) sqlSave(ctx context.Context) (*ApplicationDataMaterial, error) {
	if err := admc.check(); err != nil {
		return nil, err
	}
	_node, _spec := admc.createSpec()
	if err := sqlgraph.CreateNode(ctx, admc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ApplicationDataMaterial.ID type: %T", _spec.ID.Value)
		}
	}
	admc.mutation.id = &_node.ID
	admc.mutation.done = true
	return _node, nil
}

func (admc *ApplicationDataMaterialCreate) createSpec() (*ApplicationDataMaterial, *sqlgraph.CreateSpec) {
	var (
		_node = &ApplicationDataMaterial{config: admc.config}
		_spec = sqlgraph.NewCreateSpec(applicationdatamaterial.Table, sqlgraph.NewFieldSpec(applicationdatamaterial.FieldID, field.TypeString))
	)
	if id, ok := admc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := admc.mutation.CreatedAt(); ok {
		_spec.SetField(applicationdatamaterial.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := admc.mutation.UpdatedAt(); ok {
		_spec.SetField(applicationdatamaterial.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := admc.mutation.ApplicationID(); ok {
		_spec.SetField(applicationdatamaterial.FieldApplicationID, field.TypeString, value)
		_node.ApplicationID = value
	}
	if value, ok := admc.mutation.Version(); ok {
		_spec.SetField(applicationdatamaterial.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := admc.mutation.Digest(); ok {
		_spec.SetField(applicationdatamaterial.FieldDigest, field.TypeString, value)
		_node.Digest = value
	}
	if value, ok := admc.mutation.Payload(); ok {
		_spec.SetField(applicationdatamaterial.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := admc.mutation.AdmittedByUserID(); ok {
		_spec.SetField(applicationdatamaterial.FieldAdmittedByUserID, field.TypeString, value)
		_node.AdmittedByUserID = value
	}
	return _node, _spec
}

// ApplicationDataMaterialCreateBulk is the builder for creating many ApplicationDataMaterial entities in bulk.
type ApplicationDataMaterialCreateBulk struct {
	config
	err      error
	builders []*ApplicationDataMaterialCreate
}

// Save creates the ApplicationDataMaterial entities in the database.
func (admcb *ApplicationDataMaterialCreateBulk) Save(ctx context.Context) ([]*ApplicationDataMaterial, error) {
	if admcb.err != nil {
		return nil, admcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(admcb.builders))
	nodes := make([]*ApplicationDataMaterial, len(admcb.builders))
	mutators := make([]Mutator, len(admcb.builders))
	for i := range admcb.builders {
		func(i int, root context.Context) {
			builder := admcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicationDataMaterialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, admcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, admcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, admcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (admcb *ApplicationDataMaterialCreateBulk) SaveX(ctx context.Context) []*ApplicationDataMaterial {
	v, err := admcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (admcb *ApplicationDataMaterialCreateBulk) Exec(ctx context.Context) error {
	_, err := admcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (admcb *ApplicationDataMaterialCreateBulk) ExecX(ctx context.Context) {
	if err := admcb.Exec(ctx); err != nil {
		panic(err)
	}
}
