// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/applicationrevision"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationRevisionCreate is the builder for creating a ApplicationRevision entity.
type ApplicationRevisionCreate struct {
	config
	mutation *ApplicationRevisionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (arc *ApplicationRevisionCreate) SetCreatedAt(t time.Time) *ApplicationRevisionCreate {
	arc.mutation.SetCreatedAt(t)
	return arc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (arc *ApplicationRevisionCreate) SetNillableCreatedAt(t *time.Time) *ApplicationRevisionCreate {
	if t != nil {
		arc.SetCreatedAt(*t)
	}
	return arc
}

// SetUpdatedAt sets the "updated_at" field.
func (arc *ApplicationRevisionCreate) SetUpdatedAt(t time.Time) *ApplicationRevisionCreate {
	arc.mutation.SetUpdatedAt(t)
	return arc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (arc *ApplicationRevisionCreate) SetNillableUpdatedAt(t *time.Time) *ApplicationRevisionCreate {
	if t != nil {
		arc.SetUpdatedAt(*t)
	}
	return arc
}

// SetApplicationID sets the "application_id" field.
func (arc *ApplicationRevisionCreate) SetApplicationID(s string) *ApplicationRevisionCreate {
	arc.mutation.SetApplicationID(s)
	return arc
}

// SetVersion sets the "version" field.
func (arc *ApplicationRevisionCreate) SetVersion(s string) *ApplicationRevisionCreate {
	arc.mutation.SetVersion(s)
	return arc
}

// SetDigest sets the "digest" field.
func (arc *ApplicationRevisionCreate) SetDigest(s string) *ApplicationRevisionCreate {
	arc.mutation.SetDigest(s)
	return arc
}

// SetPayload sets the "payload" field.
func (arc *ApplicationRevisionCreate) SetPayload(s string) *ApplicationRevisionCreate {
	arc.mutation.SetPayload(s)
	return arc
}

// SetAdmittedByUserID sets the "admitted_by_user_id" field.
func (arc *ApplicationRevisionCreate) SetAdmittedByUserID(s string) *ApplicationRevisionCreate {
	arc.mutation.SetAdmittedByUserID(s)
	return arc
}

// SetID sets the "id" field.
func (arc *ApplicationRevisionCreate) SetID(s string) *ApplicationRevisionCreate {
	arc.mutation.SetID(s)
	return arc
}

// Mutation returns the ApplicationRevisionMutation object of the builder.
func (arc *ApplicationRevisionCreate) Mutation() *ApplicationRevisionMutation {
	return arc.mutation
}

// Save creates the ApplicationRevision in the database.
func (arc *ApplicationRevisionCreate) Save(ctx context.Context) (*ApplicationRevision, error) {
	arc.defaults()
	return withHooks(ctx, arc.sqlSave, arc.mutation, arc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (arc *ApplicationRevisionCreate) SaveX(ctx context.Context) *ApplicationRevision {
	v, err := arc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arc *ApplicationRevisionCreate) Exec(ctx context.Context) error {
	_, err := arc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arc *ApplicationRevisionCreate) ExecX(ctx context.Context) {
	if err := arc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (arc *ApplicationRevisionCreate) defaults() {
	if _, ok := arc.mutation.CreatedAt(); !ok {
		v := applicationrevision.DefaultCreatedAt()
		arc.mutation.SetCreatedAt(v)
	}
	if _, ok := arc.mutation.UpdatedAt(); !ok {
		v := applicationrevision.DefaultUpdatedAt()
		arc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (arc *ApplicationRevisionCreate) check() error {
	if _, ok := arc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApplicationRevision.created_at"`)}
	}
	if _, ok := arc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ApplicationRevision.updated_at"`)}
	}
	if _, ok := arc.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "ApplicationRevision.application_id"`)}
	}
	if v, ok := arc.mutation.ApplicationID(); ok {
		if err := applicationrevision.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.application_id": %w`, err)}
		}
	}
	if _, ok := arc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ApplicationRevision.version"`)}
	}
	if v, ok := arc.mutation.Version(); ok {
		if err := applicationrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.version": %w`, err)}
		}
	}
	if _, ok := arc.mutation.Digest(); !ok {
		return &ValidationError{Name: "digest", err: errors.New(`ent: missing required field "ApplicationRevision.digest"`)}
	}
	if v, ok := arc.mutation.Digest(); ok {
		if err := applicationrevision.DigestValidator(v); err != nil {
			return &ValidationError{Name: "digest", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.digest": %w`, err)}
		}
	}
	if _, ok := arc.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "ApplicationRevision.payload"`)}
	}
	if v, ok := arc.mutation.Payload(); ok {
		if err := applicationrevision.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.payload": %w`, err)}
		}
	}
	if _, ok := arc.mutation.AdmittedByUserID(); !ok {
		return &ValidationError{Name: "admitted_by_user_id", err: errors.New(`ent: missing required field "ApplicationRevision.admitted_by_user_id"`)}
	}
	if v, ok := arc.mutation.AdmittedByUserID(); ok {
		if err := applicationrevision.AdmittedByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "admitted_by_user_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.admitted_by_user_id": %w`, err)}
		}
	}
	if v, ok := arc.mutation.ID(); ok {
		if err := applicationrevision.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ApplicationRevision.id": %w`, err)}
		}
	}
	return nil
}

func (arc *ApplicationRevisionCreate) sqlSave(ctx context.Context) (*ApplicationRevision, error) {
	if err := arc.check(); err != nil {
		return nil, err
	}
	_node, _spec := arc.createSpec()
	if err := sqlgraph.CreateNode(ctx, arc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ApplicationRevision.ID type: %T", _spec.ID.Value)
		}
	}
	arc.mutation.id = &_node.ID
	arc.mutation.done = true
	return _node, nil
}

func (arc *ApplicationRevisionCreate) createSpec() (*ApplicationRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &ApplicationRevision{config: arc.config}
		_spec = sqlgraph.NewCreateSpec(applicationrevision.Table, sqlgraph.NewFieldSpec(applicationrevision.FieldID, field.TypeString))
	)
	if id, ok := arc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := arc.mutation.CreatedAt(); ok {
		_spec.SetField(applicationrevision.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := arc.mutation.UpdatedAt(); ok {
		_spec.SetField(applicationrevision.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := arc.mutation.ApplicationID(); ok {
		_spec.SetField(applicationrevision.FieldApplicationID, field.TypeString, value)
		_node.ApplicationID = value
	}
	if value, ok := arc.mutation.Version(); ok {
		_spec.SetField(applicationrevision.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := arc.mutation.Digest(); ok {
		_spec.SetField(applicationrevision.FieldDigest, field.TypeString, value)
		_node.Digest = value
	}
	if value, ok := arc.mutation.Payload(); ok {
		_spec.SetField(applicationrevision.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := arc.mutation.AdmittedByUserID(); ok {
		_spec.SetField(applicationrevision.FieldAdmittedByUserID, field.TypeString, value)
		_node.AdmittedByUserID = value
	}
	return _node, _spec
}

// ApplicationRevisionCreateBulk is the builder for creating many ApplicationRevision entities in bulk.
type ApplicationRevisionCreateBulk struct {
	config
	err      error
	builders []*ApplicationRevisionCreate
}

// Save creates the ApplicationRevision entities in the database.
func (arcb *ApplicationRevisionCreateBulk) Save(ctx context.Context) ([]*ApplicationRevision, error) {
	if arcb.err != nil {
		return nil, arcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(arcb.builders))
	nodes := make([]*ApplicationRevision, len(arcb.builders))
	mutators := make([]Mutator, len(arcb.builders))
	for i := range arcb.builders {
		func(i int, root context.Context) {
			builder := arcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicationRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, arcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, arcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, arcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (arcb *ApplicationRevisionCreateBulk) SaveX(ctx context.Context) []*ApplicationRevision {
	v, err := arcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arcb *ApplicationRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := arcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arcb *ApplicationRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := arcb.Exec(ctx); err != nil {
		panic(err)
	}
}
