// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/applicationdatamaterial"
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationDataMaterialUpdate is the builder for updating ApplicationDataMaterial entities.
type ApplicationDataMaterialUpdate struct {
	config
	hooks    []Hook
	mutation *ApplicationDataMaterialMutation
}

// Where appends a list predicates to the ApplicationDataMaterialUpdate builder.
func (admu *ApplicationDataMaterialUpdate) Where(ps ...predicate.ApplicationDataMaterial) *ApplicationDataMaterialUpdate {
	admu.mutation.Where(ps...)
	return admu
}

// SetCreatedAt sets the "created_at" field.
func (admu *ApplicationDataMaterialUpdate) SetCreatedAt(t time.Time) *ApplicationDataMaterialUpdate {
	admu.mutation.SetCreatedAt(t)
	return admu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (admu *ApplicationDataMaterialUpdate) SetNillableCreatedAt(t *time.Time) *ApplicationDataMaterialUpdate {
	if t != nil {
		admu.SetCreatedAt(*t)
	}
	return admu
}

// SetUpdatedAt sets the "updated_at" field.
func (admu *ApplicationDataMaterialUpdate) SetUpdatedAt(t time.Time) *ApplicationDataMaterialUpdate {
	admu.mutation.SetUpdatedAt(t)
	return admu
}

// SetApplicationID sets the "application_id" field.
func (admu *ApplicationDataMaterialUpdate) SetApplicationID(s string) *ApplicationDataMaterialUpdate {
	admu.mutation.SetApplicationID(s)
	return admu
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (admu *ApplicationDataMaterialUpdate) SetNillableApplicationID(s *string) *ApplicationDataMaterialUpdate {
	if s != nil {
		admu.SetApplicationID(*s)
	}
	return admu
}

// SetVersion sets the "version" field.
func (admu *ApplicationDataMaterialUpdate) SetVersion(s string) *ApplicationDataMaterialUpdate {
	admu.mutation.SetVersion(s)
	return admu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (admu *ApplicationDataMaterialUpdate) SetNillableVersion(s *string) *ApplicationDataMaterialUpdate {
	if s != nil {
		admu.SetVersion(*s)
	}
	return admu
}

// SetDigest sets the "digest" field.
func (admu *ApplicationDataMaterialUpdate) SetDigest(s string) *ApplicationDataMaterialUpdate {
	admu.mutation.SetDigest(s)
	return admu
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (admu *ApplicationDataMaterialUpdate) SetNillableDigest(s *string) *ApplicationDataMaterialUpdate {
	if s != nil {
		admu.SetDigest(*s)
	}
	return admu
}

// SetPayload sets the "payload" field.
func (admu *ApplicationDataMaterialUpdate) SetPayload(s string) *ApplicationDataMaterialUpdate {
	admu.mutation.SetPayload(s)
	return admu
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (admu *ApplicationDataMaterialUpdate) SetNillablePayload(s *string) *ApplicationDataMaterialUpdate {
	if s != nil {
		admu.SetPayload(*s)
	}
	return admu
}

// SetAdmittedByUserID sets the "admitted_by_user_id" field.
func (admu *ApplicationDataMaterialUpdate) SetAdmittedByUserID(s string) *ApplicationDataMaterialUpdate {
	admu.mutation.SetAdmittedByUserID(s)
	return admu
}

// SetNillableAdmittedByUserID sets the "admitted_by_user_id" field if the given value is not nil.
func (admu *ApplicationDataMaterialUpdate) SetNillableAdmittedByUserID(s *string) *ApplicationDataMaterialUpdate {
	if s != nil {
		admu.SetAdmittedByUserID(*s)
	}
	return admu
}

// Mutation returns the ApplicationDataMaterialMutation object of the builder.
func (admu *ApplicationDataMaterialUpdate) Mutation() *ApplicationDataMaterialMutation {
	return admu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (admu *ApplicationDataMaterialUpdate) Save(ctx context.Context) (int, error) {
	admu.defaults()
	return withHooks(ctx, admu.sqlSave, admu.mutation, admu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (admu *ApplicationDataMaterialUpdate) SaveX(ctx context.Context) int {
	affected, err := admu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (admu *ApplicationDataMaterialUpdate) Exec(ctx context.Context) error {
	_, err := admu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (admu *ApplicationDataMaterialUpdate) ExecX(ctx context.Context) {
	if err := admu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (admu *ApplicationDataMaterialUpdate) defaults() {
	if _, ok := admu.mutation.UpdatedAt(); !ok {
		v := applicationdatamaterial.UpdateDefaultUpdatedAt()
		admu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (admu *ApplicationDataMaterialUpdate) check() error {
	if v, ok := admu.mutation.ApplicationID(); ok {
		if err := applicationdatamaterial.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.application_id": %w`, err)}
		}
	}
	if v, ok := admu.mutation.Version(); ok {
		if err := applicationdatamaterial.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.version": %w`, err)}
		}
	}
	if v, ok := admu.mutation.Digest(); ok {
		if err := applicationdatamaterial.DigestValidator(v); err != nil {
			return &ValidationError{Name: "digest", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.digest": %w`, err)}
		}
	}
	if v, ok := admu.mutation.Payload(); ok {
		if err := applicationdatamaterial.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.payload": %w`, err)}
		}
	}
	if v, ok := admu.mutation.AdmittedByUserID(); ok {
		if err := applicationdatamaterial.AdmittedByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "admitted_by_user_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.admitted_by_user_id": %w`, err)}
		}
	}
	return nil
}

func (admu *ApplicationDataMaterialUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := admu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(applicationdatamaterial.Table, applicationdatamaterial.Columns, sqlgraph.NewFieldSpec(applicationdatamaterial.FieldID, field.TypeString))
	if ps := admu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := admu.mutation.CreatedAt(); ok {
		_spec.SetField(applicationdatamaterial.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := admu.mutation.UpdatedAt(); ok {
		_spec.SetField(applicationdatamaterial.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := admu.mutation.ApplicationID(); ok {
		_spec.SetField(applicationdatamaterial.FieldApplicationID, field.TypeString, value)
	}
	if value, ok := admu.mutation.Version(); ok {
		_spec.SetField(applicationdatamaterial.FieldVersion, field.TypeString, value)
	}
	if value, ok := admu.mutation.Digest(); ok {
		_spec.SetField(applicationdatamaterial.FieldDigest, field.TypeString, value)
	}
	if value, ok := admu.mutation.Payload(); ok {
		_spec.SetField(applicationdatamaterial.FieldPayload, field.TypeString, value)
	}
	if value, ok := admu.mutation.AdmittedByUserID(); ok {
		_spec.SetField(applicationdatamaterial.FieldAdmittedByUserID, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, admu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationdatamaterial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	admu.mutation.done = true
	return n, nil
}

// ApplicationDataMaterialUpdateOne is the builder for updating a single ApplicationDataMaterial entity.
type ApplicationDataMaterialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApplicationDataMaterialMutation
}

// SetCreatedAt sets the "created_at" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetCreatedAt(t time.Time) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetCreatedAt(t)
	return admuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (admuo *ApplicationDataMaterialUpdateOne) SetNillableCreatedAt(t *time.Time) *ApplicationDataMaterialUpdateOne {
	if t != nil {
		admuo.SetCreatedAt(*t)
	}
	return admuo
}

// SetUpdatedAt sets the "updated_at" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetUpdatedAt(t time.Time) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetUpdatedAt(t)
	return admuo
}

// SetApplicationID sets the "application_id" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetApplicationID(s string) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetApplicationID(s)
	return admuo
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (admuo *ApplicationDataMaterialUpdateOne) SetNillableApplicationID(s *string) *ApplicationDataMaterialUpdateOne {
	if s != nil {
		admuo.SetApplicationID(*s)
	}
	return admuo
}

// SetVersion sets the "version" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetVersion(s string) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetVersion(s)
	return admuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (admuo *ApplicationDataMaterialUpdateOne) SetNillableVersion(s *string) *ApplicationDataMaterialUpdateOne {
	if s != nil {
		admuo.SetVersion(*s)
	}
	return admuo
}

// SetDigest sets the "digest" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetDigest(s string) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetDigest(s)
	return admuo
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (admuo *ApplicationDataMaterialUpdateOne) SetNillableDigest(s *string) *ApplicationDataMaterialUpdateOne {
	if s != nil {
		admuo.SetDigest(*s)
	}
	return admuo
}

// SetPayload sets the "payload" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetPayload(s string) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetPayload(s)
	return admuo
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (admuo *ApplicationDataMaterialUpdateOne) SetNillablePayload(s *string) *ApplicationDataMaterialUpdateOne {
	if s != nil {
		admuo.SetPayload(*s)
	}
	return admuo
}

// SetAdmittedByUserID sets the "admitted_by_user_id" field.
func (admuo *ApplicationDataMaterialUpdateOne) SetAdmittedByUserID(s string) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.SetAdmittedByUserID(s)
	return admuo
}

// SetNillableAdmittedByUserID sets the "admitted_by_user_id" field if the given value is not nil.
func (admuo *ApplicationDataMaterialUpdateOne) SetNillableAdmittedByUserID(s *string) *ApplicationDataMaterialUpdateOne {
	if s != nil {
		admuo.SetAdmittedByUserID(*s)
	}
	return admuo
}

// Mutation returns the ApplicationDataMaterialMutation object of the builder.
func (admuo *ApplicationDataMaterialUpdateOne) Mutation() *ApplicationDataMaterialMutation {
	return admuo.mutation
}

// Where appends a list predicates to the ApplicationDataMaterialUpdate builder.
func (admuo *ApplicationDataMaterialUpdateOne) Where(ps ...predicate.ApplicationDataMaterial) *ApplicationDataMaterialUpdateOne {
	admuo.mutation.Where(ps...)
	return admuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (admuo *ApplicationDataMaterialUpdateOne) Select(field string, fields ...string) *ApplicationDataMaterialUpdateOne {
	admuo.fields = append([]string{field}, fields...)
	return admuo
}

// Save executes the query and returns the updated ApplicationDataMaterial entity.
func (admuo *ApplicationDataMaterialUpdateOne) Save(ctx context.Context) (*ApplicationDataMaterial, error) {
	admuo.defaults()
	return withHooks(ctx, admuo.sqlSave, admuo.mutation, admuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (admuo *ApplicationDataMaterialUpdateOne) SaveX(ctx context.Context) *ApplicationDataMaterial {
	node, err := admuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (admuo *ApplicationDataMaterialUpdateOne) Exec(ctx context.Context) error {
	_, err := admuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (admuo *ApplicationDataMaterialUpdateOne) ExecX(ctx context.Context) {
	if err := admuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (admuo *ApplicationDataMaterialUpdateOne) defaults() {
	if _, ok := admuo.mutation.UpdatedAt(); !ok {
		v := applicationdatamaterial.UpdateDefaultUpdatedAt()
		admuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (admuo *ApplicationDataMaterialUpdateOne) check() error {
	if v, ok := admuo.mutation.ApplicationID(); ok {
		if err := applicationdatamaterial.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.application_id": %w`, err)}
		}
	}
	if v, ok := admuo.mutation.Version(); ok {
		if err := applicationdatamaterial.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.version": %w`, err)}
		}
	}
	if v, ok := admuo.mutation.Digest(); ok {
		if err := applicationdatamaterial.DigestValidator(v); err != nil {
			return &ValidationError{Name: "digest", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.digest": %w`, err)}
		}
	}
	if v, ok := admuo.mutation.Payload(); ok {
		if err := applicationdatamaterial.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.payload": %w`, err)}
		}
	}
	if v, ok := admuo.mutation.AdmittedByUserID(); ok {
		if err := applicationdatamaterial.AdmittedByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "admitted_by_user_id", err: fmt.Errorf(`ent: validator failed for field "ApplicationDataMaterial.admitted_by_user_id": %w`, err)}
		}
	}
	return nil
}

func (admuo *ApplicationDataMaterialUpdateOne) sqlSave(ctx context.Context) (_node *ApplicationDataMaterial, err error) {
	if err := admuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(applicationdatamaterial.Table, applicationdatamaterial.Columns, sqlgraph.NewFieldSpec(applicationdatamaterial.FieldID, field.TypeString))
	id, ok := admuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApplicationDataMaterial.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := admuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationdatamaterial.FieldID)
		for _, f := range fields {
			if !applicationdatamaterial.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != applicationdatamaterial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := admuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := admuo.mutation.CreatedAt(); ok {
		_spec.SetField(applicationdatamaterial.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := admuo.mutation.UpdatedAt(); ok {
		_spec.SetField(applicationdatamaterial.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := admuo.mutation.ApplicationID(); ok {
		_spec.SetField(applicationdatamaterial.FieldApplicationID, field.TypeString, value)
	}
	if value, ok := admuo.mutation.Version(); ok {
		_spec.SetField(applicationdatamaterial.FieldVersion, field.TypeString, value)
	}
	if value, ok := admuo.mutation.Digest(); ok {
		_spec.SetField(applicationdatamaterial.FieldDigest, field.TypeString, value)
	}
	if value, ok := admuo.mutation.Payload(); ok {
		_spec.SetField(applicationdatamaterial.FieldPayload, field.TypeString, value)
	}
	if value, ok := admuo.mutation.AdmittedByUserID(); ok {
		_spec.SetField(applicationdatamaterial.FieldAdmittedByUserID, field.TypeString, value)
	}
	_node = &ApplicationDataMaterial{config: admuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, admuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationdatamaterial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	admuo.mutation.done = true
	return _node, nil
}
