// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/applicationrevision"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ApplicationRevision is the model entity for the ApplicationRevision schema.
type ApplicationRevision struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ApplicationID holds the value of the "application_id" field.
	ApplicationID string `json:"application_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Digest holds the value of the "digest" field.
	Digest string `json:"digest,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// AdmittedByUserID holds the value of the "admitted_by_user_id" field.
	AdmittedByUserID string `json:"admitted_by_user_id,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApplicationRevision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case applicationrevision.FieldID, applicationrevision.FieldApplicationID, applicationrevision.FieldVersion, applicationrevision.FieldDigest, applicationrevision.FieldPayload, applicationrevision.FieldAdmittedByUserID:
			values[i] = new(sql.NullString)
		case applicationrevision.FieldCreatedAt, applicationrevision.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApplicationRevision fields.
func (ar *ApplicationRevision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case applicationrevision.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ar.ID = value.String
			}
		case applicationrevision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ar.CreatedAt = value.Time
			}
		case applicationrevision.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ar.UpdatedAt = value.Time
			}
		case applicationrevision.FieldApplicationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_id", values[i])
			} else if value.Valid {
				ar.ApplicationID = value.String
			}
		case applicationrevision.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				ar.Version = value.String
			}
		case applicationrevision.FieldDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field digest", values[i])
			} else if value.Valid {
				ar.Digest = value.String
			}
		case applicationrevision.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				ar.Payload = value.String
			}
		case applicationrevision.FieldAdmittedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admitted_by_user_id", values[i])
			} else if value.Valid {
				ar.AdmittedByUserID = value.String
			}
		default:
			ar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApplicationRevision.
// This includes values selected through modifiers, order, etc.
func (ar *ApplicationRevision) Value(name string) (ent.Value, error) {
	return ar.selectValues.Get(name)
}

// Update returns a builder for updating this ApplicationRevision.
// Note that you need to call ApplicationRevision.Unwrap() before calling this method if this ApplicationRevision
// was returned from a transaction, and the transaction was committed or rolled back.
func (ar *ApplicationRevision) Update() *ApplicationRevisionUpdateOne {
	return NewApplicationRevisionClient(ar.config).UpdateOne(ar)
}

// Unwrap unwraps the ApplicationRevision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ar *ApplicationRevision) Unwrap() *ApplicationRevision {
	_tx, ok := ar.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApplicationRevision is not a transactional entity")
	}
	ar.config.driver = _tx.drv
	return ar
}

// String implements the fmt.Stringer.
func (ar *ApplicationRevision) String() string {
	var builder strings.Builder
	builder.WriteString("ApplicationRevision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ar.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ar.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ar.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("application_id=")
	builder.WriteString(ar.ApplicationID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(ar.Version)
	builder.WriteString(", ")
	builder.WriteString("digest=")
	builder.WriteString(ar.Digest)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(ar.Payload)
	builder.WriteString(", ")
	builder.WriteString("admitted_by_user_id=")
	builder.WriteString(ar.AdmittedByUserID)
	builder.WriteByte(')')
	return builder.String()
}

// ApplicationRevisions is a parsable slice of ApplicationRevision.
type ApplicationRevisions []*ApplicationRevision
