// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"opl-cloud/services/control-plane/ent/applicationdatamaterial"
	"opl-cloud/services/control-plane/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationDataMaterialQuery is the builder for querying ApplicationDataMaterial entities.
type ApplicationDataMaterialQuery struct {
	config
	ctx        *QueryContext
	order      []applicationdatamaterial.OrderOption
	inters     []Interceptor
	predicates []predicate.ApplicationDataMaterial
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApplicationDataMaterialQuery builder.
func (admq *ApplicationDataMaterialQuery) Where(ps ...predicate.ApplicationDataMaterial) *ApplicationDataMaterialQuery {
	admq.predicates = append(admq.predicates, ps...)
	return admq
}

// Limit the number of records to be returned by this query.
func (admq *ApplicationDataMaterialQuery) Limit(limit int) *ApplicationDataMaterialQuery {
	admq.ctx.Limit = &limit
	return admq
}

// Offset to start from.
func (admq *ApplicationDataMaterialQuery) Offset(offset int) *ApplicationDataMaterialQuery {
	admq.ctx.Offset = &offset
	return admq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (admq *ApplicationDataMaterialQuery) Unique(unique bool) *ApplicationDataMaterialQuery {
	admq.ctx.Unique = &unique
	return admq
}

// Order specifies how the records should be ordered.
func (admq *ApplicationDataMaterialQuery) Order(o ...applicationdatamaterial.OrderOption) *ApplicationDataMaterialQuery {
	admq.order = append(admq.order, o...)
	return admq
}

// First returns the first ApplicationDataMaterial entity from the query.
// Returns a *NotFoundError when no ApplicationDataMaterial was found.
func (admq *ApplicationDataMaterialQuery) First(ctx context.Context) (*ApplicationDataMaterial, error) {
	nodes, err := admq.Limit(1).All(setContextOp(ctx, admq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{applicationdatamaterial.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) FirstX(ctx context.Context) *ApplicationDataMaterial {
	node, err := admq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApplicationDataMaterial ID from the query.
// Returns a *NotFoundError when no ApplicationDataMaterial ID was found.
func (admq *ApplicationDataMaterialQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = admq.Limit(1).IDs(setContextOp(ctx, admq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{applicationdatamaterial.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) FirstIDX(ctx context.Context) string {
	id, err := admq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApplicationDataMaterial entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApplicationDataMaterial entity is found.
// Returns a *NotFoundError when no ApplicationDataMaterial entities are found.
func (admq *ApplicationDataMaterialQuery) Only(ctx context.Context) (*ApplicationDataMaterial, error) {
	nodes, err := admq.Limit(2).All(setContextOp(ctx, admq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{applicationdatamaterial.Label}
	default:
		return nil, &NotSingularError{applicationdatamaterial.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) OnlyX(ctx context.Context) *ApplicationDataMaterial {
	node, err := admq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApplicationDataMaterial ID in the query.
// Returns a *NotSingularError when more than one ApplicationDataMaterial ID is found.
// Returns a *NotFoundError when no entities are found.
func (admq *ApplicationDataMaterialQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = admq.Limit(2).IDs(setContextOp(ctx, admq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{applicationdatamaterial.Label}
	default:
		err = &NotSingularError{applicationdatamaterial.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) OnlyIDX(ctx context.Context) string {
	id, err := admq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApplicationDataMaterials.
func (admq *ApplicationDataMaterialQuery) All(ctx context.Context) ([]*ApplicationDataMaterial, error) {
	ctx = setContextOp(ctx, admq.ctx, "All")
	if err := admq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApplicationDataMaterial, *ApplicationDataMaterialQuery]()
	return withInterceptors[[]*ApplicationDataMaterial](ctx, admq, qr, admq.inters)
}

// AllX is like All, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) AllX(ctx context.Context) []*ApplicationDataMaterial {
	nodes, err := admq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApplicationDataMaterial IDs.
func (admq *ApplicationDataMaterialQuery) IDs(ctx context.Context) (ids []string, err error) {
	if admq.ctx.Unique == nil && admq.path != nil {
		admq.Unique(true)
	}
	ctx = setContextOp(ctx, admq.ctx, "IDs")
	if err = admq.Select(applicationdatamaterial.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) IDsX(ctx context.Context) []string {
	ids, err := admq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (admq *ApplicationDataMaterialQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, admq.ctx, "Count")
	if err := admq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, admq, querierCount[*ApplicationDataMaterialQuery](), admq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) CountX(ctx context.Context) int {
	count, err := admq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (admq *ApplicationDataMaterialQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, admq.ctx, "Exist")
	switch _, err := admq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (admq *ApplicationDataMaterialQuery) ExistX(ctx context.Context) bool {
	exist, err := admq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApplicationDataMaterialQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (admq *ApplicationDataMaterialQuery) Clone() *ApplicationDataMaterialQuery {
	if admq == nil {
		return nil
	}
	return &ApplicationDataMaterialQuery{
		config:     admq.config,
		ctx:        admq.ctx.Clone(),
		order:      append([]applicationdatamaterial.OrderOption{}, admq.order...),
		inters:     append([]Interceptor{}, admq.inters...),
		predicates: append([]predicate.ApplicationDataMaterial{}, admq.predicates...),
		// clone intermediate query.
		sql:  admq.sql.Clone(),
		path: admq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApplicationDataMaterial.Query().
//		GroupBy(applicationdatamaterial.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (admq *ApplicationDataMaterialQuery) GroupBy(field string, fields ...string) *ApplicationDataMaterialGroupBy {
	admq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApplicationDataMaterialGroupBy{build: admq}
	grbuild.flds = &admq.ctx.Fields
	grbuild.label = applicationdatamaterial.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ApplicationDataMaterial.Query().
//		Select(applicationdatamaterial.FieldCreatedAt).
//		Scan(ctx, &v)
func (admq *ApplicationDataMaterialQuery) Select(fields ...string) *ApplicationDataMaterialSelect {
	admq.ctx.Fields = append(admq.ctx.Fields, fields...)
	sbuild := &ApplicationDataMaterialSelect{ApplicationDataMaterialQuery: admq}
	sbuild.label = applicationdatamaterial.Label
	sbuild.flds, sbuild.scan = &admq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApplicationDataMaterialSelect configured with the given aggregations.
func (admq *ApplicationDataMaterialQuery) Aggregate(fns ...AggregateFunc) *ApplicationDataMaterialSelect {
	return admq.Select().Aggregate(fns...)
}

func (admq *ApplicationDataMaterialQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range admq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, admq); err != nil {
				return err
			}
		}
	}
	for _, f := range admq.ctx.Fields {
		if !applicationdatamaterial.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if admq.path != nil {
		prev, err := admq.path(ctx)
		if err != nil {
			return err
		}
		admq.sql = prev
	}
	return nil
}

func (admq *ApplicationDataMaterialQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApplicationDataMaterial, error) {
	var (
		nodes = []*ApplicationDataMaterial{}
		_spec = admq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApplicationDataMaterial).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApplicationDataMaterial{config: admq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, admq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (admq *ApplicationDataMaterialQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := admq.querySpec()
	_spec.Node.Columns = admq.ctx.Fields
	if len(admq.ctx.Fields) > 0 {
		_spec.Unique = admq.ctx.Unique != nil && *admq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, admq.driver, _spec)
}

func (admq *ApplicationDataMaterialQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(applicationdatamaterial.Table, applicationdatamaterial.Columns, sqlgraph.NewFieldSpec(applicationdatamaterial.FieldID, field.TypeString))
	_spec.From = admq.sql
	if unique := admq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if admq.path != nil {
		_spec.Unique = true
	}
	if fields := admq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationdatamaterial.FieldID)
		for i := range fields {
			if fields[i] != applicationdatamaterial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := admq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := admq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := admq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := admq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (admq *ApplicationDataMaterialQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(admq.driver.Dialect())
	t1 := builder.Table(applicationdatamaterial.Table)
	columns := admq.ctx.Fields
	if len(columns) == 0 {
		columns = applicationdatamaterial.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if admq.sql != nil {
		selector = admq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if admq.ctx.Unique != nil && *admq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range admq.predicates {
		p(selector)
	}
	for _, p := range admq.order {
		p(selector)
	}
	if offset := admq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := admq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApplicationDataMaterialGroupBy is the group-by builder for ApplicationDataMaterial entities.
type ApplicationDataMaterialGroupBy struct {
	selector
	build *ApplicationDataMaterialQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (admgb *ApplicationDataMaterialGroupBy) Aggregate(fns ...AggregateFunc) *ApplicationDataMaterialGroupBy {
	admgb.fns = append(admgb.fns, fns...)
	return admgb
}

// Scan applies the selector query and scans the result into the given value.
func (admgb *ApplicationDataMaterialGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, admgb.build.ctx, "GroupBy")
	if err := admgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApplicationDataMaterialQuery, *ApplicationDataMaterialGroupBy](ctx, admgb.build, admgb, admgb.build.inters, v)
}

func (admgb *ApplicationDataMaterialGroupBy) sqlScan(ctx context.Context, root *ApplicationDataMaterialQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(admgb.fns))
	for _, fn := range admgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*admgb.flds)+len(admgb.fns))
		for _, f := range *admgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*admgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := admgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApplicationDataMaterialSelect is the builder for selecting fields of ApplicationDataMaterial entities.
type ApplicationDataMaterialSelect struct {
	*ApplicationDataMaterialQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (adms *ApplicationDataMaterialSelect) Aggregate(fns ...AggregateFunc) *ApplicationDataMaterialSelect {
	adms.fns = append(adms.fns, fns...)
	return adms
}

// Scan applies the selector query and scans the result into the given value.
func (adms *ApplicationDataMaterialSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, adms.ctx, "Select")
	if err := adms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApplicationDataMaterialQuery, *ApplicationDataMaterialSelect](ctx, adms.ApplicationDataMaterialQuery, adms, adms.inters, v)
}

func (adms *ApplicationDataMaterialSelect) sqlScan(ctx context.Context, root *ApplicationDataMaterialQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(adms.fns))
	for _, fn := range adms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*adms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := adms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
