// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/applicationdatamaterial"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ApplicationDataMaterial is the model entity for the ApplicationDataMaterial schema.
type ApplicationDataMaterial struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ApplicationID holds the value of the "application_id" field.
	ApplicationID string `json:"application_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Digest holds the value of the "digest" field.
	Digest string `json:"digest,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// AdmittedByUserID holds the value of the "admitted_by_user_id" field.
	AdmittedByUserID string `json:"admitted_by_user_id,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApplicationDataMaterial) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case applicationdatamaterial.FieldID, applicationdatamaterial.FieldApplicationID, applicationdatamaterial.FieldVersion, applicationdatamaterial.FieldDigest, applicationdatamaterial.FieldPayload, applicationdatamaterial.FieldAdmittedByUserID:
			values[i] = new(sql.NullString)
		case applicationdatamaterial.FieldCreatedAt, applicationdatamaterial.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApplicationDataMaterial fields.
func (adm *ApplicationDataMaterial) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case applicationdatamaterial.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				adm.ID = value.String
			}
		case applicationdatamaterial.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				adm.CreatedAt = value.Time
			}
		case applicationdatamaterial.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				adm.UpdatedAt = value.Time
			}
		case applicationdatamaterial.FieldApplicationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_id", values[i])
			} else if value.Valid {
				adm.ApplicationID = value.String
			}
		case applicationdatamaterial.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				adm.Version = value.String
			}
		case applicationdatamaterial.FieldDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field digest", values[i])
			} else if value.Valid {
				adm.Digest = value.String
			}
		case applicationdatamaterial.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				adm.Payload = value.String
			}
		case applicationdatamaterial.FieldAdmittedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admitted_by_user_id", values[i])
			} else if value.Valid {
				adm.AdmittedByUserID = value.String
			}
		default:
			adm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApplicationDataMaterial.
// This includes values selected through modifiers, order, etc.
func (adm *ApplicationDataMaterial) Value(name string) (ent.Value, error) {
	return adm.selectValues.Get(name)
}

// Update returns a builder for updating this ApplicationDataMaterial.
// Note that you need to call ApplicationDataMaterial.Unwrap() before calling this method if this ApplicationDataMaterial
// was returned from a transaction, and the transaction was committed or rolled back.
func (adm *ApplicationDataMaterial) Update() *ApplicationDataMaterialUpdateOne {
	return NewApplicationDataMaterialClient(adm.config).UpdateOne(adm)
}

// Unwrap unwraps the ApplicationDataMaterial entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (adm *ApplicationDataMaterial) Unwrap() *ApplicationDataMaterial {
	_tx, ok := adm.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApplicationDataMaterial is not a transactional entity")
	}
	adm.config.driver = _tx.drv
	return adm
}

// String implements the fmt.Stringer.
func (adm *ApplicationDataMaterial) String() string {
	var builder strings.Builder
	builder.WriteString("ApplicationDataMaterial(")
	builder.WriteString(fmt.Sprintf("id=%v, ", adm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(adm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(adm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("application_id=")
	builder.WriteString(adm.ApplicationID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(adm.Version)
	builder.WriteString(", ")
	builder.WriteString("digest=")
	builder.WriteString(adm.Digest)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(adm.Payload)
	builder.WriteString(", ")
	builder.WriteString("admitted_by_user_id=")
	builder.WriteString(adm.AdmittedByUserID)
	builder.WriteByte(')')
	return builder.String()
}

// ApplicationDataMaterials is a parsable slice of ApplicationDataMaterial.
type ApplicationDataMaterials []*ApplicationDataMaterial
