// Code generated by ent, DO NOT EDIT.

package ent

import (
	"opl-cloud/services/control-plane/ent/account"
	"opl-cloud/services/control-plane/ent/adminauditevent"
	"opl-cloud/services/control-plane/ent/announcement"
	"opl-cloud/services/control-plane/ent/announcementread"
	"opl-cloud/services/control-plane/ent/archivedadminauditevent"
	"opl-cloud/services/control-plane/ent/authattempt"
	"opl-cloud/services/control-plane/ent/billingreconciliation"
	"opl-cloud/services/control-plane/ent/computeallocation"
	"opl-cloud/services/control-plane/ent/productione2erecord"
	"opl-cloud/services/control-plane/ent/projecttasksynchead"
	"opl-cloud/services/control-plane/ent/runtimeoperation"
	"opl-cloud/services/control-plane/ent/schema"
	"opl-cloud/services/control-plane/ent/session"
	"opl-cloud/services/control-plane/ent/storageattachment"
	"opl-cloud/services/control-plane/ent/storagevolume"
	"opl-cloud/services/control-plane/ent/user"
	"opl-cloud/services/control-plane/ent/workspace"
	"opl-cloud/services/control-plane/ent/workspacesyncevent"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[1].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[2].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescOwnerUserID is the schema descriptor for owner_user_id field.
	accountDescOwnerUserID := accountFields[3].Descriptor()
	// account.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	account.OwnerUserIDValidator = accountDescOwnerUserID.Validators[0].(func(string) error)
	// accountDescSub2apiUserID is the schema descriptor for sub2api_user_id field.
	accountDescSub2apiUserID := accountFields[4].Descriptor()
	// account.Sub2apiUserIDValidator is a validator for the "sub2api_user_id" field. It is called by the builders before save.
	account.Sub2apiUserIDValidator = accountDescSub2apiUserID.Validators[0].(func(int64) error)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[5].Descriptor()
	// account.DefaultName holds the default value on creation for the name field.
	account.DefaultName = accountDescName.Default.(string)
	// accountDescStatus is the schema descriptor for status field.
	accountDescStatus := accountFields[6].Descriptor()
	// account.DefaultStatus holds the default value on creation for the status field.
	account.DefaultStatus = accountDescStatus.Default.(string)
	// accountDescWorkspacePurchaseEnabled is the schema descriptor for workspace_purchase_enabled field.
	accountDescWorkspacePurchaseEnabled := accountFields[7].Descriptor()
	// account.DefaultWorkspacePurchaseEnabled holds the default value on creation for the workspace_purchase_enabled field.
	account.DefaultWorkspacePurchaseEnabled = accountDescWorkspacePurchaseEnabled.Default.(bool)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.IDValidator is a validator for the "id" field. It is called by the builders before save.
	account.IDValidator = accountDescID.Validators[0].(func(string) error)
	adminauditeventFields := schema.AdminAuditEvent{}.Fields()
	_ = adminauditeventFields
	// adminauditeventDescCreatedAt is the schema descriptor for created_at field.
	adminauditeventDescCreatedAt := adminauditeventFields[1].Descriptor()
	// adminauditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminauditevent.DefaultCreatedAt = adminauditeventDescCreatedAt.Default.(func() time.Time)
	// adminauditeventDescUpdatedAt is the schema descriptor for updated_at field.
	adminauditeventDescUpdatedAt := adminauditeventFields[2].Descriptor()
	// adminauditevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminauditevent.DefaultUpdatedAt = adminauditeventDescUpdatedAt.Default.(func() time.Time)
	// adminauditevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminauditevent.UpdateDefaultUpdatedAt = adminauditeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminauditeventDescActorUserID is the schema descriptor for actor_user_id field.
	adminauditeventDescActorUserID := adminauditeventFields[3].Descriptor()
	// adminauditevent.DefaultActorUserID holds the default value on creation for the actor_user_id field.
	adminauditevent.DefaultActorUserID = adminauditeventDescActorUserID.Default.(string)
	// adminauditeventDescActorRole is the schema descriptor for actor_role field.
	adminauditeventDescActorRole := adminauditeventFields[4].Descriptor()
	// adminauditevent.DefaultActorRole holds the default value on creation for the actor_role field.
	adminauditevent.DefaultActorRole = adminauditeventDescActorRole.Default.(string)
	// adminauditeventDescActorAccountID is the schema descriptor for actor_account_id field.
	adminauditeventDescActorAccountID := adminauditeventFields[5].Descriptor()
	// adminauditevent.DefaultActorAccountID holds the default value on creation for the actor_account_id field.
	adminauditevent.DefaultActorAccountID = adminauditeventDescActorAccountID.Default.(string)
	// adminauditeventDescTargetAccountID is the schema descriptor for target_account_id field.
	adminauditeventDescTargetAccountID := adminauditeventFields[6].Descriptor()
	// adminauditevent.DefaultTargetAccountID holds the default value on creation for the target_account_id field.
	adminauditevent.DefaultTargetAccountID = adminauditeventDescTargetAccountID.Default.(string)
	// adminauditeventDescAction is the schema descriptor for action field.
	adminauditeventDescAction := adminauditeventFields[7].Descriptor()
	// adminauditevent.DefaultAction holds the default value on creation for the action field.
	adminauditevent.DefaultAction = adminauditeventDescAction.Default.(string)
	// adminauditeventDescResourceKind is the schema descriptor for resource_kind field.
	adminauditeventDescResourceKind := adminauditeventFields[8].Descriptor()
	// adminauditevent.DefaultResourceKind holds the default value on creation for the resource_kind field.
	adminauditevent.DefaultResourceKind = adminauditeventDescResourceKind.Default.(string)
	// adminauditeventDescResourceID is the schema descriptor for resource_id field.
	adminauditeventDescResourceID := adminauditeventFields[9].Descriptor()
	// adminauditevent.DefaultResourceID holds the default value on creation for the resource_id field.
	adminauditevent.DefaultResourceID = adminauditeventDescResourceID.Default.(string)
	// adminauditeventDescIPAddress is the schema descriptor for ip_address field.
	adminauditeventDescIPAddress := adminauditeventFields[10].Descriptor()
	// adminauditevent.DefaultIPAddress holds the default value on creation for the ip_address field.
	adminauditevent.DefaultIPAddress = adminauditeventDescIPAddress.Default.(string)
	// adminauditeventDescUserAgent is the schema descriptor for user_agent field.
	adminauditeventDescUserAgent := adminauditeventFields[11].Descriptor()
	// adminauditevent.DefaultUserAgent holds the default value on creation for the user_agent field.
	adminauditevent.DefaultUserAgent = adminauditeventDescUserAgent.Default.(string)
	// adminauditeventDescBeforeJSON is the schema descriptor for before_json field.
	adminauditeventDescBeforeJSON := adminauditeventFields[12].Descriptor()
	// adminauditevent.DefaultBeforeJSON holds the default value on creation for the before_json field.
	adminauditevent.DefaultBeforeJSON = adminauditeventDescBeforeJSON.Default.(string)
	// adminauditeventDescAfterJSON is the schema descriptor for after_json field.
	adminauditeventDescAfterJSON := adminauditeventFields[13].Descriptor()
	// adminauditevent.DefaultAfterJSON holds the default value on creation for the after_json field.
	adminauditevent.DefaultAfterJSON = adminauditeventDescAfterJSON.Default.(string)
	// adminauditeventDescResult is the schema descriptor for result field.
	adminauditeventDescResult := adminauditeventFields[14].Descriptor()
	// adminauditevent.DefaultResult holds the default value on creation for the result field.
	adminauditevent.DefaultResult = adminauditeventDescResult.Default.(string)
	// adminauditeventDescID is the schema descriptor for id field.
	adminauditeventDescID := adminauditeventFields[0].Descriptor()
	// adminauditevent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	adminauditevent.IDValidator = adminauditeventDescID.Validators[0].(func(string) error)
	announcementFields := schema.Announcement{}.Fields()
	_ = announcementFields
	// announcementDescCreatedAt is the schema descriptor for created_at field.
	announcementDescCreatedAt := announcementFields[1].Descriptor()
	// announcement.DefaultCreatedAt holds the default value on creation for the created_at field.
	announcement.DefaultCreatedAt = announcementDescCreatedAt.Default.(func() time.Time)
	// announcementDescUpdatedAt is the schema descriptor for updated_at field.
	announcementDescUpdatedAt := announcementFields[2].Descriptor()
	// announcement.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	announcement.DefaultUpdatedAt = announcementDescUpdatedAt.Default.(func() time.Time)
	// announcement.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	announcement.UpdateDefaultUpdatedAt = announcementDescUpdatedAt.UpdateDefault.(func() time.Time)
	// announcementDescTitle is the schema descriptor for title field.
	announcementDescTitle := announcementFields[3].Descriptor()
	// announcement.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	announcement.TitleValidator = announcementDescTitle.Validators[0].(func(string) error)
	// announcementDescBody is the schema descriptor for body field.
	announcementDescBody := announcementFields[4].Descriptor()
	// announcement.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	announcement.BodyValidator = announcementDescBody.Validators[0].(func(string) error)
	// announcementDescStatus is the schema descriptor for status field.
	announcementDescStatus := announcementFields[5].Descriptor()
	// announcement.DefaultStatus holds the default value on creation for the status field.
	announcement.DefaultStatus = announcementDescStatus.Default.(string)
	// announcementDescStartsAt is the schema descriptor for starts_at field.
	announcementDescStartsAt := announcementFields[6].Descriptor()
	// announcement.DefaultStartsAt holds the default value on creation for the starts_at field.
	announcement.DefaultStartsAt = announcementDescStartsAt.Default.(string)
	// announcementDescEndsAt is the schema descriptor for ends_at field.
	announcementDescEndsAt := announcementFields[7].Descriptor()
	// announcement.DefaultEndsAt holds the default value on creation for the ends_at field.
	announcement.DefaultEndsAt = announcementDescEndsAt.Default.(string)
	// announcementDescPublishedAt is the schema descriptor for published_at field.
	announcementDescPublishedAt := announcementFields[8].Descriptor()
	// announcement.DefaultPublishedAt holds the default value on creation for the published_at field.
	announcement.DefaultPublishedAt = announcementDescPublishedAt.Default.(string)
	// announcementDescCreatedByUserID is the schema descriptor for created_by_user_id field.
	announcementDescCreatedByUserID := announcementFields[9].Descriptor()
	// announcement.CreatedByUserIDValidator is a validator for the "created_by_user_id" field. It is called by the builders before save.
	announcement.CreatedByUserIDValidator = announcementDescCreatedByUserID.Validators[0].(func(string) error)
	// announcementDescUpdatedByUserID is the schema descriptor for updated_by_user_id field.
	announcementDescUpdatedByUserID := announcementFields[10].Descriptor()
	// announcement.UpdatedByUserIDValidator is a validator for the "updated_by_user_id" field. It is called by the builders before save.
	announcement.UpdatedByUserIDValidator = announcementDescUpdatedByUserID.Validators[0].(func(string) error)
	// announcementDescID is the schema descriptor for id field.
	announcementDescID := announcementFields[0].Descriptor()
	// announcement.IDValidator is a validator for the "id" field. It is called by the builders before save.
	announcement.IDValidator = announcementDescID.Validators[0].(func(string) error)
	announcementreadFields := schema.AnnouncementRead{}.Fields()
	_ = announcementreadFields
	// announcementreadDescCreatedAt is the schema descriptor for created_at field.
	announcementreadDescCreatedAt := announcementreadFields[1].Descriptor()
	// announcementread.DefaultCreatedAt holds the default value on creation for the created_at field.
	announcementread.DefaultCreatedAt = announcementreadDescCreatedAt.Default.(func() time.Time)
	// announcementreadDescUpdatedAt is the schema descriptor for updated_at field.
	announcementreadDescUpdatedAt := announcementreadFields[2].Descriptor()
	// announcementread.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	announcementread.DefaultUpdatedAt = announcementreadDescUpdatedAt.Default.(func() time.Time)
	// announcementread.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	announcementread.UpdateDefaultUpdatedAt = announcementreadDescUpdatedAt.UpdateDefault.(func() time.Time)
	// announcementreadDescAnnouncementID is the schema descriptor for announcement_id field.
	announcementreadDescAnnouncementID := announcementreadFields[3].Descriptor()
	// announcementread.AnnouncementIDValidator is a validator for the "announcement_id" field. It is called by the builders before save.
	announcementread.AnnouncementIDValidator = announcementreadDescAnnouncementID.Validators[0].(func(string) error)
	// announcementreadDescUserID is the schema descriptor for user_id field.
	announcementreadDescUserID := announcementreadFields[4].Descriptor()
	// announcementread.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	announcementread.UserIDValidator = announcementreadDescUserID.Validators[0].(func(string) error)
	// announcementreadDescReadAt is the schema descriptor for read_at field.
	announcementreadDescReadAt := announcementreadFields[5].Descriptor()
	// announcementread.ReadAtValidator is a validator for the "read_at" field. It is called by the builders before save.
	announcementread.ReadAtValidator = announcementreadDescReadAt.Validators[0].(func(string) error)
	// announcementreadDescID is the schema descriptor for id field.
	announcementreadDescID := announcementreadFields[0].Descriptor()
	// announcementread.IDValidator is a validator for the "id" field. It is called by the builders before save.
	announcementread.IDValidator = announcementreadDescID.Validators[0].(func(string) error)
	archivedadminauditeventFields := schema.ArchivedAdminAuditEvent{}.Fields()
	_ = archivedadminauditeventFields
	// archivedadminauditeventDescCreatedAt is the schema descriptor for created_at field.
	archivedadminauditeventDescCreatedAt := archivedadminauditeventFields[1].Descriptor()
	// archivedadminauditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	archivedadminauditevent.DefaultCreatedAt = archivedadminauditeventDescCreatedAt.Default.(func() time.Time)
	// archivedadminauditeventDescUpdatedAt is the schema descriptor for updated_at field.
	archivedadminauditeventDescUpdatedAt := archivedadminauditeventFields[2].Descriptor()
	// archivedadminauditevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	archivedadminauditevent.DefaultUpdatedAt = archivedadminauditeventDescUpdatedAt.Default.(func() time.Time)
	// archivedadminauditevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	archivedadminauditevent.UpdateDefaultUpdatedAt = archivedadminauditeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// archivedadminauditeventDescActorUserID is the schema descriptor for actor_user_id field.
	archivedadminauditeventDescActorUserID := archivedadminauditeventFields[3].Descriptor()
	// archivedadminauditevent.DefaultActorUserID holds the default value on creation for the actor_user_id field.
	archivedadminauditevent.DefaultActorUserID = archivedadminauditeventDescActorUserID.Default.(string)
	// archivedadminauditeventDescActorRole is the schema descriptor for actor_role field.
	archivedadminauditeventDescActorRole := archivedadminauditeventFields[4].Descriptor()
	// archivedadminauditevent.DefaultActorRole holds the default value on creation for the actor_role field.
	archivedadminauditevent.DefaultActorRole = archivedadminauditeventDescActorRole.Default.(string)
	// archivedadminauditeventDescActorAccountID is the schema descriptor for actor_account_id field.
	archivedadminauditeventDescActorAccountID := archivedadminauditeventFields[5].Descriptor()
	// archivedadminauditevent.DefaultActorAccountID holds the default value on creation for the actor_account_id field.
	archivedadminauditevent.DefaultActorAccountID = archivedadminauditeventDescActorAccountID.Default.(string)
	// archivedadminauditeventDescTargetAccountID is the schema descriptor for target_account_id field.
	archivedadminauditeventDescTargetAccountID := archivedadminauditeventFields[6].Descriptor()
	// archivedadminauditevent.DefaultTargetAccountID holds the default value on creation for the target_account_id field.
	archivedadminauditevent.DefaultTargetAccountID = archivedadminauditeventDescTargetAccountID.Default.(string)
	// archivedadminauditeventDescAction is the schema descriptor for action field.
	archivedadminauditeventDescAction := archivedadminauditeventFields[7].Descriptor()
	// archivedadminauditevent.DefaultAction holds the default value on creation for the action field.
	archivedadminauditevent.DefaultAction = archivedadminauditeventDescAction.Default.(string)
	// archivedadminauditeventDescResourceKind is the schema descriptor for resource_kind field.
	archivedadminauditeventDescResourceKind := archivedadminauditeventFields[8].Descriptor()
	// archivedadminauditevent.DefaultResourceKind holds the default value on creation for the resource_kind field.
	archivedadminauditevent.DefaultResourceKind = archivedadminauditeventDescResourceKind.Default.(string)
	// archivedadminauditeventDescResourceID is the schema descriptor for resource_id field.
	archivedadminauditeventDescResourceID := archivedadminauditeventFields[9].Descriptor()
	// archivedadminauditevent.DefaultResourceID holds the default value on creation for the resource_id field.
	archivedadminauditevent.DefaultResourceID = archivedadminauditeventDescResourceID.Default.(string)
	// archivedadminauditeventDescIPAddress is the schema descriptor for ip_address field.
	archivedadminauditeventDescIPAddress := archivedadminauditeventFields[10].Descriptor()
	// archivedadminauditevent.DefaultIPAddress holds the default value on creation for the ip_address field.
	archivedadminauditevent.DefaultIPAddress = archivedadminauditeventDescIPAddress.Default.(string)
	// archivedadminauditeventDescUserAgent is the schema descriptor for user_agent field.
	archivedadminauditeventDescUserAgent := archivedadminauditeventFields[11].Descriptor()
	// archivedadminauditevent.DefaultUserAgent holds the default value on creation for the user_agent field.
	archivedadminauditevent.DefaultUserAgent = archivedadminauditeventDescUserAgent.Default.(string)
	// archivedadminauditeventDescBeforeJSON is the schema descriptor for before_json field.
	archivedadminauditeventDescBeforeJSON := archivedadminauditeventFields[12].Descriptor()
	// archivedadminauditevent.DefaultBeforeJSON holds the default value on creation for the before_json field.
	archivedadminauditevent.DefaultBeforeJSON = archivedadminauditeventDescBeforeJSON.Default.(string)
	// archivedadminauditeventDescAfterJSON is the schema descriptor for after_json field.
	archivedadminauditeventDescAfterJSON := archivedadminauditeventFields[13].Descriptor()
	// archivedadminauditevent.DefaultAfterJSON holds the default value on creation for the after_json field.
	archivedadminauditevent.DefaultAfterJSON = archivedadminauditeventDescAfterJSON.Default.(string)
	// archivedadminauditeventDescResult is the schema descriptor for result field.
	archivedadminauditeventDescResult := archivedadminauditeventFields[14].Descriptor()
	// archivedadminauditevent.DefaultResult holds the default value on creation for the result field.
	archivedadminauditevent.DefaultResult = archivedadminauditeventDescResult.Default.(string)
	// archivedadminauditeventDescID is the schema descriptor for id field.
	archivedadminauditeventDescID := archivedadminauditeventFields[0].Descriptor()
	// archivedadminauditevent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	archivedadminauditevent.IDValidator = archivedadminauditeventDescID.Validators[0].(func(string) error)
	authattemptFields := schema.AuthAttempt{}.Fields()
	_ = authattemptFields
	// authattemptDescCreatedAt is the schema descriptor for created_at field.
	authattemptDescCreatedAt := authattemptFields[1].Descriptor()
	// authattempt.DefaultCreatedAt holds the default value on creation for the created_at field.
	authattempt.DefaultCreatedAt = authattemptDescCreatedAt.Default.(func() time.Time)
	// authattemptDescUpdatedAt is the schema descriptor for updated_at field.
	authattemptDescUpdatedAt := authattemptFields[2].Descriptor()
	// authattempt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authattempt.DefaultUpdatedAt = authattemptDescUpdatedAt.Default.(func() time.Time)
	// authattempt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authattempt.UpdateDefaultUpdatedAt = authattemptDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authattemptDescEmail is the schema descriptor for email field.
	authattemptDescEmail := authattemptFields[3].Descriptor()
	// authattempt.DefaultEmail holds the default value on creation for the email field.
	authattempt.DefaultEmail = authattemptDescEmail.Default.(string)
	// authattemptDescStatus is the schema descriptor for status field.
	authattemptDescStatus := authattemptFields[4].Descriptor()
	// authattempt.DefaultStatus holds the default value on creation for the status field.
	authattempt.DefaultStatus = authattemptDescStatus.Default.(string)
	// authattemptDescReason is the schema descriptor for reason field.
	authattemptDescReason := authattemptFields[5].Descriptor()
	// authattempt.DefaultReason holds the default value on creation for the reason field.
	authattempt.DefaultReason = authattemptDescReason.Default.(string)
	// authattemptDescIPAddress is the schema descriptor for ip_address field.
	authattemptDescIPAddress := authattemptFields[6].Descriptor()
	// authattempt.DefaultIPAddress holds the default value on creation for the ip_address field.
	authattempt.DefaultIPAddress = authattemptDescIPAddress.Default.(string)
	// authattemptDescUserAgent is the schema descriptor for user_agent field.
	authattemptDescUserAgent := authattemptFields[7].Descriptor()
	// authattempt.DefaultUserAgent holds the default value on creation for the user_agent field.
	authattempt.DefaultUserAgent = authattemptDescUserAgent.Default.(string)
	// authattemptDescID is the schema descriptor for id field.
	authattemptDescID := authattemptFields[0].Descriptor()
	// authattempt.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authattempt.IDValidator = authattemptDescID.Validators[0].(func(string) error)
	billingreconciliationFields := schema.BillingReconciliation{}.Fields()
	_ = billingreconciliationFields
	// billingreconciliationDescCreatedAt is the schema descriptor for created_at field.
	billingreconciliationDescCreatedAt := billingreconciliationFields[1].Descriptor()
	// billingreconciliation.DefaultCreatedAt holds the default value on creation for the created_at field.
	billingreconciliation.DefaultCreatedAt = billingreconciliationDescCreatedAt.Default.(func() time.Time)
	// billingreconciliationDescUpdatedAt is the schema descriptor for updated_at field.
	billingreconciliationDescUpdatedAt := billingreconciliationFields[2].Descriptor()
	// billingreconciliation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	billingreconciliation.DefaultUpdatedAt = billingreconciliationDescUpdatedAt.Default.(func() time.Time)
	// billingreconciliation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	billingreconciliation.UpdateDefaultUpdatedAt = billingreconciliationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// billingreconciliationDescStatus is the schema descriptor for status field.
	billingreconciliationDescStatus := billingreconciliationFields[3].Descriptor()
	// billingreconciliation.DefaultStatus holds the default value on creation for the status field.
	billingreconciliation.DefaultStatus = billingreconciliationDescStatus.Default.(string)
	// billingreconciliationDescGuardStatus is the schema descriptor for guard_status field.
	billingreconciliationDescGuardStatus := billingreconciliationFields[4].Descriptor()
	// billingreconciliation.DefaultGuardStatus holds the default value on creation for the guard_status field.
	billingreconciliation.DefaultGuardStatus = billingreconciliationDescGuardStatus.Default.(string)
	// billingreconciliationDescGuardReason is the schema descriptor for guard_reason field.
	billingreconciliationDescGuardReason := billingreconciliationFields[5].Descriptor()
	// billingreconciliation.DefaultGuardReason holds the default value on creation for the guard_reason field.
	billingreconciliation.DefaultGuardReason = billingreconciliationDescGuardReason.Default.(string)
	// billingreconciliationDescMessageAuthor is the schema descriptor for message_author field.
	billingreconciliationDescMessageAuthor := billingreconciliationFields[6].Descriptor()
	// billingreconciliation.DefaultMessageAuthor holds the default value on creation for the message_author field.
	billingreconciliation.DefaultMessageAuthor = billingreconciliationDescMessageAuthor.Default.(string)
	// billingreconciliationDescMessageText is the schema descriptor for message_text field.
	billingreconciliationDescMessageText := billingreconciliationFields[7].Descriptor()
	// billingreconciliation.DefaultMessageText holds the default value on creation for the message_text field.
	billingreconciliation.DefaultMessageText = billingreconciliationDescMessageText.Default.(string)
	// billingreconciliationDescMessageCreatedAt is the schema descriptor for message_created_at field.
	billingreconciliationDescMessageCreatedAt := billingreconciliationFields[8].Descriptor()
	// billingreconciliation.DefaultMessageCreatedAt holds the default value on creation for the message_created_at field.
	billingreconciliation.DefaultMessageCreatedAt = billingreconciliationDescMessageCreatedAt.Default.(string)
	// billingreconciliationDescGuardBlockNewWorkspaces is the schema descriptor for guard_block_new_workspaces field.
	billingreconciliationDescGuardBlockNewWorkspaces := billingreconciliationFields[9].Descriptor()
	// billingreconciliation.DefaultGuardBlockNewWorkspaces holds the default value on creation for the guard_block_new_workspaces field.
	billingreconciliation.DefaultGuardBlockNewWorkspaces = billingreconciliationDescGuardBlockNewWorkspaces.Default.(bool)
	// billingreconciliationDescReports is the schema descriptor for reports field.
	billingreconciliationDescReports := billingreconciliationFields[10].Descriptor()
	// billingreconciliation.DefaultReports holds the default value on creation for the reports field.
	billingreconciliation.DefaultReports = billingreconciliationDescReports.Default.(int64)
	// billingreconciliationDescID is the schema descriptor for id field.
	billingreconciliationDescID := billingreconciliationFields[0].Descriptor()
	// billingreconciliation.IDValidator is a validator for the "id" field. It is called by the builders before save.
	billingreconciliation.IDValidator = billingreconciliationDescID.Validators[0].(func(string) error)
	computeallocationFields := schema.ComputeAllocation{}.Fields()
	_ = computeallocationFields
	// computeallocationDescCreatedAt is the schema descriptor for created_at field.
	computeallocationDescCreatedAt := computeallocationFields[1].Descriptor()
	// computeallocation.DefaultCreatedAt holds the default value on creation for the created_at field.
	computeallocation.DefaultCreatedAt = computeallocationDescCreatedAt.Default.(func() time.Time)
	// computeallocationDescUpdatedAt is the schema descriptor for updated_at field.
	computeallocationDescUpdatedAt := computeallocationFields[2].Descriptor()
	// computeallocation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	computeallocation.DefaultUpdatedAt = computeallocationDescUpdatedAt.Default.(func() time.Time)
	// computeallocation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	computeallocation.UpdateDefaultUpdatedAt = computeallocationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// computeallocationDescAccountID is the schema descriptor for account_id field.
	computeallocationDescAccountID := computeallocationFields[3].Descriptor()
	// computeallocation.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	computeallocation.AccountIDValidator = computeallocationDescAccountID.Validators[0].(func(string) error)
	// computeallocationDescOwnerUserID is the schema descriptor for owner_user_id field.
	computeallocationDescOwnerUserID := computeallocationFields[4].Descriptor()
	// computeallocation.DefaultOwnerUserID holds the default value on creation for the owner_user_id field.
	computeallocation.DefaultOwnerUserID = computeallocationDescOwnerUserID.Default.(string)
	// computeallocationDescWorkspaceID is the schema descriptor for workspace_id field.
	computeallocationDescWorkspaceID := computeallocationFields[5].Descriptor()
	// computeallocation.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	computeallocation.DefaultWorkspaceID = computeallocationDescWorkspaceID.Default.(string)
	// computeallocationDescName is the schema descriptor for name field.
	computeallocationDescName := computeallocationFields[6].Descriptor()
	// computeallocation.DefaultName holds the default value on creation for the name field.
	computeallocation.DefaultName = computeallocationDescName.Default.(string)
	// computeallocationDescPackageID is the schema descriptor for package_id field.
	computeallocationDescPackageID := computeallocationFields[7].Descriptor()
	// computeallocation.DefaultPackageID holds the default value on creation for the package_id field.
	computeallocation.DefaultPackageID = computeallocationDescPackageID.Default.(string)
	// computeallocationDescProvider is the schema descriptor for provider field.
	computeallocationDescProvider := computeallocationFields[8].Descriptor()
	// computeallocation.DefaultProvider holds the default value on creation for the provider field.
	computeallocation.DefaultProvider = computeallocationDescProvider.Default.(string)
	// computeallocationDescProviderResourceID is the schema descriptor for provider_resource_id field.
	computeallocationDescProviderResourceID := computeallocationFields[9].Descriptor()
	// computeallocation.DefaultProviderResourceID holds the default value on creation for the provider_resource_id field.
	computeallocation.DefaultProviderResourceID = computeallocationDescProviderResourceID.Default.(string)
	// computeallocationDescProviderRequestID is the schema descriptor for provider_request_id field.
	computeallocationDescProviderRequestID := computeallocationFields[10].Descriptor()
	// computeallocation.DefaultProviderRequestID holds the default value on creation for the provider_request_id field.
	computeallocation.DefaultProviderRequestID = computeallocationDescProviderRequestID.Default.(string)
	// computeallocationDescOperationID is the schema descriptor for operation_id field.
	computeallocationDescOperationID := computeallocationFields[11].Descriptor()
	// computeallocation.DefaultOperationID holds the default value on creation for the operation_id field.
	computeallocation.DefaultOperationID = computeallocationDescOperationID.Default.(string)
	// computeallocationDescStatus is the schema descriptor for status field.
	computeallocationDescStatus := computeallocationFields[12].Descriptor()
	// computeallocation.DefaultStatus holds the default value on creation for the status field.
	computeallocation.DefaultStatus = computeallocationDescStatus.Default.(string)
	// computeallocationDescDesiredStatus is the schema descriptor for desired_status field.
	computeallocationDescDesiredStatus := computeallocationFields[13].Descriptor()
	// computeallocation.DefaultDesiredStatus holds the default value on creation for the desired_status field.
	computeallocation.DefaultDesiredStatus = computeallocationDescDesiredStatus.Default.(string)
	// computeallocationDescProviderStatus is the schema descriptor for provider_status field.
	computeallocationDescProviderStatus := computeallocationFields[14].Descriptor()
	// computeallocation.DefaultProviderStatus holds the default value on creation for the provider_status field.
	computeallocation.DefaultProviderStatus = computeallocationDescProviderStatus.Default.(string)
	// computeallocationDescLastProviderSyncAt is the schema descriptor for last_provider_sync_at field.
	computeallocationDescLastProviderSyncAt := computeallocationFields[15].Descriptor()
	// computeallocation.DefaultLastProviderSyncAt holds the default value on creation for the last_provider_sync_at field.
	computeallocation.DefaultLastProviderSyncAt = computeallocationDescLastProviderSyncAt.Default.(string)
	// computeallocationDescLastProviderSyncError is the schema descriptor for last_provider_sync_error field.
	computeallocationDescLastProviderSyncError := computeallocationFields[16].Descriptor()
	// computeallocation.DefaultLastProviderSyncError holds the default value on creation for the last_provider_sync_error field.
	computeallocation.DefaultLastProviderSyncError = computeallocationDescLastProviderSyncError.Default.(string)
	// computeallocationDescExternalDeletedAt is the schema descriptor for external_deleted_at field.
	computeallocationDescExternalDeletedAt := computeallocationFields[17].Descriptor()
	// computeallocation.DefaultExternalDeletedAt holds the default value on creation for the external_deleted_at field.
	computeallocation.DefaultExternalDeletedAt = computeallocationDescExternalDeletedAt.Default.(string)
	// computeallocationDescBillingStatus is the schema descriptor for billing_status field.
	computeallocationDescBillingStatus := computeallocationFields[18].Descriptor()
	// computeallocation.DefaultBillingStatus holds the default value on creation for the billing_status field.
	computeallocation.DefaultBillingStatus = computeallocationDescBillingStatus.Default.(string)
	// computeallocationDescPricingVersion is the schema descriptor for pricing_version field.
	computeallocationDescPricingVersion := computeallocationFields[19].Descriptor()
	// computeallocation.DefaultPricingVersion holds the default value on creation for the pricing_version field.
	computeallocation.DefaultPricingVersion = computeallocationDescPricingVersion.Default.(string)
	// computeallocationDescBillingOperationID is the schema descriptor for billing_operation_id field.
	computeallocationDescBillingOperationID := computeallocationFields[20].Descriptor()
	// computeallocation.DefaultBillingOperationID holds the default value on creation for the billing_operation_id field.
	computeallocation.DefaultBillingOperationID = computeallocationDescBillingOperationID.Default.(string)
	// computeallocationDescBillingStateJSON is the schema descriptor for billing_state_json field.
	computeallocationDescBillingStateJSON := computeallocationFields[21].Descriptor()
	// computeallocation.DefaultBillingStateJSON holds the default value on creation for the billing_state_json field.
	computeallocation.DefaultBillingStateJSON = computeallocationDescBillingStateJSON.Default.(string)
	// computeallocationDescEvidenceID is the schema descriptor for evidence_id field.
	computeallocationDescEvidenceID := computeallocationFields[22].Descriptor()
	// computeallocation.DefaultEvidenceID holds the default value on creation for the evidence_id field.
	computeallocation.DefaultEvidenceID = computeallocationDescEvidenceID.Default.(string)
	// computeallocationDescCvmInstanceID is the schema descriptor for cvm_instance_id field.
	computeallocationDescCvmInstanceID := computeallocationFields[23].Descriptor()
	// computeallocation.DefaultCvmInstanceID holds the default value on creation for the cvm_instance_id field.
	computeallocation.DefaultCvmInstanceID = computeallocationDescCvmInstanceID.Default.(string)
	// computeallocationDescInstanceID is the schema descriptor for instance_id field.
	computeallocationDescInstanceID := computeallocationFields[24].Descriptor()
	// computeallocation.DefaultInstanceID holds the default value on creation for the instance_id field.
	computeallocation.DefaultInstanceID = computeallocationDescInstanceID.Default.(string)
	// computeallocationDescNodeName is the schema descriptor for node_name field.
	computeallocationDescNodeName := computeallocationFields[25].Descriptor()
	// computeallocation.DefaultNodeName holds the default value on creation for the node_name field.
	computeallocation.DefaultNodeName = computeallocationDescNodeName.Default.(string)
	// computeallocationDescMachineName is the schema descriptor for machine_name field.
	computeallocationDescMachineName := computeallocationFields[26].Descriptor()
	// computeallocation.DefaultMachineName holds the default value on creation for the machine_name field.
	computeallocation.DefaultMachineName = computeallocationDescMachineName.Default.(string)
	// computeallocationDescCPU is the schema descriptor for cpu field.
	computeallocationDescCPU := computeallocationFields[27].Descriptor()
	// computeallocation.DefaultCPU holds the default value on creation for the cpu field.
	computeallocation.DefaultCPU = computeallocationDescCPU.Default.(float64)
	// computeallocationDescMemoryGB is the schema descriptor for memory_gb field.
	computeallocationDescMemoryGB := computeallocationFields[28].Descriptor()
	// computeallocation.DefaultMemoryGB holds the default value on creation for the memory_gb field.
	computeallocation.DefaultMemoryGB = computeallocationDescMemoryGB.Default.(float64)
	// computeallocationDescDiskGB is the schema descriptor for disk_gb field.
	computeallocationDescDiskGB := computeallocationFields[29].Descriptor()
	// computeallocation.DefaultDiskGB holds the default value on creation for the disk_gb field.
	computeallocation.DefaultDiskGB = computeallocationDescDiskGB.Default.(float64)
	// computeallocationDescID is the schema descriptor for id field.
	computeallocationDescID := computeallocationFields[0].Descriptor()
	// computeallocation.IDValidator is a validator for the "id" field. It is called by the builders before save.
	computeallocation.IDValidator = computeallocationDescID.Validators[0].(func(string) error)
	productione2erecordFields := schema.ProductionE2ERecord{}.Fields()
	_ = productione2erecordFields
	// productione2erecordDescCreatedAt is the schema descriptor for created_at field.
	productione2erecordDescCreatedAt := productione2erecordFields[1].Descriptor()
	// productione2erecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	productione2erecord.DefaultCreatedAt = productione2erecordDescCreatedAt.Default.(func() time.Time)
	// productione2erecordDescUpdatedAt is the schema descriptor for updated_at field.
	productione2erecordDescUpdatedAt := productione2erecordFields[2].Descriptor()
	// productione2erecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	productione2erecord.DefaultUpdatedAt = productione2erecordDescUpdatedAt.Default.(func() time.Time)
	// productione2erecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productione2erecord.UpdateDefaultUpdatedAt = productione2erecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productione2erecordDescAccountID is the schema descriptor for account_id field.
	productione2erecordDescAccountID := productione2erecordFields[3].Descriptor()
	// productione2erecord.DefaultAccountID holds the default value on creation for the account_id field.
	productione2erecord.DefaultAccountID = productione2erecordDescAccountID.Default.(string)
	// productione2erecordDescWorkspaceID is the schema descriptor for workspace_id field.
	productione2erecordDescWorkspaceID := productione2erecordFields[4].Descriptor()
	// productione2erecord.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	productione2erecord.DefaultWorkspaceID = productione2erecordDescWorkspaceID.Default.(string)
	// productione2erecordDescStatus is the schema descriptor for status field.
	productione2erecordDescStatus := productione2erecordFields[5].Descriptor()
	// productione2erecord.DefaultStatus holds the default value on creation for the status field.
	productione2erecord.DefaultStatus = productione2erecordDescStatus.Default.(string)
	// productione2erecordDescResult is the schema descriptor for result field.
	productione2erecordDescResult := productione2erecordFields[6].Descriptor()
	// productione2erecord.DefaultResult holds the default value on creation for the result field.
	productione2erecord.DefaultResult = productione2erecordDescResult.Default.(string)
	// productione2erecordDescReason is the schema descriptor for reason field.
	productione2erecordDescReason := productione2erecordFields[7].Descriptor()
	// productione2erecord.DefaultReason holds the default value on creation for the reason field.
	productione2erecord.DefaultReason = productione2erecordDescReason.Default.(string)
	// productione2erecordDescURL is the schema descriptor for url field.
	productione2erecordDescURL := productione2erecordFields[8].Descriptor()
	// productione2erecord.DefaultURL holds the default value on creation for the url field.
	productione2erecord.DefaultURL = productione2erecordDescURL.Default.(string)
	// productione2erecordDescID is the schema descriptor for id field.
	productione2erecordDescID := productione2erecordFields[0].Descriptor()
	// productione2erecord.IDValidator is a validator for the "id" field. It is called by the builders before save.
	productione2erecord.IDValidator = productione2erecordDescID.Validators[0].(func(string) error)
	projecttasksyncheadFields := schema.ProjectTaskSyncHead{}.Fields()
	_ = projecttasksyncheadFields
	// projecttasksyncheadDescCreatedAt is the schema descriptor for created_at field.
	projecttasksyncheadDescCreatedAt := projecttasksyncheadFields[1].Descriptor()
	// projecttasksynchead.DefaultCreatedAt holds the default value on creation for the created_at field.
	projecttasksynchead.DefaultCreatedAt = projecttasksyncheadDescCreatedAt.Default.(func() time.Time)
	// projecttasksyncheadDescUpdatedAt is the schema descriptor for updated_at field.
	projecttasksyncheadDescUpdatedAt := projecttasksyncheadFields[2].Descriptor()
	// projecttasksynchead.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	projecttasksynchead.DefaultUpdatedAt = projecttasksyncheadDescUpdatedAt.Default.(func() time.Time)
	// projecttasksynchead.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	projecttasksynchead.UpdateDefaultUpdatedAt = projecttasksyncheadDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projecttasksyncheadDescKind is the schema descriptor for kind field.
	projecttasksyncheadDescKind := projecttasksyncheadFields[3].Descriptor()
	// projecttasksynchead.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	projecttasksynchead.KindValidator = projecttasksyncheadDescKind.Validators[0].(func(string) error)
	// projecttasksyncheadDescOrganizationID is the schema descriptor for organization_id field.
	projecttasksyncheadDescOrganizationID := projecttasksyncheadFields[4].Descriptor()
	// projecttasksynchead.OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	projecttasksynchead.OrganizationIDValidator = projecttasksyncheadDescOrganizationID.Validators[0].(func(string) error)
	// projecttasksyncheadDescWorkspaceID is the schema descriptor for workspace_id field.
	projecttasksyncheadDescWorkspaceID := projecttasksyncheadFields[5].Descriptor()
	// projecttasksynchead.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	projecttasksynchead.WorkspaceIDValidator = projecttasksyncheadDescWorkspaceID.Validators[0].(func(string) error)
	// projecttasksyncheadDescProjectID is the schema descriptor for project_id field.
	projecttasksyncheadDescProjectID := projecttasksyncheadFields[6].Descriptor()
	// projecttasksynchead.DefaultProjectID holds the default value on creation for the project_id field.
	projecttasksynchead.DefaultProjectID = projecttasksyncheadDescProjectID.Default.(string)
	// projecttasksyncheadDescLocalAliasID is the schema descriptor for local_alias_id field.
	projecttasksyncheadDescLocalAliasID := projecttasksyncheadFields[7].Descriptor()
	// projecttasksynchead.DefaultLocalAliasID holds the default value on creation for the local_alias_id field.
	projecttasksynchead.DefaultLocalAliasID = projecttasksyncheadDescLocalAliasID.Default.(string)
	// projecttasksyncheadDescVersion is the schema descriptor for version field.
	projecttasksyncheadDescVersion := projecttasksyncheadFields[8].Descriptor()
	// projecttasksynchead.DefaultVersion holds the default value on creation for the version field.
	projecttasksynchead.DefaultVersion = projecttasksyncheadDescVersion.Default.(int64)
	// projecttasksyncheadDescStatus is the schema descriptor for status field.
	projecttasksyncheadDescStatus := projecttasksyncheadFields[9].Descriptor()
	// projecttasksynchead.DefaultStatus holds the default value on creation for the status field.
	projecttasksynchead.DefaultStatus = projecttasksyncheadDescStatus.Default.(string)
	// projecttasksyncheadDescID is the schema descriptor for id field.
	projecttasksyncheadDescID := projecttasksyncheadFields[0].Descriptor()
	// projecttasksynchead.IDValidator is a validator for the "id" field. It is called by the builders before save.
	projecttasksynchead.IDValidator = projecttasksyncheadDescID.Validators[0].(func(string) error)
	runtimeoperationFields := schema.RuntimeOperation{}.Fields()
	_ = runtimeoperationFields
	// runtimeoperationDescCreatedAt is the schema descriptor for created_at field.
	runtimeoperationDescCreatedAt := runtimeoperationFields[1].Descriptor()
	// runtimeoperation.DefaultCreatedAt holds the default value on creation for the created_at field.
	runtimeoperation.DefaultCreatedAt = runtimeoperationDescCreatedAt.Default.(func() time.Time)
	// runtimeoperationDescUpdatedAt is the schema descriptor for updated_at field.
	runtimeoperationDescUpdatedAt := runtimeoperationFields[2].Descriptor()
	// runtimeoperation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	runtimeoperation.DefaultUpdatedAt = runtimeoperationDescUpdatedAt.Default.(func() time.Time)
	// runtimeoperation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	runtimeoperation.UpdateDefaultUpdatedAt = runtimeoperationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// runtimeoperationDescOperationID is the schema descriptor for operation_id field.
	runtimeoperationDescOperationID := runtimeoperationFields[3].Descriptor()
	// runtimeoperation.DefaultOperationID holds the default value on creation for the operation_id field.
	runtimeoperation.DefaultOperationID = runtimeoperationDescOperationID.Default.(string)
	// runtimeoperationDescAccountID is the schema descriptor for account_id field.
	runtimeoperationDescAccountID := runtimeoperationFields[4].Descriptor()
	// runtimeoperation.DefaultAccountID holds the default value on creation for the account_id field.
	runtimeoperation.DefaultAccountID = runtimeoperationDescAccountID.Default.(string)
	// runtimeoperationDescWorkspaceID is the schema descriptor for workspace_id field.
	runtimeoperationDescWorkspaceID := runtimeoperationFields[5].Descriptor()
	// runtimeoperation.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	runtimeoperation.DefaultWorkspaceID = runtimeoperationDescWorkspaceID.Default.(string)
	// runtimeoperationDescPeriodStart is the schema descriptor for period_start field.
	runtimeoperationDescPeriodStart := runtimeoperationFields[6].Descriptor()
	// runtimeoperation.DefaultPeriodStart holds the default value on creation for the period_start field.
	runtimeoperation.DefaultPeriodStart = runtimeoperationDescPeriodStart.Default.(string)
	// runtimeoperationDescResourceID is the schema descriptor for resource_id field.
	runtimeoperationDescResourceID := runtimeoperationFields[7].Descriptor()
	// runtimeoperation.DefaultResourceID holds the default value on creation for the resource_id field.
	runtimeoperation.DefaultResourceID = runtimeoperationDescResourceID.Default.(string)
	// runtimeoperationDescResourceKind is the schema descriptor for resource_kind field.
	runtimeoperationDescResourceKind := runtimeoperationFields[8].Descriptor()
	// runtimeoperation.DefaultResourceKind holds the default value on creation for the resource_kind field.
	runtimeoperation.DefaultResourceKind = runtimeoperationDescResourceKind.Default.(string)
	// runtimeoperationDescAction is the schema descriptor for action field.
	runtimeoperationDescAction := runtimeoperationFields[9].Descriptor()
	// runtimeoperation.DefaultAction holds the default value on creation for the action field.
	runtimeoperation.DefaultAction = runtimeoperationDescAction.Default.(string)
	// runtimeoperationDescProvider is the schema descriptor for provider field.
	runtimeoperationDescProvider := runtimeoperationFields[10].Descriptor()
	// runtimeoperation.DefaultProvider holds the default value on creation for the provider field.
	runtimeoperation.DefaultProvider = runtimeoperationDescProvider.Default.(string)
	// runtimeoperationDescProviderRequestID is the schema descriptor for provider_request_id field.
	runtimeoperationDescProviderRequestID := runtimeoperationFields[11].Descriptor()
	// runtimeoperation.DefaultProviderRequestID holds the default value on creation for the provider_request_id field.
	runtimeoperation.DefaultProviderRequestID = runtimeoperationDescProviderRequestID.Default.(string)
	// runtimeoperationDescStatus is the schema descriptor for status field.
	runtimeoperationDescStatus := runtimeoperationFields[12].Descriptor()
	// runtimeoperation.DefaultStatus holds the default value on creation for the status field.
	runtimeoperation.DefaultStatus = runtimeoperationDescStatus.Default.(string)
	// runtimeoperationDescResult is the schema descriptor for result field.
	runtimeoperationDescResult := runtimeoperationFields[13].Descriptor()
	// runtimeoperation.DefaultResult holds the default value on creation for the result field.
	runtimeoperation.DefaultResult = runtimeoperationDescResult.Default.(string)
	// runtimeoperationDescComputeAllocationID is the schema descriptor for compute_allocation_id field.
	runtimeoperationDescComputeAllocationID := runtimeoperationFields[14].Descriptor()
	// runtimeoperation.DefaultComputeAllocationID holds the default value on creation for the compute_allocation_id field.
	runtimeoperation.DefaultComputeAllocationID = runtimeoperationDescComputeAllocationID.Default.(string)
	// runtimeoperationDescStorageID is the schema descriptor for storage_id field.
	runtimeoperationDescStorageID := runtimeoperationFields[15].Descriptor()
	// runtimeoperation.DefaultStorageID holds the default value on creation for the storage_id field.
	runtimeoperation.DefaultStorageID = runtimeoperationDescStorageID.Default.(string)
	// runtimeoperationDescAttachmentID is the schema descriptor for attachment_id field.
	runtimeoperationDescAttachmentID := runtimeoperationFields[16].Descriptor()
	// runtimeoperation.DefaultAttachmentID holds the default value on creation for the attachment_id field.
	runtimeoperation.DefaultAttachmentID = runtimeoperationDescAttachmentID.Default.(string)
	// runtimeoperationDescRuntimeServiceName is the schema descriptor for runtime_service_name field.
	runtimeoperationDescRuntimeServiceName := runtimeoperationFields[17].Descriptor()
	// runtimeoperation.DefaultRuntimeServiceName holds the default value on creation for the runtime_service_name field.
	runtimeoperation.DefaultRuntimeServiceName = runtimeoperationDescRuntimeServiceName.Default.(string)
	// runtimeoperationDescCvmInstanceID is the schema descriptor for cvm_instance_id field.
	runtimeoperationDescCvmInstanceID := runtimeoperationFields[18].Descriptor()
	// runtimeoperation.DefaultCvmInstanceID holds the default value on creation for the cvm_instance_id field.
	runtimeoperation.DefaultCvmInstanceID = runtimeoperationDescCvmInstanceID.Default.(string)
	// runtimeoperationDescInstanceID is the schema descriptor for instance_id field.
	runtimeoperationDescInstanceID := runtimeoperationFields[19].Descriptor()
	// runtimeoperation.DefaultInstanceID holds the default value on creation for the instance_id field.
	runtimeoperation.DefaultInstanceID = runtimeoperationDescInstanceID.Default.(string)
	// runtimeoperationDescNodeName is the schema descriptor for node_name field.
	runtimeoperationDescNodeName := runtimeoperationFields[20].Descriptor()
	// runtimeoperation.DefaultNodeName holds the default value on creation for the node_name field.
	runtimeoperation.DefaultNodeName = runtimeoperationDescNodeName.Default.(string)
	// runtimeoperationDescMachineName is the schema descriptor for machine_name field.
	runtimeoperationDescMachineName := runtimeoperationFields[21].Descriptor()
	// runtimeoperation.DefaultMachineName holds the default value on creation for the machine_name field.
	runtimeoperation.DefaultMachineName = runtimeoperationDescMachineName.Default.(string)
	// runtimeoperationDescID is the schema descriptor for id field.
	runtimeoperationDescID := runtimeoperationFields[0].Descriptor()
	// runtimeoperation.IDValidator is a validator for the "id" field. It is called by the builders before save.
	runtimeoperation.IDValidator = runtimeoperationDescID.Validators[0].(func(string) error)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[1].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[2].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[3].Descriptor()
	// session.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	session.UserIDValidator = sessionDescUserID.Validators[0].(func(string) error)
	// sessionDescCsrf is the schema descriptor for csrf field.
	sessionDescCsrf := sessionFields[4].Descriptor()
	// session.CsrfValidator is a validator for the "csrf" field. It is called by the builders before save.
	session.CsrfValidator = sessionDescCsrf.Validators[0].(func(string) error)
	// sessionDescExpiresAt is the schema descriptor for expires_at field.
	sessionDescExpiresAt := sessionFields[5].Descriptor()
	// session.ExpiresAtValidator is a validator for the "expires_at" field. It is called by the builders before save.
	session.ExpiresAtValidator = sessionDescExpiresAt.Validators[0].(func(string) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.IDValidator is a validator for the "id" field. It is called by the builders before save.
	session.IDValidator = sessionDescID.Validators[0].(func(string) error)
	storageattachmentFields := schema.StorageAttachment{}.Fields()
	_ = storageattachmentFields
	// storageattachmentDescCreatedAt is the schema descriptor for created_at field.
	storageattachmentDescCreatedAt := storageattachmentFields[1].Descriptor()
	// storageattachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	storageattachment.DefaultCreatedAt = storageattachmentDescCreatedAt.Default.(func() time.Time)
	// storageattachmentDescUpdatedAt is the schema descriptor for updated_at field.
	storageattachmentDescUpdatedAt := storageattachmentFields[2].Descriptor()
	// storageattachment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storageattachment.DefaultUpdatedAt = storageattachmentDescUpdatedAt.Default.(func() time.Time)
	// storageattachment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storageattachment.UpdateDefaultUpdatedAt = storageattachmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storageattachmentDescAccountID is the schema descriptor for account_id field.
	storageattachmentDescAccountID := storageattachmentFields[3].Descriptor()
	// storageattachment.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	storageattachment.AccountIDValidator = storageattachmentDescAccountID.Validators[0].(func(string) error)
	// storageattachmentDescWorkspaceID is the schema descriptor for workspace_id field.
	storageattachmentDescWorkspaceID := storageattachmentFields[4].Descriptor()
	// storageattachment.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	storageattachment.DefaultWorkspaceID = storageattachmentDescWorkspaceID.Default.(string)
	// storageattachmentDescComputeAllocationID is the schema descriptor for compute_allocation_id field.
	storageattachmentDescComputeAllocationID := storageattachmentFields[5].Descriptor()
	// storageattachment.DefaultComputeAllocationID holds the default value on creation for the compute_allocation_id field.
	storageattachment.DefaultComputeAllocationID = storageattachmentDescComputeAllocationID.Default.(string)
	// storageattachmentDescStorageID is the schema descriptor for storage_id field.
	storageattachmentDescStorageID := storageattachmentFields[6].Descriptor()
	// storageattachment.DefaultStorageID holds the default value on creation for the storage_id field.
	storageattachment.DefaultStorageID = storageattachmentDescStorageID.Default.(string)
	// storageattachmentDescVolumeID is the schema descriptor for volume_id field.
	storageattachmentDescVolumeID := storageattachmentFields[7].Descriptor()
	// storageattachment.DefaultVolumeID holds the default value on creation for the volume_id field.
	storageattachment.DefaultVolumeID = storageattachmentDescVolumeID.Default.(string)
	// storageattachmentDescOperationID is the schema descriptor for operation_id field.
	storageattachmentDescOperationID := storageattachmentFields[8].Descriptor()
	// storageattachment.DefaultOperationID holds the default value on creation for the operation_id field.
	storageattachment.DefaultOperationID = storageattachmentDescOperationID.Default.(string)
	// storageattachmentDescProvider is the schema descriptor for provider field.
	storageattachmentDescProvider := storageattachmentFields[9].Descriptor()
	// storageattachment.DefaultProvider holds the default value on creation for the provider field.
	storageattachment.DefaultProvider = storageattachmentDescProvider.Default.(string)
	// storageattachmentDescProviderRequestID is the schema descriptor for provider_request_id field.
	storageattachmentDescProviderRequestID := storageattachmentFields[10].Descriptor()
	// storageattachment.DefaultProviderRequestID holds the default value on creation for the provider_request_id field.
	storageattachment.DefaultProviderRequestID = storageattachmentDescProviderRequestID.Default.(string)
	// storageattachmentDescStatus is the schema descriptor for status field.
	storageattachmentDescStatus := storageattachmentFields[11].Descriptor()
	// storageattachment.DefaultStatus holds the default value on creation for the status field.
	storageattachment.DefaultStatus = storageattachmentDescStatus.Default.(string)
	// storageattachmentDescMountPath is the schema descriptor for mount_path field.
	storageattachmentDescMountPath := storageattachmentFields[12].Descriptor()
	// storageattachment.DefaultMountPath holds the default value on creation for the mount_path field.
	storageattachment.DefaultMountPath = storageattachmentDescMountPath.Default.(string)
	// storageattachmentDescID is the schema descriptor for id field.
	storageattachmentDescID := storageattachmentFields[0].Descriptor()
	// storageattachment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	storageattachment.IDValidator = storageattachmentDescID.Validators[0].(func(string) error)
	storagevolumeFields := schema.StorageVolume{}.Fields()
	_ = storagevolumeFields
	// storagevolumeDescCreatedAt is the schema descriptor for created_at field.
	storagevolumeDescCreatedAt := storagevolumeFields[1].Descriptor()
	// storagevolume.DefaultCreatedAt holds the default value on creation for the created_at field.
	storagevolume.DefaultCreatedAt = storagevolumeDescCreatedAt.Default.(func() time.Time)
	// storagevolumeDescUpdatedAt is the schema descriptor for updated_at field.
	storagevolumeDescUpdatedAt := storagevolumeFields[2].Descriptor()
	// storagevolume.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storagevolume.DefaultUpdatedAt = storagevolumeDescUpdatedAt.Default.(func() time.Time)
	// storagevolume.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storagevolume.UpdateDefaultUpdatedAt = storagevolumeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storagevolumeDescAccountID is the schema descriptor for account_id field.
	storagevolumeDescAccountID := storagevolumeFields[3].Descriptor()
	// storagevolume.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	storagevolume.AccountIDValidator = storagevolumeDescAccountID.Validators[0].(func(string) error)
	// storagevolumeDescOwnerUserID is the schema descriptor for owner_user_id field.
	storagevolumeDescOwnerUserID := storagevolumeFields[4].Descriptor()
	// storagevolume.DefaultOwnerUserID holds the default value on creation for the owner_user_id field.
	storagevolume.DefaultOwnerUserID = storagevolumeDescOwnerUserID.Default.(string)
	// storagevolumeDescWorkspaceID is the schema descriptor for workspace_id field.
	storagevolumeDescWorkspaceID := storagevolumeFields[5].Descriptor()
	// storagevolume.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	storagevolume.DefaultWorkspaceID = storagevolumeDescWorkspaceID.Default.(string)
	// storagevolumeDescName is the schema descriptor for name field.
	storagevolumeDescName := storagevolumeFields[6].Descriptor()
	// storagevolume.DefaultName holds the default value on creation for the name field.
	storagevolume.DefaultName = storagevolumeDescName.Default.(string)
	// storagevolumeDescPackageID is the schema descriptor for package_id field.
	storagevolumeDescPackageID := storagevolumeFields[7].Descriptor()
	// storagevolume.DefaultPackageID holds the default value on creation for the package_id field.
	storagevolume.DefaultPackageID = storagevolumeDescPackageID.Default.(string)
	// storagevolumeDescProvider is the schema descriptor for provider field.
	storagevolumeDescProvider := storagevolumeFields[8].Descriptor()
	// storagevolume.DefaultProvider holds the default value on creation for the provider field.
	storagevolume.DefaultProvider = storagevolumeDescProvider.Default.(string)
	// storagevolumeDescProviderResourceID is the schema descriptor for provider_resource_id field.
	storagevolumeDescProviderResourceID := storagevolumeFields[9].Descriptor()
	// storagevolume.DefaultProviderResourceID holds the default value on creation for the provider_resource_id field.
	storagevolume.DefaultProviderResourceID = storagevolumeDescProviderResourceID.Default.(string)
	// storagevolumeDescProviderRequestID is the schema descriptor for provider_request_id field.
	storagevolumeDescProviderRequestID := storagevolumeFields[10].Descriptor()
	// storagevolume.DefaultProviderRequestID holds the default value on creation for the provider_request_id field.
	storagevolume.DefaultProviderRequestID = storagevolumeDescProviderRequestID.Default.(string)
	// storagevolumeDescOperationID is the schema descriptor for operation_id field.
	storagevolumeDescOperationID := storagevolumeFields[11].Descriptor()
	// storagevolume.DefaultOperationID holds the default value on creation for the operation_id field.
	storagevolume.DefaultOperationID = storagevolumeDescOperationID.Default.(string)
	// storagevolumeDescStatus is the schema descriptor for status field.
	storagevolumeDescStatus := storagevolumeFields[12].Descriptor()
	// storagevolume.DefaultStatus holds the default value on creation for the status field.
	storagevolume.DefaultStatus = storagevolumeDescStatus.Default.(string)
	// storagevolumeDescDesiredStatus is the schema descriptor for desired_status field.
	storagevolumeDescDesiredStatus := storagevolumeFields[13].Descriptor()
	// storagevolume.DefaultDesiredStatus holds the default value on creation for the desired_status field.
	storagevolume.DefaultDesiredStatus = storagevolumeDescDesiredStatus.Default.(string)
	// storagevolumeDescProviderStatus is the schema descriptor for provider_status field.
	storagevolumeDescProviderStatus := storagevolumeFields[14].Descriptor()
	// storagevolume.DefaultProviderStatus holds the default value on creation for the provider_status field.
	storagevolume.DefaultProviderStatus = storagevolumeDescProviderStatus.Default.(string)
	// storagevolumeDescLastProviderSyncAt is the schema descriptor for last_provider_sync_at field.
	storagevolumeDescLastProviderSyncAt := storagevolumeFields[15].Descriptor()
	// storagevolume.DefaultLastProviderSyncAt holds the default value on creation for the last_provider_sync_at field.
	storagevolume.DefaultLastProviderSyncAt = storagevolumeDescLastProviderSyncAt.Default.(string)
	// storagevolumeDescLastProviderSyncError is the schema descriptor for last_provider_sync_error field.
	storagevolumeDescLastProviderSyncError := storagevolumeFields[16].Descriptor()
	// storagevolume.DefaultLastProviderSyncError holds the default value on creation for the last_provider_sync_error field.
	storagevolume.DefaultLastProviderSyncError = storagevolumeDescLastProviderSyncError.Default.(string)
	// storagevolumeDescExternalDeletedAt is the schema descriptor for external_deleted_at field.
	storagevolumeDescExternalDeletedAt := storagevolumeFields[17].Descriptor()
	// storagevolume.DefaultExternalDeletedAt holds the default value on creation for the external_deleted_at field.
	storagevolume.DefaultExternalDeletedAt = storagevolumeDescExternalDeletedAt.Default.(string)
	// storagevolumeDescBillingStatus is the schema descriptor for billing_status field.
	storagevolumeDescBillingStatus := storagevolumeFields[18].Descriptor()
	// storagevolume.DefaultBillingStatus holds the default value on creation for the billing_status field.
	storagevolume.DefaultBillingStatus = storagevolumeDescBillingStatus.Default.(string)
	// storagevolumeDescPricingVersion is the schema descriptor for pricing_version field.
	storagevolumeDescPricingVersion := storagevolumeFields[19].Descriptor()
	// storagevolume.DefaultPricingVersion holds the default value on creation for the pricing_version field.
	storagevolume.DefaultPricingVersion = storagevolumeDescPricingVersion.Default.(string)
	// storagevolumeDescBillingOperationID is the schema descriptor for billing_operation_id field.
	storagevolumeDescBillingOperationID := storagevolumeFields[20].Descriptor()
	// storagevolume.DefaultBillingOperationID holds the default value on creation for the billing_operation_id field.
	storagevolume.DefaultBillingOperationID = storagevolumeDescBillingOperationID.Default.(string)
	// storagevolumeDescBillingStateJSON is the schema descriptor for billing_state_json field.
	storagevolumeDescBillingStateJSON := storagevolumeFields[21].Descriptor()
	// storagevolume.DefaultBillingStateJSON holds the default value on creation for the billing_state_json field.
	storagevolume.DefaultBillingStateJSON = storagevolumeDescBillingStateJSON.Default.(string)
	// storagevolumeDescMountPath is the schema descriptor for mount_path field.
	storagevolumeDescMountPath := storagevolumeFields[22].Descriptor()
	// storagevolume.DefaultMountPath holds the default value on creation for the mount_path field.
	storagevolume.DefaultMountPath = storagevolumeDescMountPath.Default.(string)
	// storagevolumeDescSizeGB is the schema descriptor for size_gb field.
	storagevolumeDescSizeGB := storagevolumeFields[23].Descriptor()
	// storagevolume.DefaultSizeGB holds the default value on creation for the size_gb field.
	storagevolume.DefaultSizeGB = storagevolumeDescSizeGB.Default.(float64)
	// storagevolumeDescID is the schema descriptor for id field.
	storagevolumeDescID := storagevolumeFields[0].Descriptor()
	// storagevolume.IDValidator is a validator for the "id" field. It is called by the builders before save.
	storagevolume.IDValidator = storagevolumeDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescAccountID is the schema descriptor for account_id field.
	userDescAccountID := userFields[3].Descriptor()
	// user.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	user.AccountIDValidator = userDescAccountID.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[5].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[6].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[7].Descriptor()
	// user.DefaultPasswordHash holds the default value on creation for the password_hash field.
	user.DefaultPasswordHash = userDescPasswordHash.Default.(string)
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescDisabledAt is the schema descriptor for disabled_at field.
	userDescDisabledAt := userFields[8].Descriptor()
	// user.DefaultDisabledAt holds the default value on creation for the disabled_at field.
	user.DefaultDisabledAt = userDescDisabledAt.Default.(string)
	// userDescDisabledBy is the schema descriptor for disabled_by field.
	userDescDisabledBy := userFields[9].Descriptor()
	// user.DefaultDisabledBy holds the default value on creation for the disabled_by field.
	user.DefaultDisabledBy = userDescDisabledBy.Default.(string)
	// userDescDisabledReason is the schema descriptor for disabled_reason field.
	userDescDisabledReason := userFields[10].Descriptor()
	// user.DefaultDisabledReason holds the default value on creation for the disabled_reason field.
	user.DefaultDisabledReason = userDescDisabledReason.Default.(string)
	// userDescDeletedAt is the schema descriptor for deleted_at field.
	userDescDeletedAt := userFields[11].Descriptor()
	// user.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	user.DefaultDeletedAt = userDescDeletedAt.Default.(string)
	// userDescDeletedBy is the schema descriptor for deleted_by field.
	userDescDeletedBy := userFields[12].Descriptor()
	// user.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	user.DefaultDeletedBy = userDescDeletedBy.Default.(string)
	// userDescDeleteReason is the schema descriptor for delete_reason field.
	userDescDeleteReason := userFields[13].Descriptor()
	// user.DefaultDeleteReason holds the default value on creation for the delete_reason field.
	user.DefaultDeleteReason = userDescDeleteReason.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescCreatedAt is the schema descriptor for created_at field.
	workspaceDescCreatedAt := workspaceFields[1].Descriptor()
	// workspace.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspace.DefaultCreatedAt = workspaceDescCreatedAt.Default.(func() time.Time)
	// workspaceDescUpdatedAt is the schema descriptor for updated_at field.
	workspaceDescUpdatedAt := workspaceFields[2].Descriptor()
	// workspace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspace.DefaultUpdatedAt = workspaceDescUpdatedAt.Default.(func() time.Time)
	// workspace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspace.UpdateDefaultUpdatedAt = workspaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspaceDescAccountID is the schema descriptor for account_id field.
	workspaceDescAccountID := workspaceFields[3].Descriptor()
	// workspace.DefaultAccountID holds the default value on creation for the account_id field.
	workspace.DefaultAccountID = workspaceDescAccountID.Default.(string)
	// workspaceDescOwnerAccountID is the schema descriptor for owner_account_id field.
	workspaceDescOwnerAccountID := workspaceFields[4].Descriptor()
	// workspace.DefaultOwnerAccountID holds the default value on creation for the owner_account_id field.
	workspace.DefaultOwnerAccountID = workspaceDescOwnerAccountID.Default.(string)
	// workspaceDescOwnerUserID is the schema descriptor for owner_user_id field.
	workspaceDescOwnerUserID := workspaceFields[5].Descriptor()
	// workspace.DefaultOwnerUserID holds the default value on creation for the owner_user_id field.
	workspace.DefaultOwnerUserID = workspaceDescOwnerUserID.Default.(string)
	// workspaceDescUserID is the schema descriptor for user_id field.
	workspaceDescUserID := workspaceFields[6].Descriptor()
	// workspace.DefaultUserID holds the default value on creation for the user_id field.
	workspace.DefaultUserID = workspaceDescUserID.Default.(string)
	// workspaceDescName is the schema descriptor for name field.
	workspaceDescName := workspaceFields[7].Descriptor()
	// workspace.DefaultName holds the default value on creation for the name field.
	workspace.DefaultName = workspaceDescName.Default.(string)
	// workspaceDescURL is the schema descriptor for url field.
	workspaceDescURL := workspaceFields[8].Descriptor()
	// workspace.DefaultURL holds the default value on creation for the url field.
	workspace.DefaultURL = workspaceDescURL.Default.(string)
	// workspaceDescState is the schema descriptor for state field.
	workspaceDescState := workspaceFields[9].Descriptor()
	// workspace.DefaultState holds the default value on creation for the state field.
	workspace.DefaultState = workspaceDescState.Default.(string)
	// workspaceDescStatus is the schema descriptor for status field.
	workspaceDescStatus := workspaceFields[10].Descriptor()
	// workspace.DefaultStatus holds the default value on creation for the status field.
	workspace.DefaultStatus = workspaceDescStatus.Default.(string)
	// workspaceDescPurchaseReceiptID is the schema descriptor for purchase_receipt_id field.
	workspaceDescPurchaseReceiptID := workspaceFields[11].Descriptor()
	// workspace.DefaultPurchaseReceiptID holds the default value on creation for the purchase_receipt_id field.
	workspace.DefaultPurchaseReceiptID = workspaceDescPurchaseReceiptID.Default.(string)
	// workspaceDescBillingStateJSON is the schema descriptor for billing_state_json field.
	workspaceDescBillingStateJSON := workspaceFields[12].Descriptor()
	// workspace.DefaultBillingStateJSON holds the default value on creation for the billing_state_json field.
	workspace.DefaultBillingStateJSON = workspaceDescBillingStateJSON.Default.(string)
	// workspaceDescStorageID is the schema descriptor for storage_id field.
	workspaceDescStorageID := workspaceFields[13].Descriptor()
	// workspace.DefaultStorageID holds the default value on creation for the storage_id field.
	workspace.DefaultStorageID = workspaceDescStorageID.Default.(string)
	// workspaceDescCurrentComputeAllocationID is the schema descriptor for current_compute_allocation_id field.
	workspaceDescCurrentComputeAllocationID := workspaceFields[14].Descriptor()
	// workspace.DefaultCurrentComputeAllocationID holds the default value on creation for the current_compute_allocation_id field.
	workspace.DefaultCurrentComputeAllocationID = workspaceDescCurrentComputeAllocationID.Default.(string)
	// workspaceDescCurrentAttachmentID is the schema descriptor for current_attachment_id field.
	workspaceDescCurrentAttachmentID := workspaceFields[15].Descriptor()
	// workspace.DefaultCurrentAttachmentID holds the default value on creation for the current_attachment_id field.
	workspace.DefaultCurrentAttachmentID = workspaceDescCurrentAttachmentID.Default.(string)
	// workspaceDescRuntimeID is the schema descriptor for runtime_id field.
	workspaceDescRuntimeID := workspaceFields[16].Descriptor()
	// workspace.DefaultRuntimeID holds the default value on creation for the runtime_id field.
	workspace.DefaultRuntimeID = workspaceDescRuntimeID.Default.(string)
	// workspaceDescRuntimeServiceName is the schema descriptor for runtime_service_name field.
	workspaceDescRuntimeServiceName := workspaceFields[17].Descriptor()
	// workspace.DefaultRuntimeServiceName holds the default value on creation for the runtime_service_name field.
	workspace.DefaultRuntimeServiceName = workspaceDescRuntimeServiceName.Default.(string)
	// workspaceDescRuntimeServiceNameRoot is the schema descriptor for runtime_service_name_root field.
	workspaceDescRuntimeServiceNameRoot := workspaceFields[18].Descriptor()
	// workspace.DefaultRuntimeServiceNameRoot holds the default value on creation for the runtime_service_name_root field.
	workspace.DefaultRuntimeServiceNameRoot = workspaceDescRuntimeServiceNameRoot.Default.(string)
	// workspaceDescServiceName is the schema descriptor for service_name field.
	workspaceDescServiceName := workspaceFields[19].Descriptor()
	// workspace.DefaultServiceName holds the default value on creation for the service_name field.
	workspace.DefaultServiceName = workspaceDescServiceName.Default.(string)
	// workspaceDescWorkspaceAPIKeyID is the schema descriptor for workspace_api_key_id field.
	workspaceDescWorkspaceAPIKeyID := workspaceFields[20].Descriptor()
	// workspace.WorkspaceAPIKeyIDValidator is a validator for the "workspace_api_key_id" field. It is called by the builders before save.
	workspace.WorkspaceAPIKeyIDValidator = workspaceDescWorkspaceAPIKeyID.Validators[0].(func(int64) error)
	// workspaceDescAccessTokenStatus is the schema descriptor for access_token_status field.
	workspaceDescAccessTokenStatus := workspaceFields[21].Descriptor()
	// workspace.DefaultAccessTokenStatus holds the default value on creation for the access_token_status field.
	workspace.DefaultAccessTokenStatus = workspaceDescAccessTokenStatus.Default.(string)
	// workspaceDescAccessAccount is the schema descriptor for access_account field.
	workspaceDescAccessAccount := workspaceFields[22].Descriptor()
	// workspace.DefaultAccessAccount holds the default value on creation for the access_account field.
	workspace.DefaultAccessAccount = workspaceDescAccessAccount.Default.(string)
	// workspaceDescAccessUsername is the schema descriptor for access_username field.
	workspaceDescAccessUsername := workspaceFields[23].Descriptor()
	// workspace.DefaultAccessUsername holds the default value on creation for the access_username field.
	workspace.DefaultAccessUsername = workspaceDescAccessUsername.Default.(string)
	// workspaceDescCredentialStatus is the schema descriptor for credential_status field.
	workspaceDescCredentialStatus := workspaceFields[24].Descriptor()
	// workspace.DefaultCredentialStatus holds the default value on creation for the credential_status field.
	workspace.DefaultCredentialStatus = workspaceDescCredentialStatus.Default.(string)
	// workspaceDescCredentialVersion is the schema descriptor for credential_version field.
	workspaceDescCredentialVersion := workspaceFields[25].Descriptor()
	// workspace.DefaultCredentialVersion holds the default value on creation for the credential_version field.
	workspace.DefaultCredentialVersion = workspaceDescCredentialVersion.Default.(string)
	// workspaceDescCredentialSecretRef is the schema descriptor for credential_secret_ref field.
	workspaceDescCredentialSecretRef := workspaceFields[26].Descriptor()
	// workspace.DefaultCredentialSecretRef holds the default value on creation for the credential_secret_ref field.
	workspace.DefaultCredentialSecretRef = workspaceDescCredentialSecretRef.Default.(string)
	// workspaceDescAccessRequiresLogin is the schema descriptor for access_requires_login field.
	workspaceDescAccessRequiresLogin := workspaceFields[27].Descriptor()
	// workspace.DefaultAccessRequiresLogin holds the default value on creation for the access_requires_login field.
	workspace.DefaultAccessRequiresLogin = workspaceDescAccessRequiresLogin.Default.(bool)
	// workspaceDescVerificationSlotID is the schema descriptor for verification_slot_id field.
	workspaceDescVerificationSlotID := workspaceFields[28].Descriptor()
	// workspace.DefaultVerificationSlotID holds the default value on creation for the verification_slot_id field.
	workspace.DefaultVerificationSlotID = workspaceDescVerificationSlotID.Default.(string)
	// workspaceDescCustomerProduct is the schema descriptor for customer_product field.
	workspaceDescCustomerProduct := workspaceFields[29].Descriptor()
	// workspace.DefaultCustomerProduct holds the default value on creation for the customer_product field.
	workspace.DefaultCustomerProduct = workspaceDescCustomerProduct.Default.(bool)
	// workspaceDescID is the schema descriptor for id field.
	workspaceDescID := workspaceFields[0].Descriptor()
	// workspace.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workspace.IDValidator = workspaceDescID.Validators[0].(func(string) error)
	workspacesynceventFields := schema.WorkspaceSyncEvent{}.Fields()
	_ = workspacesynceventFields
	// workspacesynceventDescCreatedAt is the schema descriptor for created_at field.
	workspacesynceventDescCreatedAt := workspacesynceventFields[1].Descriptor()
	// workspacesyncevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspacesyncevent.DefaultCreatedAt = workspacesynceventDescCreatedAt.Default.(func() time.Time)
	// workspacesynceventDescUpdatedAt is the schema descriptor for updated_at field.
	workspacesynceventDescUpdatedAt := workspacesynceventFields[2].Descriptor()
	// workspacesyncevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspacesyncevent.DefaultUpdatedAt = workspacesynceventDescUpdatedAt.Default.(func() time.Time)
	// workspacesyncevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspacesyncevent.UpdateDefaultUpdatedAt = workspacesynceventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspacesynceventDescOperationID is the schema descriptor for operation_id field.
	workspacesynceventDescOperationID := workspacesynceventFields[3].Descriptor()
	// workspacesyncevent.OperationIDValidator is a validator for the "operation_id" field. It is called by the builders before save.
	workspacesyncevent.OperationIDValidator = workspacesynceventDescOperationID.Validators[0].(func(string) error)
	// workspacesynceventDescWorkspaceID is the schema descriptor for workspace_id field.
	workspacesynceventDescWorkspaceID := workspacesynceventFields[4].Descriptor()
	// workspacesyncevent.WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	workspacesyncevent.WorkspaceIDValidator = workspacesynceventDescWorkspaceID.Validators[0].(func(string) error)
	// workspacesynceventDescEntityKind is the schema descriptor for entity_kind field.
	workspacesynceventDescEntityKind := workspacesynceventFields[6].Descriptor()
	// workspacesyncevent.EntityKindValidator is a validator for the "entity_kind" field. It is called by the builders before save.
	workspacesyncevent.EntityKindValidator = workspacesynceventDescEntityKind.Validators[0].(func(string) error)
	// workspacesynceventDescProjectID is the schema descriptor for project_id field.
	workspacesynceventDescProjectID := workspacesynceventFields[7].Descriptor()
	// workspacesyncevent.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	workspacesyncevent.ProjectIDValidator = workspacesynceventDescProjectID.Validators[0].(func(string) error)
	// workspacesynceventDescTaskID is the schema descriptor for task_id field.
	workspacesynceventDescTaskID := workspacesynceventFields[8].Descriptor()
	// workspacesyncevent.DefaultTaskID holds the default value on creation for the task_id field.
	workspacesyncevent.DefaultTaskID = workspacesynceventDescTaskID.Default.(string)
	// workspacesynceventDescClientID is the schema descriptor for client_id field.
	workspacesynceventDescClientID := workspacesynceventFields[9].Descriptor()
	// workspacesyncevent.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	workspacesyncevent.ClientIDValidator = workspacesynceventDescClientID.Validators[0].(func(string) error)
	// workspacesynceventDescActorUserID is the schema descriptor for actor_user_id field.
	workspacesynceventDescActorUserID := workspacesynceventFields[10].Descriptor()
	// workspacesyncevent.ActorUserIDValidator is a validator for the "actor_user_id" field. It is called by the builders before save.
	workspacesyncevent.ActorUserIDValidator = workspacesynceventDescActorUserID.Validators[0].(func(string) error)
	// workspacesynceventDescOperation is the schema descriptor for operation field.
	workspacesynceventDescOperation := workspacesynceventFields[13].Descriptor()
	// workspacesyncevent.OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	workspacesyncevent.OperationValidator = workspacesynceventDescOperation.Validators[0].(func(string) error)
	// workspacesynceventDescStatus is the schema descriptor for status field.
	workspacesynceventDescStatus := workspacesynceventFields[14].Descriptor()
	// workspacesyncevent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	workspacesyncevent.StatusValidator = workspacesynceventDescStatus.Validators[0].(func(string) error)
	// workspacesynceventDescPayloadJSON is the schema descriptor for payload_json field.
	workspacesynceventDescPayloadJSON := workspacesynceventFields[15].Descriptor()
	// workspacesyncevent.DefaultPayloadJSON holds the default value on creation for the payload_json field.
	workspacesyncevent.DefaultPayloadJSON = workspacesynceventDescPayloadJSON.Default.(string)
	// workspacesynceventDescContentDigest is the schema descriptor for content_digest field.
	workspacesynceventDescContentDigest := workspacesynceventFields[16].Descriptor()
	// workspacesyncevent.DefaultContentDigest holds the default value on creation for the content_digest field.
	workspacesyncevent.DefaultContentDigest = workspacesynceventDescContentDigest.Default.(string)
	// workspacesynceventDescIdempotencyKey is the schema descriptor for idempotency_key field.
	workspacesynceventDescIdempotencyKey := workspacesynceventFields[17].Descriptor()
	// workspacesyncevent.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	workspacesyncevent.IdempotencyKeyValidator = workspacesynceventDescIdempotencyKey.Validators[0].(func(string) error)
	// workspacesynceventDescRequestHash is the schema descriptor for request_hash field.
	workspacesynceventDescRequestHash := workspacesynceventFields[18].Descriptor()
	// workspacesyncevent.RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	workspacesyncevent.RequestHashValidator = workspacesynceventDescRequestHash.Validators[0].(func(string) error)
	// workspacesynceventDescConflictID is the schema descriptor for conflict_id field.
	workspacesynceventDescConflictID := workspacesynceventFields[19].Descriptor()
	// workspacesyncevent.DefaultConflictID holds the default value on creation for the conflict_id field.
	workspacesyncevent.DefaultConflictID = workspacesynceventDescConflictID.Default.(string)
	// workspacesynceventDescID is the schema descriptor for id field.
	workspacesynceventDescID := workspacesynceventFields[0].Descriptor()
	// workspacesyncevent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workspacesyncevent.IDValidator = workspacesynceventDescID.Validators[0].(func(string) error)
}
