// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/workspace"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Workspace is the model entity for the Workspace schema.
type Workspace struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// OwnerAccountID holds the value of the "owner_account_id" field.
	OwnerAccountID string `json:"owner_account_id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID string `json:"owner_user_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PurchaseReceiptID holds the value of the "purchase_receipt_id" field.
	PurchaseReceiptID string `json:"purchase_receipt_id,omitempty"`
	// BillingStateJSON holds the value of the "billing_state_json" field.
	BillingStateJSON string `json:"billing_state_json,omitempty"`
	// StorageID holds the value of the "storage_id" field.
	StorageID string `json:"storage_id,omitempty"`
	// CurrentComputeAllocationID holds the value of the "current_compute_allocation_id" field.
	CurrentComputeAllocationID string `json:"current_compute_allocation_id,omitempty"`
	// CurrentAttachmentID holds the value of the "current_attachment_id" field.
	CurrentAttachmentID string `json:"current_attachment_id,omitempty"`
	// RuntimeID holds the value of the "runtime_id" field.
	RuntimeID string `json:"runtime_id,omitempty"`
	// RuntimeServiceName holds the value of the "runtime_service_name" field.
	RuntimeServiceName string `json:"runtime_service_name,omitempty"`
	// RuntimeServiceNameRoot holds the value of the "runtime_service_name_root" field.
	RuntimeServiceNameRoot string `json:"runtime_service_name_root,omitempty"`
	// ServiceName holds the value of the "service_name" field.
	ServiceName string `json:"service_name,omitempty"`
	// WorkspaceAPIKeyID holds the value of the "workspace_api_key_id" field.
	WorkspaceAPIKeyID int64 `json:"workspace_api_key_id,omitempty"`
	// AccessTokenStatus holds the value of the "access_token_status" field.
	AccessTokenStatus string `json:"access_token_status,omitempty"`
	// AccessAccount holds the value of the "access_account" field.
	AccessAccount string `json:"access_account,omitempty"`
	// AccessUsername holds the value of the "access_username" field.
	AccessUsername string `json:"access_username,omitempty"`
	// CredentialStatus holds the value of the "credential_status" field.
	CredentialStatus string `json:"credential_status,omitempty"`
	// CredentialVersion holds the value of the "credential_version" field.
	CredentialVersion string `json:"credential_version,omitempty"`
	// CredentialSecretRef holds the value of the "credential_secret_ref" field.
	CredentialSecretRef string `json:"credential_secret_ref,omitempty"`
	// AccessRequiresLogin holds the value of the "access_requires_login" field.
	AccessRequiresLogin bool `json:"access_requires_login,omitempty"`
	// VerificationSlotID holds the value of the "verification_slot_id" field.
	VerificationSlotID string `json:"verification_slot_id,omitempty"`
	// CustomerProduct holds the value of the "customer_product" field.
	CustomerProduct bool `json:"customer_product,omitempty"`
	// ApplicationBinding holds the value of the "application_binding" field.
	ApplicationBinding string `json:"application_binding,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Workspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspace.FieldAccessRequiresLogin, workspace.FieldCustomerProduct:
			values[i] = new(sql.NullBool)
		case workspace.FieldWorkspaceAPIKeyID:
			values[i] = new(sql.NullInt64)
		case workspace.FieldID, workspace.FieldAccountID, workspace.FieldOwnerAccountID, workspace.FieldOwnerUserID, workspace.FieldUserID, workspace.FieldName, workspace.FieldURL, workspace.FieldState, workspace.FieldStatus, workspace.FieldPurchaseReceiptID, workspace.FieldBillingStateJSON, workspace.FieldStorageID, workspace.FieldCurrentComputeAllocationID, workspace.FieldCurrentAttachmentID, workspace.FieldRuntimeID, workspace.FieldRuntimeServiceName, workspace.FieldRuntimeServiceNameRoot, workspace.FieldServiceName, workspace.FieldAccessTokenStatus, workspace.FieldAccessAccount, workspace.FieldAccessUsername, workspace.FieldCredentialStatus, workspace.FieldCredentialVersion, workspace.FieldCredentialSecretRef, workspace.FieldVerificationSlotID, workspace.FieldApplicationBinding:
			values[i] = new(sql.NullString)
		case workspace.FieldCreatedAt, workspace.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Workspace fields.
func (w *Workspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspace.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				w.ID = value.String
			}
		case workspace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				w.CreatedAt = value.Time
			}
		case workspace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				w.UpdatedAt = value.Time
			}
		case workspace.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				w.AccountID = value.String
			}
		case workspace.FieldOwnerAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_account_id", values[i])
			} else if value.Valid {
				w.OwnerAccountID = value.String
			}
		case workspace.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				w.OwnerUserID = value.String
			}
		case workspace.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				w.UserID = value.String
			}
		case workspace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				w.Name = value.String
			}
		case workspace.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				w.URL = value.String
			}
		case workspace.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				w.State = value.String
			}
		case workspace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				w.Status = value.String
			}
		case workspace.FieldPurchaseReceiptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_receipt_id", values[i])
			} else if value.Valid {
				w.PurchaseReceiptID = value.String
			}
		case workspace.FieldBillingStateJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_state_json", values[i])
			} else if value.Valid {
				w.BillingStateJSON = value.String
			}
		case workspace.FieldStorageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_id", values[i])
			} else if value.Valid {
				w.StorageID = value.String
			}
		case workspace.FieldCurrentComputeAllocationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_compute_allocation_id", values[i])
			} else if value.Valid {
				w.CurrentComputeAllocationID = value.String
			}
		case workspace.FieldCurrentAttachmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_attachment_id", values[i])
			} else if value.Valid {
				w.CurrentAttachmentID = value.String
			}
		case workspace.FieldRuntimeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runtime_id", values[i])
			} else if value.Valid {
				w.RuntimeID = value.String
			}
		case workspace.FieldRuntimeServiceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runtime_service_name", values[i])
			} else if value.Valid {
				w.RuntimeServiceName = value.String
			}
		case workspace.FieldRuntimeServiceNameRoot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runtime_service_name_root", values[i])
			} else if value.Valid {
				w.RuntimeServiceNameRoot = value.String
			}
		case workspace.FieldServiceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_name", values[i])
			} else if value.Valid {
				w.ServiceName = value.String
			}
		case workspace.FieldWorkspaceAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_api_key_id", values[i])
			} else if value.Valid {
				w.WorkspaceAPIKeyID = value.Int64
			}
		case workspace.FieldAccessTokenStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_status", values[i])
			} else if value.Valid {
				w.AccessTokenStatus = value.String
			}
		case workspace.FieldAccessAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_account", values[i])
			} else if value.Valid {
				w.AccessAccount = value.String
			}
		case workspace.FieldAccessUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_username", values[i])
			} else if value.Valid {
				w.AccessUsername = value.String
			}
		case workspace.FieldCredentialStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_status", values[i])
			} else if value.Valid {
				w.CredentialStatus = value.String
			}
		case workspace.FieldCredentialVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_version", values[i])
			} else if value.Valid {
				w.CredentialVersion = value.String
			}
		case workspace.FieldCredentialSecretRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_secret_ref", values[i])
			} else if value.Valid {
				w.CredentialSecretRef = value.String
			}
		case workspace.FieldAccessRequiresLogin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field access_requires_login", values[i])
			} else if value.Valid {
				w.AccessRequiresLogin = value.Bool
			}
		case workspace.FieldVerificationSlotID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verification_slot_id", values[i])
			} else if value.Valid {
				w.VerificationSlotID = value.String
			}
		case workspace.FieldCustomerProduct:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field customer_product", values[i])
			} else if value.Valid {
				w.CustomerProduct = value.Bool
			}
		case workspace.FieldApplicationBinding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_binding", values[i])
			} else if value.Valid {
				w.ApplicationBinding = value.String
			}
		default:
			w.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Workspace.
// This includes values selected through modifiers, order, etc.
func (w *Workspace) Value(name string) (ent.Value, error) {
	return w.selectValues.Get(name)
}

// Update returns a builder for updating this Workspace.
// Note that you need to call Workspace.Unwrap() before calling this method if this Workspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Workspace) Update() *WorkspaceUpdateOne {
	return NewWorkspaceClient(w.config).UpdateOne(w)
}

// Unwrap unwraps the Workspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Workspace) Unwrap() *Workspace {
	_tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Workspace is not a transactional entity")
	}
	w.config.driver = _tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Workspace) String() string {
	var builder strings.Builder
	builder.WriteString("Workspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", w.ID))
	builder.WriteString("created_at=")
	builder.WriteString(w.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(w.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(w.AccountID)
	builder.WriteString(", ")
	builder.WriteString("owner_account_id=")
	builder.WriteString(w.OwnerAccountID)
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(w.OwnerUserID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(w.UserID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(w.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(w.URL)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(w.State)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(w.Status)
	builder.WriteString(", ")
	builder.WriteString("purchase_receipt_id=")
	builder.WriteString(w.PurchaseReceiptID)
	builder.WriteString(", ")
	builder.WriteString("billing_state_json=")
	builder.WriteString(w.BillingStateJSON)
	builder.WriteString(", ")
	builder.WriteString("storage_id=")
	builder.WriteString(w.StorageID)
	builder.WriteString(", ")
	builder.WriteString("current_compute_allocation_id=")
	builder.WriteString(w.CurrentComputeAllocationID)
	builder.WriteString(", ")
	builder.WriteString("current_attachment_id=")
	builder.WriteString(w.CurrentAttachmentID)
	builder.WriteString(", ")
	builder.WriteString("runtime_id=")
	builder.WriteString(w.RuntimeID)
	builder.WriteString(", ")
	builder.WriteString("runtime_service_name=")
	builder.WriteString(w.RuntimeServiceName)
	builder.WriteString(", ")
	builder.WriteString("runtime_service_name_root=")
	builder.WriteString(w.RuntimeServiceNameRoot)
	builder.WriteString(", ")
	builder.WriteString("service_name=")
	builder.WriteString(w.ServiceName)
	builder.WriteString(", ")
	builder.WriteString("workspace_api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", w.WorkspaceAPIKeyID))
	builder.WriteString(", ")
	builder.WriteString("access_token_status=")
	builder.WriteString(w.AccessTokenStatus)
	builder.WriteString(", ")
	builder.WriteString("access_account=")
	builder.WriteString(w.AccessAccount)
	builder.WriteString(", ")
	builder.WriteString("access_username=")
	builder.WriteString(w.AccessUsername)
	builder.WriteString(", ")
	builder.WriteString("credential_status=")
	builder.WriteString(w.CredentialStatus)
	builder.WriteString(", ")
	builder.WriteString("credential_version=")
	builder.WriteString(w.CredentialVersion)
	builder.WriteString(", ")
	builder.WriteString("credential_secret_ref=")
	builder.WriteString(w.CredentialSecretRef)
	builder.WriteString(", ")
	builder.WriteString("access_requires_login=")
	builder.WriteString(fmt.Sprintf("%v", w.AccessRequiresLogin))
	builder.WriteString(", ")
	builder.WriteString("verification_slot_id=")
	builder.WriteString(w.VerificationSlotID)
	builder.WriteString(", ")
	builder.WriteString("customer_product=")
	builder.WriteString(fmt.Sprintf("%v", w.CustomerProduct))
	builder.WriteString(", ")
	builder.WriteString("application_binding=")
	builder.WriteString(w.ApplicationBinding)
	builder.WriteByte(')')
	return builder.String()
}

// Workspaces is a parsable slice of Workspace.
type Workspaces []*Workspace
