// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/workspace"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceCreate is the builder for creating a Workspace entity.
type WorkspaceCreate struct {
	config
	mutation *WorkspaceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (wc *WorkspaceCreate) SetCreatedAt(t time.Time) *WorkspaceCreate {
	wc.mutation.SetCreatedAt(t)
	return wc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCreatedAt(t *time.Time) *WorkspaceCreate {
	if t != nil {
		wc.SetCreatedAt(*t)
	}
	return wc
}

// SetUpdatedAt sets the "updated_at" field.
func (wc *WorkspaceCreate) SetUpdatedAt(t time.Time) *WorkspaceCreate {
	wc.mutation.SetUpdatedAt(t)
	return wc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableUpdatedAt(t *time.Time) *WorkspaceCreate {
	if t != nil {
		wc.SetUpdatedAt(*t)
	}
	return wc
}

// SetAccountID sets the "account_id" field.
func (wc *WorkspaceCreate) SetAccountID(s string) *WorkspaceCreate {
	wc.mutation.SetAccountID(s)
	return wc
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableAccountID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetAccountID(*s)
	}
	return wc
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (wc *WorkspaceCreate) SetOwnerAccountID(s string) *WorkspaceCreate {
	wc.mutation.SetOwnerAccountID(s)
	return wc
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableOwnerAccountID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetOwnerAccountID(*s)
	}
	return wc
}

// SetOwnerUserID sets the "owner_user_id" field.
func (wc *WorkspaceCreate) SetOwnerUserID(s string) *WorkspaceCreate {
	wc.mutation.SetOwnerUserID(s)
	return wc
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableOwnerUserID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetOwnerUserID(*s)
	}
	return wc
}

// SetUserID sets the "user_id" field.
func (wc *WorkspaceCreate) SetUserID(s string) *WorkspaceCreate {
	wc.mutation.SetUserID(s)
	return wc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableUserID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetUserID(*s)
	}
	return wc
}

// SetName sets the "name" field.
func (wc *WorkspaceCreate) SetName(s string) *WorkspaceCreate {
	wc.mutation.SetName(s)
	return wc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableName(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetName(*s)
	}
	return wc
}

// SetURL sets the "url" field.
func (wc *WorkspaceCreate) SetURL(s string) *WorkspaceCreate {
	wc.mutation.SetURL(s)
	return wc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableURL(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetURL(*s)
	}
	return wc
}

// SetState sets the "state" field.
func (wc *WorkspaceCreate) SetState(s string) *WorkspaceCreate {
	wc.mutation.SetState(s)
	return wc
}

// SetNillableState sets the "state" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableState(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetState(*s)
	}
	return wc
}

// SetStatus sets the "status" field.
func (wc *WorkspaceCreate) SetStatus(s string) *WorkspaceCreate {
	wc.mutation.SetStatus(s)
	return wc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableStatus(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetStatus(*s)
	}
	return wc
}

// SetPurchaseReceiptID sets the "purchase_receipt_id" field.
func (wc *WorkspaceCreate) SetPurchaseReceiptID(s string) *WorkspaceCreate {
	wc.mutation.SetPurchaseReceiptID(s)
	return wc
}

// SetNillablePurchaseReceiptID sets the "purchase_receipt_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillablePurchaseReceiptID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetPurchaseReceiptID(*s)
	}
	return wc
}

// SetBillingStateJSON sets the "billing_state_json" field.
func (wc *WorkspaceCreate) SetBillingStateJSON(s string) *WorkspaceCreate {
	wc.mutation.SetBillingStateJSON(s)
	return wc
}

// SetNillableBillingStateJSON sets the "billing_state_json" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableBillingStateJSON(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetBillingStateJSON(*s)
	}
	return wc
}

// SetStorageID sets the "storage_id" field.
func (wc *WorkspaceCreate) SetStorageID(s string) *WorkspaceCreate {
	wc.mutation.SetStorageID(s)
	return wc
}

// SetNillableStorageID sets the "storage_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableStorageID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetStorageID(*s)
	}
	return wc
}

// SetCurrentComputeAllocationID sets the "current_compute_allocation_id" field.
func (wc *WorkspaceCreate) SetCurrentComputeAllocationID(s string) *WorkspaceCreate {
	wc.mutation.SetCurrentComputeAllocationID(s)
	return wc
}

// SetNillableCurrentComputeAllocationID sets the "current_compute_allocation_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCurrentComputeAllocationID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetCurrentComputeAllocationID(*s)
	}
	return wc
}

// SetCurrentAttachmentID sets the "current_attachment_id" field.
func (wc *WorkspaceCreate) SetCurrentAttachmentID(s string) *WorkspaceCreate {
	wc.mutation.SetCurrentAttachmentID(s)
	return wc
}

// SetNillableCurrentAttachmentID sets the "current_attachment_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCurrentAttachmentID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetCurrentAttachmentID(*s)
	}
	return wc
}

// SetRuntimeID sets the "runtime_id" field.
func (wc *WorkspaceCreate) SetRuntimeID(s string) *WorkspaceCreate {
	wc.mutation.SetRuntimeID(s)
	return wc
}

// SetNillableRuntimeID sets the "runtime_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableRuntimeID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetRuntimeID(*s)
	}
	return wc
}

// SetRuntimeServiceName sets the "runtime_service_name" field.
func (wc *WorkspaceCreate) SetRuntimeServiceName(s string) *WorkspaceCreate {
	wc.mutation.SetRuntimeServiceName(s)
	return wc
}

// SetNillableRuntimeServiceName sets the "runtime_service_name" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableRuntimeServiceName(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetRuntimeServiceName(*s)
	}
	return wc
}

// SetRuntimeServiceNameRoot sets the "runtime_service_name_root" field.
func (wc *WorkspaceCreate) SetRuntimeServiceNameRoot(s string) *WorkspaceCreate {
	wc.mutation.SetRuntimeServiceNameRoot(s)
	return wc
}

// SetNillableRuntimeServiceNameRoot sets the "runtime_service_name_root" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableRuntimeServiceNameRoot(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetRuntimeServiceNameRoot(*s)
	}
	return wc
}

// SetServiceName sets the "service_name" field.
func (wc *WorkspaceCreate) SetServiceName(s string) *WorkspaceCreate {
	wc.mutation.SetServiceName(s)
	return wc
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableServiceName(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetServiceName(*s)
	}
	return wc
}

// SetWorkspaceAPIKeyID sets the "workspace_api_key_id" field.
func (wc *WorkspaceCreate) SetWorkspaceAPIKeyID(i int64) *WorkspaceCreate {
	wc.mutation.SetWorkspaceAPIKeyID(i)
	return wc
}

// SetNillableWorkspaceAPIKeyID sets the "workspace_api_key_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableWorkspaceAPIKeyID(i *int64) *WorkspaceCreate {
	if i != nil {
		wc.SetWorkspaceAPIKeyID(*i)
	}
	return wc
}

// SetAccessTokenStatus sets the "access_token_status" field.
func (wc *WorkspaceCreate) SetAccessTokenStatus(s string) *WorkspaceCreate {
	wc.mutation.SetAccessTokenStatus(s)
	return wc
}

// SetNillableAccessTokenStatus sets the "access_token_status" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableAccessTokenStatus(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetAccessTokenStatus(*s)
	}
	return wc
}

// SetAccessAccount sets the "access_account" field.
func (wc *WorkspaceCreate) SetAccessAccount(s string) *WorkspaceCreate {
	wc.mutation.SetAccessAccount(s)
	return wc
}

// SetNillableAccessAccount sets the "access_account" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableAccessAccount(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetAccessAccount(*s)
	}
	return wc
}

// SetAccessUsername sets the "access_username" field.
func (wc *WorkspaceCreate) SetAccessUsername(s string) *WorkspaceCreate {
	wc.mutation.SetAccessUsername(s)
	return wc
}

// SetNillableAccessUsername sets the "access_username" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableAccessUsername(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetAccessUsername(*s)
	}
	return wc
}

// SetCredentialStatus sets the "credential_status" field.
func (wc *WorkspaceCreate) SetCredentialStatus(s string) *WorkspaceCreate {
	wc.mutation.SetCredentialStatus(s)
	return wc
}

// SetNillableCredentialStatus sets the "credential_status" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCredentialStatus(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetCredentialStatus(*s)
	}
	return wc
}

// SetCredentialVersion sets the "credential_version" field.
func (wc *WorkspaceCreate) SetCredentialVersion(s string) *WorkspaceCreate {
	wc.mutation.SetCredentialVersion(s)
	return wc
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCredentialVersion(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetCredentialVersion(*s)
	}
	return wc
}

// SetCredentialSecretRef sets the "credential_secret_ref" field.
func (wc *WorkspaceCreate) SetCredentialSecretRef(s string) *WorkspaceCreate {
	wc.mutation.SetCredentialSecretRef(s)
	return wc
}

// SetNillableCredentialSecretRef sets the "credential_secret_ref" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCredentialSecretRef(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetCredentialSecretRef(*s)
	}
	return wc
}

// SetAccessRequiresLogin sets the "access_requires_login" field.
func (wc *WorkspaceCreate) SetAccessRequiresLogin(b bool) *WorkspaceCreate {
	wc.mutation.SetAccessRequiresLogin(b)
	return wc
}

// SetNillableAccessRequiresLogin sets the "access_requires_login" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableAccessRequiresLogin(b *bool) *WorkspaceCreate {
	if b != nil {
		wc.SetAccessRequiresLogin(*b)
	}
	return wc
}

// SetVerificationSlotID sets the "verification_slot_id" field.
func (wc *WorkspaceCreate) SetVerificationSlotID(s string) *WorkspaceCreate {
	wc.mutation.SetVerificationSlotID(s)
	return wc
}

// SetNillableVerificationSlotID sets the "verification_slot_id" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableVerificationSlotID(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetVerificationSlotID(*s)
	}
	return wc
}

// SetCustomerProduct sets the "customer_product" field.
func (wc *WorkspaceCreate) SetCustomerProduct(b bool) *WorkspaceCreate {
	wc.mutation.SetCustomerProduct(b)
	return wc
}

// SetNillableCustomerProduct sets the "customer_product" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableCustomerProduct(b *bool) *WorkspaceCreate {
	if b != nil {
		wc.SetCustomerProduct(*b)
	}
	return wc
}

// SetApplicationBinding sets the "application_binding" field.
func (wc *WorkspaceCreate) SetApplicationBinding(s string) *WorkspaceCreate {
	wc.mutation.SetApplicationBinding(s)
	return wc
}

// SetNillableApplicationBinding sets the "application_binding" field if the given value is not nil.
func (wc *WorkspaceCreate) SetNillableApplicationBinding(s *string) *WorkspaceCreate {
	if s != nil {
		wc.SetApplicationBinding(*s)
	}
	return wc
}

// SetID sets the "id" field.
func (wc *WorkspaceCreate) SetID(s string) *WorkspaceCreate {
	wc.mutation.SetID(s)
	return wc
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wc *WorkspaceCreate) Mutation() *WorkspaceMutation {
	return wc.mutation
}

// Save creates the Workspace in the database.
func (wc *WorkspaceCreate) Save(ctx context.Context) (*Workspace, error) {
	wc.defaults()
	return withHooks(ctx, wc.sqlSave, wc.mutation, wc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WorkspaceCreate) SaveX(ctx context.Context) *Workspace {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wc *WorkspaceCreate) Exec(ctx context.Context) error {
	_, err := wc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wc *WorkspaceCreate) ExecX(ctx context.Context) {
	if err := wc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wc *WorkspaceCreate) defaults() {
	if _, ok := wc.mutation.CreatedAt(); !ok {
		v := workspace.DefaultCreatedAt()
		wc.mutation.SetCreatedAt(v)
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		v := workspace.DefaultUpdatedAt()
		wc.mutation.SetUpdatedAt(v)
	}
	if _, ok := wc.mutation.AccountID(); !ok {
		v := workspace.DefaultAccountID
		wc.mutation.SetAccountID(v)
	}
	if _, ok := wc.mutation.OwnerAccountID(); !ok {
		v := workspace.DefaultOwnerAccountID
		wc.mutation.SetOwnerAccountID(v)
	}
	if _, ok := wc.mutation.OwnerUserID(); !ok {
		v := workspace.DefaultOwnerUserID
		wc.mutation.SetOwnerUserID(v)
	}
	if _, ok := wc.mutation.UserID(); !ok {
		v := workspace.DefaultUserID
		wc.mutation.SetUserID(v)
	}
	if _, ok := wc.mutation.Name(); !ok {
		v := workspace.DefaultName
		wc.mutation.SetName(v)
	}
	if _, ok := wc.mutation.URL(); !ok {
		v := workspace.DefaultURL
		wc.mutation.SetURL(v)
	}
	if _, ok := wc.mutation.State(); !ok {
		v := workspace.DefaultState
		wc.mutation.SetState(v)
	}
	if _, ok := wc.mutation.Status(); !ok {
		v := workspace.DefaultStatus
		wc.mutation.SetStatus(v)
	}
	if _, ok := wc.mutation.PurchaseReceiptID(); !ok {
		v := workspace.DefaultPurchaseReceiptID
		wc.mutation.SetPurchaseReceiptID(v)
	}
	if _, ok := wc.mutation.BillingStateJSON(); !ok {
		v := workspace.DefaultBillingStateJSON
		wc.mutation.SetBillingStateJSON(v)
	}
	if _, ok := wc.mutation.StorageID(); !ok {
		v := workspace.DefaultStorageID
		wc.mutation.SetStorageID(v)
	}
	if _, ok := wc.mutation.CurrentComputeAllocationID(); !ok {
		v := workspace.DefaultCurrentComputeAllocationID
		wc.mutation.SetCurrentComputeAllocationID(v)
	}
	if _, ok := wc.mutation.CurrentAttachmentID(); !ok {
		v := workspace.DefaultCurrentAttachmentID
		wc.mutation.SetCurrentAttachmentID(v)
	}
	if _, ok := wc.mutation.RuntimeID(); !ok {
		v := workspace.DefaultRuntimeID
		wc.mutation.SetRuntimeID(v)
	}
	if _, ok := wc.mutation.RuntimeServiceName(); !ok {
		v := workspace.DefaultRuntimeServiceName
		wc.mutation.SetRuntimeServiceName(v)
	}
	if _, ok := wc.mutation.RuntimeServiceNameRoot(); !ok {
		v := workspace.DefaultRuntimeServiceNameRoot
		wc.mutation.SetRuntimeServiceNameRoot(v)
	}
	if _, ok := wc.mutation.ServiceName(); !ok {
		v := workspace.DefaultServiceName
		wc.mutation.SetServiceName(v)
	}
	if _, ok := wc.mutation.AccessTokenStatus(); !ok {
		v := workspace.DefaultAccessTokenStatus
		wc.mutation.SetAccessTokenStatus(v)
	}
	if _, ok := wc.mutation.AccessAccount(); !ok {
		v := workspace.DefaultAccessAccount
		wc.mutation.SetAccessAccount(v)
	}
	if _, ok := wc.mutation.AccessUsername(); !ok {
		v := workspace.DefaultAccessUsername
		wc.mutation.SetAccessUsername(v)
	}
	if _, ok := wc.mutation.CredentialStatus(); !ok {
		v := workspace.DefaultCredentialStatus
		wc.mutation.SetCredentialStatus(v)
	}
	if _, ok := wc.mutation.CredentialVersion(); !ok {
		v := workspace.DefaultCredentialVersion
		wc.mutation.SetCredentialVersion(v)
	}
	if _, ok := wc.mutation.CredentialSecretRef(); !ok {
		v := workspace.DefaultCredentialSecretRef
		wc.mutation.SetCredentialSecretRef(v)
	}
	if _, ok := wc.mutation.AccessRequiresLogin(); !ok {
		v := workspace.DefaultAccessRequiresLogin
		wc.mutation.SetAccessRequiresLogin(v)
	}
	if _, ok := wc.mutation.VerificationSlotID(); !ok {
		v := workspace.DefaultVerificationSlotID
		wc.mutation.SetVerificationSlotID(v)
	}
	if _, ok := wc.mutation.CustomerProduct(); !ok {
		v := workspace.DefaultCustomerProduct
		wc.mutation.SetCustomerProduct(v)
	}
	if _, ok := wc.mutation.ApplicationBinding(); !ok {
		v := workspace.DefaultApplicationBinding
		wc.mutation.SetApplicationBinding(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wc *WorkspaceCreate) check() error {
	if _, ok := wc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Workspace.created_at"`)}
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Workspace.updated_at"`)}
	}
	if _, ok := wc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Workspace.account_id"`)}
	}
	if _, ok := wc.mutation.OwnerAccountID(); !ok {
		return &ValidationError{Name: "owner_account_id", err: errors.New(`ent: missing required field "Workspace.owner_account_id"`)}
	}
	if _, ok := wc.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Workspace.owner_user_id"`)}
	}
	if _, ok := wc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Workspace.user_id"`)}
	}
	if _, ok := wc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Workspace.name"`)}
	}
	if _, ok := wc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Workspace.url"`)}
	}
	if _, ok := wc.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Workspace.state"`)}
	}
	if _, ok := wc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Workspace.status"`)}
	}
	if _, ok := wc.mutation.PurchaseReceiptID(); !ok {
		return &ValidationError{Name: "purchase_receipt_id", err: errors.New(`ent: missing required field "Workspace.purchase_receipt_id"`)}
	}
	if _, ok := wc.mutation.BillingStateJSON(); !ok {
		return &ValidationError{Name: "billing_state_json", err: errors.New(`ent: missing required field "Workspace.billing_state_json"`)}
	}
	if _, ok := wc.mutation.StorageID(); !ok {
		return &ValidationError{Name: "storage_id", err: errors.New(`ent: missing required field "Workspace.storage_id"`)}
	}
	if _, ok := wc.mutation.CurrentComputeAllocationID(); !ok {
		return &ValidationError{Name: "current_compute_allocation_id", err: errors.New(`ent: missing required field "Workspace.current_compute_allocation_id"`)}
	}
	if _, ok := wc.mutation.CurrentAttachmentID(); !ok {
		return &ValidationError{Name: "current_attachment_id", err: errors.New(`ent: missing required field "Workspace.current_attachment_id"`)}
	}
	if _, ok := wc.mutation.RuntimeID(); !ok {
		return &ValidationError{Name: "runtime_id", err: errors.New(`ent: missing required field "Workspace.runtime_id"`)}
	}
	if _, ok := wc.mutation.RuntimeServiceName(); !ok {
		return &ValidationError{Name: "runtime_service_name", err: errors.New(`ent: missing required field "Workspace.runtime_service_name"`)}
	}
	if _, ok := wc.mutation.RuntimeServiceNameRoot(); !ok {
		return &ValidationError{Name: "runtime_service_name_root", err: errors.New(`ent: missing required field "Workspace.runtime_service_name_root"`)}
	}
	if _, ok := wc.mutation.ServiceName(); !ok {
		return &ValidationError{Name: "service_name", err: errors.New(`ent: missing required field "Workspace.service_name"`)}
	}
	if v, ok := wc.mutation.WorkspaceAPIKeyID(); ok {
		if err := workspace.WorkspaceAPIKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_api_key_id", err: fmt.Errorf(`ent: validator failed for field "Workspace.workspace_api_key_id": %w`, err)}
		}
	}
	if _, ok := wc.mutation.AccessTokenStatus(); !ok {
		return &ValidationError{Name: "access_token_status", err: errors.New(`ent: missing required field "Workspace.access_token_status"`)}
	}
	if _, ok := wc.mutation.AccessAccount(); !ok {
		return &ValidationError{Name: "access_account", err: errors.New(`ent: missing required field "Workspace.access_account"`)}
	}
	if _, ok := wc.mutation.AccessUsername(); !ok {
		return &ValidationError{Name: "access_username", err: errors.New(`ent: missing required field "Workspace.access_username"`)}
	}
	if _, ok := wc.mutation.CredentialStatus(); !ok {
		return &ValidationError{Name: "credential_status", err: errors.New(`ent: missing required field "Workspace.credential_status"`)}
	}
	if _, ok := wc.mutation.CredentialVersion(); !ok {
		return &ValidationError{Name: "credential_version", err: errors.New(`ent: missing required field "Workspace.credential_version"`)}
	}
	if _, ok := wc.mutation.CredentialSecretRef(); !ok {
		return &ValidationError{Name: "credential_secret_ref", err: errors.New(`ent: missing required field "Workspace.credential_secret_ref"`)}
	}
	if _, ok := wc.mutation.AccessRequiresLogin(); !ok {
		return &ValidationError{Name: "access_requires_login", err: errors.New(`ent: missing required field "Workspace.access_requires_login"`)}
	}
	if _, ok := wc.mutation.VerificationSlotID(); !ok {
		return &ValidationError{Name: "verification_slot_id", err: errors.New(`ent: missing required field "Workspace.verification_slot_id"`)}
	}
	if _, ok := wc.mutation.CustomerProduct(); !ok {
		return &ValidationError{Name: "customer_product", err: errors.New(`ent: missing required field "Workspace.customer_product"`)}
	}
	if _, ok := wc.mutation.ApplicationBinding(); !ok {
		return &ValidationError{Name: "application_binding", err: errors.New(`ent: missing required field "Workspace.application_binding"`)}
	}
	if v, ok := wc.mutation.ID(); ok {
		if err := workspace.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Workspace.id": %w`, err)}
		}
	}
	return nil
}

func (wc *WorkspaceCreate) sqlSave(ctx context.Context) (*Workspace, error) {
	if err := wc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Workspace.ID type: %T", _spec.ID.Value)
		}
	}
	wc.mutation.id = &_node.ID
	wc.mutation.done = true
	return _node, nil
}

func (wc *WorkspaceCreate) createSpec() (*Workspace, *sqlgraph.CreateSpec) {
	var (
		_node = &Workspace{config: wc.config}
		_spec = sqlgraph.NewCreateSpec(workspace.Table, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	)
	if id, ok := wc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := wc.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wc.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := wc.mutation.AccountID(); ok {
		_spec.SetField(workspace.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := wc.mutation.OwnerAccountID(); ok {
		_spec.SetField(workspace.FieldOwnerAccountID, field.TypeString, value)
		_node.OwnerAccountID = value
	}
	if value, ok := wc.mutation.OwnerUserID(); ok {
		_spec.SetField(workspace.FieldOwnerUserID, field.TypeString, value)
		_node.OwnerUserID = value
	}
	if value, ok := wc.mutation.UserID(); ok {
		_spec.SetField(workspace.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := wc.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wc.mutation.URL(); ok {
		_spec.SetField(workspace.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := wc.mutation.State(); ok {
		_spec.SetField(workspace.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := wc.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := wc.mutation.PurchaseReceiptID(); ok {
		_spec.SetField(workspace.FieldPurchaseReceiptID, field.TypeString, value)
		_node.PurchaseReceiptID = value
	}
	if value, ok := wc.mutation.BillingStateJSON(); ok {
		_spec.SetField(workspace.FieldBillingStateJSON, field.TypeString, value)
		_node.BillingStateJSON = value
	}
	if value, ok := wc.mutation.StorageID(); ok {
		_spec.SetField(workspace.FieldStorageID, field.TypeString, value)
		_node.StorageID = value
	}
	if value, ok := wc.mutation.CurrentComputeAllocationID(); ok {
		_spec.SetField(workspace.FieldCurrentComputeAllocationID, field.TypeString, value)
		_node.CurrentComputeAllocationID = value
	}
	if value, ok := wc.mutation.CurrentAttachmentID(); ok {
		_spec.SetField(workspace.FieldCurrentAttachmentID, field.TypeString, value)
		_node.CurrentAttachmentID = value
	}
	if value, ok := wc.mutation.RuntimeID(); ok {
		_spec.SetField(workspace.FieldRuntimeID, field.TypeString, value)
		_node.RuntimeID = value
	}
	if value, ok := wc.mutation.RuntimeServiceName(); ok {
		_spec.SetField(workspace.FieldRuntimeServiceName, field.TypeString, value)
		_node.RuntimeServiceName = value
	}
	if value, ok := wc.mutation.RuntimeServiceNameRoot(); ok {
		_spec.SetField(workspace.FieldRuntimeServiceNameRoot, field.TypeString, value)
		_node.RuntimeServiceNameRoot = value
	}
	if value, ok := wc.mutation.ServiceName(); ok {
		_spec.SetField(workspace.FieldServiceName, field.TypeString, value)
		_node.ServiceName = value
	}
	if value, ok := wc.mutation.WorkspaceAPIKeyID(); ok {
		_spec.SetField(workspace.FieldWorkspaceAPIKeyID, field.TypeInt64, value)
		_node.WorkspaceAPIKeyID = value
	}
	if value, ok := wc.mutation.AccessTokenStatus(); ok {
		_spec.SetField(workspace.FieldAccessTokenStatus, field.TypeString, value)
		_node.AccessTokenStatus = value
	}
	if value, ok := wc.mutation.AccessAccount(); ok {
		_spec.SetField(workspace.FieldAccessAccount, field.TypeString, value)
		_node.AccessAccount = value
	}
	if value, ok := wc.mutation.AccessUsername(); ok {
		_spec.SetField(workspace.FieldAccessUsername, field.TypeString, value)
		_node.AccessUsername = value
	}
	if value, ok := wc.mutation.CredentialStatus(); ok {
		_spec.SetField(workspace.FieldCredentialStatus, field.TypeString, value)
		_node.CredentialStatus = value
	}
	if value, ok := wc.mutation.CredentialVersion(); ok {
		_spec.SetField(workspace.FieldCredentialVersion, field.TypeString, value)
		_node.CredentialVersion = value
	}
	if value, ok := wc.mutation.CredentialSecretRef(); ok {
		_spec.SetField(workspace.FieldCredentialSecretRef, field.TypeString, value)
		_node.CredentialSecretRef = value
	}
	if value, ok := wc.mutation.AccessRequiresLogin(); ok {
		_spec.SetField(workspace.FieldAccessRequiresLogin, field.TypeBool, value)
		_node.AccessRequiresLogin = value
	}
	if value, ok := wc.mutation.VerificationSlotID(); ok {
		_spec.SetField(workspace.FieldVerificationSlotID, field.TypeString, value)
		_node.VerificationSlotID = value
	}
	if value, ok := wc.mutation.CustomerProduct(); ok {
		_spec.SetField(workspace.FieldCustomerProduct, field.TypeBool, value)
		_node.CustomerProduct = value
	}
	if value, ok := wc.mutation.ApplicationBinding(); ok {
		_spec.SetField(workspace.FieldApplicationBinding, field.TypeString, value)
		_node.ApplicationBinding = value
	}
	return _node, _spec
}

// WorkspaceCreateBulk is the builder for creating many Workspace entities in bulk.
type WorkspaceCreateBulk struct {
	config
	err      error
	builders []*WorkspaceCreate
}

// Save creates the Workspace entities in the database.
func (wcb *WorkspaceCreateBulk) Save(ctx context.Context) ([]*Workspace, error) {
	if wcb.err != nil {
		return nil, wcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wcb.builders))
	nodes := make([]*Workspace, len(wcb.builders))
	mutators := make([]Mutator, len(wcb.builders))
	for i := range wcb.builders {
		func(i int, root context.Context) {
			builder := wcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcb *WorkspaceCreateBulk) SaveX(ctx context.Context) []*Workspace {
	v, err := wcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcb *WorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := wcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcb *WorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := wcb.Exec(ctx); err != nil {
		panic(err)
	}
}
