// Code generated by proto/generate_event_identity.py. DO NOT EDIT.
//
// Source: the specification's contracts/events.json `x-aggregate-identity`, which
// fixes the aggregate type and the payload field supplying its id for every exact
// (eventType, schemaVersion). Regenerate with packages/contracts/proto/generate_event_identity.py.

package contracts

import (
	"encoding/json"
	"errors"
	"fmt"
)

// ErrEventIdentityUnknown reports an event version the specification does not define.
var ErrEventIdentityUnknown = errors.New("unknown event type or schema version")

// ErrEventAggregateIdentityMismatch reports an event whose recorded aggregate
// identity does not agree with the payload it carries.
var ErrEventAggregateIdentityMismatch = errors.New("event aggregate identity does not match its payload")

// EventIdentity is the aggregate identity the specification fixes for one exact
// event version. Outbox and Inbox rows must record exactly this aggregate type and
// the aggregate id carried by this payload field; the value is never free-form.
type EventIdentity struct {
	EventType        string
	SchemaVersion    int32
	Owner            string
	Consumers        []string
	AggregateType    string
	AggregateIDField string
}

// EventIdentities lists every event version the specification defines.
var EventIdentities = []EventIdentity{
	{EventType: "build.artifact_confirmed.v1", SchemaVersion: 1, Owner: "build", Consumers: []string{"capability", "ledger"}, AggregateType: "build_job", AggregateIDField: "buildJobId"},
	{EventType: "build.failed.v1", SchemaVersion: 1, Owner: "build", Consumers: []string{"ledger"}, AggregateType: "build_job", AggregateIDField: "buildJobId"},
	{EventType: "capability.version_registered.v1", SchemaVersion: 1, Owner: "capability", Consumers: []string{"build", "ledger"}, AggregateType: "capability_version", AggregateIDField: "capabilityVersionId"},
	{EventType: "catalog.policy_changed.v1", SchemaVersion: 1, Owner: "resource_catalog", Consumers: []string{"ledger", "workspace"}, AggregateType: "catalog_policy_version", AggregateIDField: "policyVersionId"},
	{EventType: "fabric.resources_observed.v1", SchemaVersion: 1, Owner: "fabric", Consumers: []string{"ledger", "runtime_control", "workspace"}, AggregateType: "resource_set", AggregateIDField: "resourceSetId"},
	{EventType: "fabric.route_observed.v1", SchemaVersion: 1, Owner: "fabric", Consumers: []string{"ledger", "workspace"}, AggregateType: "route_binding", AggregateIDField: "routeBindingId"},
	{EventType: "ledger.receipt_recorded.v1", SchemaVersion: 1, Owner: "ledger", Consumers: []string{"workspace"}, AggregateType: "receipt", AggregateIDField: "receiptId"},
	{EventType: "package.uploaded.v1", SchemaVersion: 1, Owner: "capability", Consumers: []string{"ledger"}, AggregateType: "package_version", AggregateIDField: "packageVersionId"},
	{EventType: "runtime.readiness_observed.v1", SchemaVersion: 1, Owner: "runtime_control", Consumers: []string{"ledger", "workspace"}, AggregateType: "runtime_instance", AggregateIDField: "runtimeInstanceId"},
	{EventType: "subscription.renewal_settings_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"gateway", "ledger", "tenant"}, AggregateType: "subscription", AggregateIDField: "subscriptionId"},
	{EventType: "tenant.access_revoked.v1", SchemaVersion: 1, Owner: "tenant", Consumers: []string{"build", "capability", "gateway", "ledger", "workspace"}, AggregateType: "tenant", AggregateIDField: "targetTenantId"},
	{EventType: "tenant.reenabled.v1", SchemaVersion: 1, Owner: "tenant", Consumers: []string{"gateway", "ledger", "workspace"}, AggregateType: "tenant", AggregateIDField: "targetTenantId"},
	{EventType: "tenant.restored.v1", SchemaVersion: 1, Owner: "tenant", Consumers: []string{"build", "capability", "gateway", "ledger"}, AggregateType: "tenant", AggregateIDField: "targetTenantId"},
	{EventType: "wallet.operation_observed.v1", SchemaVersion: 1, Owner: "gateway", Consumers: []string{"ledger", "workspace"}, AggregateType: "wallet_operation", AggregateIDField: "walletOperationId"},
	{EventType: "workspace.deletion_confirmed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"ledger", "tenant"}, AggregateType: "workspace", AggregateIDField: "workspaceId"},
	{EventType: "workspace.period_obligation_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"gateway", "ledger"}, AggregateType: "period_obligation", AggregateIDField: "obligationId"},
	{EventType: "workspace.plan_change_state_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"ledger"}, AggregateType: "plan_change", AggregateIDField: "planChangeId"},
	{EventType: "workspace.state_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"ledger"}, AggregateType: "workspace", AggregateIDField: "workspaceId"},
}

var eventIdentityIndex = func() map[eventIdentityKey]EventIdentity {
	index := make(map[eventIdentityKey]EventIdentity, len(EventIdentities))
	for _, identity := range EventIdentities {
		index[eventIdentityKey{eventType: identity.EventType, schemaVersion: identity.SchemaVersion}] = identity
	}
	return index
}()

type eventIdentityKey struct {
	eventType     string
	schemaVersion int32
}

// LookupEventIdentity returns the fixed identity for one exact event version.
func LookupEventIdentity(eventType string, schemaVersion int32) (EventIdentity, bool) {
	identity, ok := eventIdentityIndex[eventIdentityKey{eventType: eventType, schemaVersion: schemaVersion}]
	return identity, ok
}

// Subscribed reports whether owner is listed in this exact event version's x-consumers.
func (identity EventIdentity) Subscribed(owner string) bool {
	for _, consumer := range identity.Consumers {
		if consumer == owner {
			return true
		}
	}
	return false
}

// AggregateIDFromPayload reads this identity's aggregate id from the exact payload
// bytes recorded for the event. A payload that omits the field, carries a non-string
// value, or carries an empty value is rejected instead of being coerced.
func (identity EventIdentity) AggregateIDFromPayload(payload []byte) (string, error) {
	if len(payload) == 0 {
		return "", fmt.Errorf("%w: empty payload", ErrEventAggregateIdentityMismatch)
	}
	var decoded map[string]json.RawMessage
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return "", fmt.Errorf("%w: %v", ErrEventAggregateIdentityMismatch, err)
	}
	raw, ok := decoded[identity.AggregateIDField]
	if !ok {
		return "", fmt.Errorf("%w: payload has no %s", ErrEventAggregateIdentityMismatch, identity.AggregateIDField)
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return "", fmt.Errorf("%w: %s is not a string", ErrEventAggregateIdentityMismatch, identity.AggregateIDField)
	}
	if value == "" {
		return "", fmt.Errorf("%w: %s is empty", ErrEventAggregateIdentityMismatch, identity.AggregateIDField)
	}
	return value, nil
}
