// Code generated by proto/generate_event_identity.py. DO NOT EDIT.
//
// Source: packages/contracts/proto/events.json, which fixes `owner`,
// `schemaVersion`, and `x-consumers` for every exact event type. Regenerate with
// packages/contracts/proto/generate_event_identity.py.

package contracts

// EventIdentity is the fixed producer and consumer set the contract defines
// for one exact event version. An Outbox producer and an Inbox consumer must
// agree with it; the owner of an event version is never caller-supplied.
type EventIdentity struct {
	EventType     string
	SchemaVersion int32
	Owner         string
	Consumers     []string
}

// EventIdentities lists every event version the contract defines.
var EventIdentities = []EventIdentity{
	{EventType: "build.artifact_confirmed.v1", SchemaVersion: 1, Owner: "build", Consumers: []string{"capability", "ledger"}},
	{EventType: "build.failed.v1", SchemaVersion: 1, Owner: "build", Consumers: []string{"ledger"}},
	{EventType: "capability.version_registered.v1", SchemaVersion: 1, Owner: "capability", Consumers: []string{"build", "ledger"}},
	{EventType: "catalog.policy_changed.v1", SchemaVersion: 1, Owner: "resource_catalog", Consumers: []string{"ledger", "workspace"}},
	{EventType: "fabric.resources_observed.v1", SchemaVersion: 1, Owner: "serve", Consumers: []string{"ledger", "runtime_control", "workspace"}},
	{EventType: "ledger.receipt_recorded.v1", SchemaVersion: 1, Owner: "ledger", Consumers: []string{"workspace"}},
	{EventType: "package.uploaded.v1", SchemaVersion: 1, Owner: "capability", Consumers: []string{"ledger"}},
	{EventType: "serve.access_observed.v1", SchemaVersion: 1, Owner: "serve", Consumers: []string{"ledger", "workspace"}},
	{EventType: "serve.agent_readiness_observed.v1", SchemaVersion: 1, Owner: "serve", Consumers: []string{"ledger", "workspace"}},
	{EventType: "subscription.renewal_settings_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"gateway", "ledger", "tenant"}},
	{EventType: "tenant.access_revoked.v1", SchemaVersion: 1, Owner: "tenant", Consumers: []string{"build", "capability", "gateway", "ledger", "workspace"}},
	{EventType: "tenant.reenabled.v1", SchemaVersion: 1, Owner: "tenant", Consumers: []string{"gateway", "ledger", "workspace"}},
	{EventType: "tenant.restored.v1", SchemaVersion: 1, Owner: "tenant", Consumers: []string{"build", "capability", "gateway", "ledger"}},
	{EventType: "wallet.operation_observed.v1", SchemaVersion: 1, Owner: "gateway", Consumers: []string{"ledger", "workspace"}},
	{EventType: "workspace.deletion_confirmed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"ledger", "tenant"}},
	{EventType: "workspace.period_obligation_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"gateway", "ledger"}},
	{EventType: "workspace.plan_change_state_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"ledger"}},
	{EventType: "workspace.state_changed.v1", SchemaVersion: 1, Owner: "workspace", Consumers: []string{"ledger"}},
}

var eventIdentityIndex = func() map[eventIdentityKey]EventIdentity {
	index := make(map[eventIdentityKey]EventIdentity, len(EventIdentities))
	for _, identity := range EventIdentities {
		index[eventIdentityKey{eventType: identity.EventType, schemaVersion: identity.SchemaVersion}] = identity
	}
	return index
}()

type eventIdentityKey struct {
	eventType     string
	schemaVersion int32
}

// LookupEventIdentity returns the fixed identity for one exact event version.
func LookupEventIdentity(eventType string, schemaVersion int32) (EventIdentity, bool) {
	identity, ok := eventIdentityIndex[eventIdentityKey{eventType: eventType, schemaVersion: schemaVersion}]
	return identity, ok
}

// Subscribed reports whether owner is listed in this exact event version's x-consumers.
func (identity EventIdentity) Subscribed(owner string) bool {
	for _, consumer := range identity.Consumers {
		if consumer == owner {
			return true
		}
	}
	return false
}
