// Code generated from the canonical API and publisher schemas; DO NOT EDIT.
package publicjson

import "google.golang.org/protobuf/reflect/protoreflect"

var enumNames = map[protoreflect.FullName]map[protoreflect.EnumNumber]string{
	"opl.cloud.api.ErrorCodeEnum":                                       {1: "VALIDATION_FAILED", 2: "UNAUTHENTICATED", 3: "FORBIDDEN", 4: "NOT_FOUND", 5: "CSRF_INVALID", 6: "ORIGIN_REJECTED", 7: "IDEMPOTENCY_REQUIRED", 8: "IDEMPOTENCY_CONFLICT", 9: "VERSION_CONFLICT", 10: "LAST_OWNER", 11: "INVITATION_INVALID", 12: "TENANT_INACTIVE", 13: "TENANT_RESTORE_EXPIRED", 14: "GATEWAY_UNAVAILABLE", 15: "OWNER_CAPABILITY_UNAVAILABLE", 16: "WALLET_BINDING_REQUIRED", 17: "INSUFFICIENT_BALANCE", 18: "QUOTE_EXPIRED", 19: "QUOTE_MISMATCH", 20: "POLICY_UNCONFIGURED", 21: "CAPACITY_UNAVAILABLE", 22: "PROVIDER_CAPABILITY_UNSUPPORTED", 23: "RUNTIME_REVOKED", 24: "WEBUI_INCOMPATIBLE", 25: "MODEL_NOT_ALLOWED", 26: "PACKAGE_ARCHIVED", 27: "UPLOAD_EXPIRED", 28: "UPLOAD_PART_MISMATCH", 29: "UPLOAD_CHECKSUM_MISMATCH", 30: "PACKAGE_INVALID", 31: "BUILD_INPUT_REJECTED", 32: "BUILD_FAILED", 33: "ARTIFACT_REFERENCED", 34: "ARTIFACT_UNAVAILABLE", 35: "INCOMPATIBLE_VERSION", 36: "DATA_MIGRATION_REQUIRED", 37: "ROLLBACK_UNSAFE", 38: "WORKSPACE_NOT_READY", 39: "WORKSPACE_EXPIRED", 40: "OPERATION_IN_PROGRESS", 41: "EXTERNAL_OUTCOME_UNKNOWN", 42: "RESOURCE_DELETE_UNCONFIRMED", 43: "REFUND_PENDING", 44: "KEY_REVEAL_FORBIDDEN", 45: "APP_ACCESS_UNAVAILABLE", 46: "RATE_LIMITED", 47: "DEPENDENCY_UNAVAILABLE", 48: "INSTANCE_AUTHORIZATION_REQUIRED", 49: "INTERNAL_ERROR", 50: "PUBLISHER_NAMESPACE_MISMATCH", 51: "PUBLISHER_CONTRACT_INVALID", 52: "REFERENCE_CLAIM_INVALID", 53: "AUTHORIZATION_CONTEXT_EXPIRED", 54: "AUTHORIZATION_REVOKED", 55: "AUTHORIZATION_AUDIENCE_MISMATCH", 56: "ROUTE_GENERATION_CONFLICT", 57: "STALE_EXECUTION_EPOCH", 58: "TENANT_NOT_SUSPENDED", 59: "RENEWAL_PERIOD_ELAPSED", 60: "PLAN_CHANGE_EXISTS", 61: "PLAN_CHANGE_NOT_CANCELLABLE", 62: "PLAN_CHANGE_QUOTE_STALE", 63: "PLAN_TRANSITION_NOT_SUPPORTED", 64: "PLAN_TRANSITION_MIXED", 65: "PLAN_CHANGE_NO_OP", 66: "STORAGE_SHRINK_UNSUPPORTED", 67: "SUBSCRIPTION_VERSION_CONFLICT", 68: "PLAN_CHANGE_PAYMENT_REQUIRED", 69: "PLAN_CHANGE_PERIOD_ELAPSED", 70: "REFUND_ORIGINAL_CHARGE_CONFLICT", 71: "FUTURE_PERIOD_COMMITTED", 72: "SCHEDULED_PLAN_APPLICATION_CONFLICT"},
	"opl.cloud.api.OwnerEnum":                                           {1: "tenant", 2: "capability", 3: "build", 4: "workspace", 5: "runtime_control", 6: "fabric", 7: "gateway", 8: "resource_catalog", 9: "ledger", 10: "serve"},
	"opl.cloud.api.TenantRoleEnum":                                      {1: "owner", 2: "admin", 3: "member"},
	"opl.cloud.api.OperationStatusEnum":                                 {1: "accepted", 2: "running", 3: "awaiting_confirmation", 4: "succeeded", 5: "failed", 6: "needs_attention", 7: "cancelled"},
	"opl.cloud.api.OperationObservationResultEnum":                      {1: "confirmed", 2: "rejected", 3: "unknown"},
	"opl.cloud.api.TenantStatusEnum":                                    {1: "active", 2: "suspended", 3: "deleting", 4: "deleted"},
	"opl.cloud.api.TenantAssetCustodyStatusEnum":                        {1: "tenant_owned", 2: "restricted", 3: "retained"},
	"opl.cloud.api.MemberStatusEnum":                                    {1: "active", 2: "revoked"},
	"opl.cloud.api.InvitationRoleEnum":                                  {1: "admin", 2: "member"},
	"opl.cloud.api.InvitationStatusEnum":                                {1: "pending", 2: "accepted", 3: "revoked", 4: "expired"},
	"opl.cloud.api.InviteMemberRequestRoleEnum":                         {1: "admin", 2: "member"},
	"opl.cloud.api.AssetCustodyStatusEnum":                              {1: "restricted", 2: "retained"},
	"opl.cloud.api.NamespaceStatusEnum":                                 {1: "active", 2: "archived"},
	"opl.cloud.api.PackageVisibilityEnum":                               {1: "private", 2: "official"},
	"opl.cloud.api.PackageStatusEnum":                                   {1: "active", 2: "archived"},
	"opl.cloud.api.PackageVersionStatusEnum":                            {1: "upload_pending", 2: "uploaded", 3: "rejected"},
	"opl.cloud.api.UploadSessionStatusEnum":                             {1: "uploading", 2: "completed", 3: "expired"},
	"opl.cloud.api.UploadPartAuthorizationMethodEnum":                   {1: "PUT"},
	"opl.cloud.api.ModelRequirementCapabilityEnum":                      {1: "text", 2: "vision", 3: "embedding", 4: "audio"},
	"opl.cloud.api.CapabilityVersionStatusEnum":                         {1: "ready", 2: "deprecated", 3: "deleting", 4: "deleted"},
	"opl.cloud.api.CapabilityVersionProvenanceEnum":                     {1: "build", 2: "legacy_application"},
	"opl.cloud.api.BuildJobStatusEnum":                                  {1: "queued", 2: "validating", 3: "building", 4: "pushing", 5: "registering", 6: "succeeded", 7: "failed", 8: "needs_attention"},
	"opl.cloud.api.BuildLogLevelEnum":                                   {1: "info", 2: "warning", 3: "error"},
	"opl.cloud.api.RuntimeVersionStatusEnum":                            {1: "approved", 2: "deprecated", 3: "revoked"},
	"opl.cloud.api.WebuiVersionStatusEnum":                              {1: "approved", 2: "deprecated", 3: "revoked"},
	"opl.cloud.api.CatalogStatusRequestStatusEnum":                      {1: "deprecated", 2: "revoked"},
	"opl.cloud.api.ComputePlanAvailabilityEnum":                         {1: "available", 2: "unavailable", 3: "retired"},
	"opl.cloud.api.ComputePlanBillingModeEnum":                          {1: "prepaid_monthly", 2: "local_no_charge"},
	"opl.cloud.api.StoragePlanAvailabilityEnum":                         {1: "available", 2: "unavailable", 3: "retired"},
	"opl.cloud.api.StoragePlanBillingModeEnum":                          {1: "prepaid_monthly", 2: "local_no_charge"},
	"opl.cloud.api.PlanAvailabilityRequestAvailabilityEnum":             {1: "available", 2: "unavailable", 3: "retired"},
	"opl.cloud.api.PricePolicyVersionCurrencyEnum":                      {1: "USD"},
	"opl.cloud.api.PricePolicyVersionPlanChangePolicyVersionEnum":       {1: "workspace-plan-change-v1"},
	"opl.cloud.api.CreatePricePolicyRequestPlanChangePolicyVersionEnum": {1: "workspace-plan-change-v1"},
	"opl.cloud.api.RefundPolicyVersionAlgorithmEnum":                    {1: "workspace-delete-refund-v1"},
	"opl.cloud.api.CreateRefundPolicyRequestAlgorithmEnum":              {1: "workspace-delete-refund-v1"},
	"opl.cloud.api.RetentionPolicyVersionWorkspaceDataDispositionEnum":  {1: "destroy_after_confirmed_deletion"},
	"opl.cloud.api.RetentionPolicyVersionPackageHistoryDispositionEnum": {1: "retain"},
	"opl.cloud.api.RetentionPolicyVersionBuildHistoryDispositionEnum":   {1: "retain"},
	"opl.cloud.api.ModelPriceSourceEnum":                                {1: "gateway"},
	"opl.cloud.api.QuoteRequestPurposeEnum":                             {1: "deploy", 2: "resize", 3: "renew"},
	"opl.cloud.api.QuoteLineKindEnum":                                   {1: "compute", 2: "storage", 3: "product", 4: "adjustment_credit"},
	"opl.cloud.api.QuotePurposeEnum":                                    {1: "deploy", 2: "resize", 3: "renew"},
	"opl.cloud.api.QuoteStatusEnum":                                     {1: "offered", 2: "accepted", 3: "expired"},
	"opl.cloud.api.QuoteRuntimeReadbackRequirementEnum":                 {1: "required", 2: "not_applicable"},
	"opl.cloud.api.WorkspaceDeliveryModelEnum":                          {1: "legacy_resource_only", 2: "imported_application", 3: "agent_saas"},
	"opl.cloud.api.WorkspaceStatusEnum":                                 {1: "provisioning", 2: "active", 3: "updating", 4: "suspended", 5: "deleting", 6: "deleted", 7: "failed", 8: "needs_attention"},
	"opl.cloud.api.WorkspaceResourceReadinessEnum":                      {1: "pending", 2: "ready", 3: "unavailable", 4: "unknown"},
	"opl.cloud.api.WorkspaceApplicationAvailabilityEnum":                {1: "pending", 2: "available", 3: "unavailable", 4: "unknown"},
	"opl.cloud.api.CreateWorkspaceRequestRenewalModeEnum":               {1: "manual", 2: "automatic"},
	"opl.cloud.api.WorkspaceAccessAuthenticationModeEnum":               {1: "application_login", 2: "cloud_private", 3: "anonymous"},
	"opl.cloud.api.ModelConfigurationStatusEnum":                        {1: "pending", 2: "applied", 3: "failed", 4: "needs_attention"},
	"opl.cloud.api.DeploymentStatusEnum":                                {1: "queued", 2: "deploying", 3: "verifying", 4: "active", 5: "superseded", 6: "failed", 7: "rolling_back", 8: "rolled_back", 9: "needs_attention"},
	"opl.cloud.api.WorkspaceDeletionResourceDeletionStatusEnum":         {1: "pending", 2: "confirmed", 3: "rejected", 4: "unknown"},
	"opl.cloud.api.WorkspaceDeletionDataDeletionStatusEnum":             {1: "pending", 2: "confirmed", 3: "rejected", 4: "unknown"},
	"opl.cloud.api.WorkspaceDeletionRefundStatusEnum":                   {1: "not_applicable", 2: "requested", 3: "confirmed", 4: "rejected", 5: "unknown"},
	"opl.cloud.api.SubscriptionStatusEnum":                              {1: "pending", 2: "active", 3: "expired", 4: "terminated"},
	"opl.cloud.api.SubscriptionProvenanceEnum":                          {1: "quoted", 2: "legacy_import"},
	"opl.cloud.api.SubscriptionRenewalModeEnum":                         {1: "manual", 2: "automatic"},
	"opl.cloud.api.WalletOperationKindEnum":                             {1: "charge", 2: "refund", 3: "recharge"},
	"opl.cloud.api.WalletOperationStatusEnum":                           {1: "requested", 2: "confirmed", 3: "rejected", 4: "unknown"},
	"opl.cloud.api.WalletOperationPurposeEnum":                          {1: "base_period", 2: "upgrade_supplement", 3: "base_period_delete", 4: "upgrade_failure_full", 5: "supplement_delete_unused", 6: "next_period_plan_failure_full", 7: "recharge"},
	"opl.cloud.api.WalletSourceEnum":                                    {1: "gateway"},
	"opl.cloud.api.WalletStatusEnum":                                    {1: "available"},
	"opl.cloud.api.WalletCurrencyEnum":                                  {1: "USD"},
	"opl.cloud.api.UsageSourceEnum":                                     {1: "gateway"},
	"opl.cloud.api.GatewayKeyPurposeEnum":                               {1: "personal", 2: "workspace_managed"},
	"opl.cloud.api.GatewayKeyStatusEnum":                                {1: "active", 2: "revoked"},
	"opl.cloud.api.AuditEventOutcomeEnum":                               {1: "confirmed", 2: "rejected", 3: "unknown"},
	"opl.cloud.api.ReceiptKindEnum":                                     {1: "source_check", 2: "candidate", 3: "qualification", 4: "deployment", 5: "rollback", 6: "release", 7: "provider_action", 8: "wallet_action", 9: "plan_change", 10: "supplemental_charge", 11: "plan_change_failure_compensation", 12: "supplemental_deletion_refund", 13: "next_period_plan_settlement"},
	"opl.cloud.api.ReceiptOutcomeEnum":                                  {1: "confirmed", 2: "rejected", 3: "unknown"},
	"opl.cloud.api.QualificationStatusEnum":                             {1: "pending", 2: "qualified", 3: "rejected"},
	"opl.cloud.api.OperationKindEnum":                                   {1: "complete_upload", 2: "build", 3: "delete_capability_version", 4: "create_workspace", 5: "update_models", 6: "update_workspace", 7: "rollback_workspace", 8: "resize_workspace", 9: "renew_workspace", 10: "delete_workspace", 11: "create_tenant", 12: "bind_tenant_wallet", 13: "suspend_tenant", 14: "delete_tenant", 15: "restore_tenant", 16: "revoke_key", 17: "reconcile", 18: "adopt_workspace", 19: "resource_provision", 20: "resource_resize", 21: "resource_renew", 22: "resource_suspend", 23: "resource_resume", 24: "resource_delete", 25: "runtime_deploy", 26: "runtime_reload", 27: "runtime_retire", 28: "reenable_tenant", 29: "migration", 30: "update_renewal_settings", 31: "apply_scheduled_plan_change", 32: "cancel_plan_change", 33: "compensate_plan_change", 34: "refund_supplement_on_delete"},
	"opl.cloud.api.OperationStageEnum":                                  {1: "absence_verification", 2: "access_enablement", 3: "access_revocation", 4: "activation", 5: "actual_resource_evidence", 6: "admission", 7: "asset_custody", 8: "attachment", 9: "attachment_deletion", 10: "building", 11: "cancellation_guard", 12: "catalog_tombstone", 13: "compatibility", 14: "compute", 15: "compute_deletion", 16: "configuration", 17: "consent_commit", 18: "consent_validation", 19: "coverage_calculation", 20: "debit", 21: "deletion_evidence", 22: "failure_fence", 23: "grant_revocation", 24: "identity_verification", 25: "key", 26: "key_revocation", 27: "membership", 28: "obligation_check", 29: "original_action_readback", 30: "owner_switch", 31: "payment_authorization", 32: "period_boundary", 33: "period_update", 34: "plan_change_commit", 35: "plan_commit", 36: "provider_renewal", 37: "provider_resume", 38: "provider_suspend", 39: "pushing", 40: "queued", 41: "quote_binding", 42: "readback", 43: "receipt", 44: "reconciliation", 45: "reference_check", 46: "refund", 47: "refund_original_charge", 48: "registering", 49: "reload", 50: "resource_preflight", 51: "restore_window_check", 52: "retirement", 53: "runtime", 54: "runtime_deletion", 55: "schedule_cancel", 56: "schedule_commit", 57: "secret_unbinding", 58: "snapshot_import", 59: "source_verification", 60: "storage", 61: "storage_deletion", 62: "succeeded", 63: "supplement_payment", 64: "target_period_payment", 65: "tenant_state_check", 66: "upload_verification", 67: "validating", 68: "verification", 69: "wallet_binding", 70: "workspace_deletion", 71: "workspace_resumption", 72: "workspace_suspension", 73: "write_barrier"},
	"opl.cloud.api.OperationOwnerEnum":                                  {1: "tenant", 2: "capability", 3: "build", 4: "workspace", 5: "runtime_control", 6: "fabric", 7: "gateway", 8: "resource_catalog", 9: "serve"},
	"opl.cloud.api.ImagePlatformOsEnum":                                 {1: "linux"},
	"opl.cloud.api.ImagePlatformArchitectureEnum":                       {1: "amd64", 2: "arm64"},
	"opl.cloud.api.RecipeArtifactMediaTypeEnum":                         {1: "application/vnd.opl.build-recipe.v1+tar"},
	"opl.cloud.api.PackageBuildInputContextNameEnum":                    {1: "agent_package"},
	"opl.cloud.api.WebuiBuildInputContextNameEnum":                      {1: "webui"},
	"opl.cloud.api.BuildRecipeContractVersionEnum":                      {1: "opl-build-recipe/v1"},
	"opl.cloud.api.BuildRecipeContractRuntimeContextNameEnum":           {1: "runtime"},
	"opl.cloud.api.BuildRecipeContractNetworkPolicyEnum":                {1: "none"},
	"opl.cloud.api.ModelConfigurationContractProtocolEnum":              {1: "opl-model-config/v1"},
	"opl.cloud.api.ModelConfigurationContractRequestFieldsEnum":         {1: "version", 2: "selections"},
	"opl.cloud.api.ModelConfigurationContractReadbackFieldsEnum":        {1: "appliedVersion", 2: "selections"},
	"opl.cloud.api.DataUpgradeContractModeEnum":                         {1: "compatible", 2: "publisher_migration"},
	"opl.cloud.api.RuntimePublisherContractSchemaVersionEnum":           {1: "opl-publisher-contract/v1"},
	"opl.cloud.api.RuntimePublisherContractKindEnum":                    {1: "runtime"},
	"opl.cloud.api.WebuiPublisherContractSchemaVersionEnum":             {1: "opl-publisher-contract/v1"},
	"opl.cloud.api.WebuiPublisherContractKindEnum":                      {1: "webui"},
	"opl.cloud.api.WebuiPublisherContractUiProtocolVersionEnum":         {1: "opl-webui/v1"},
	"opl.cloud.api.WebuiPublisherContractIntegrationModeEnum":           {1: "bundled_static"},
	"opl.cloud.api.WebuiPublisherContractAuthenticationProtocolEnum":    {1: "opl-application-session/v1"},
	"opl.cloud.api.PublisherContractReferenceKindEnum":                  {1: "runtime", 2: "webui"},
	"opl.cloud.api.DeploymentDescriptorSchemaVersionEnum":               {1: "opl-deployment-descriptor/v1"},
	"opl.cloud.api.DeploymentDescriptorProvenanceEnum":                  {1: "build", 2: "legacy_application"},
	"opl.cloud.api.PublisherNamespaceKindEnum":                          {1: "official", 2: "third_party"},
	"opl.cloud.api.PublisherNamespaceStatusEnum":                        {1: "approved", 2: "revoked"},
	"opl.cloud.api.CreatePublisherNamespaceRequestKindEnum":             {1: "official", 2: "third_party"},
	"opl.cloud.api.RenewalPolicyVersionEnum":                            {1: "renewal-policy/v1"},
	"opl.cloud.api.RenewalPolicyTriggerEnum":                            {1: "manual_or_explicitly_consented_automatic"},
	"opl.cloud.api.RenewalPolicyEffectiveStartEnum":                     {1: "previous_paid_through"},
	"opl.cloud.api.AuthorizationActionEnum":                             {1: "acceptInvitation", 2: "acquireReference", 3: "activateRoute", 4: "adoptWorkspace", 5: "appendPlanChangeEvidence", 6: "appendReceipt", 7: "archiveNamespace", 8: "archivePackage", 9: "bindManagedSecret", 10: "bindReference", 11: "bindTenantWallet", 12: "cancelAcceptedObligation", 13: "cancelPlanChange", 14: "chargeAcceptedObligation", 15: "chargePlanChangeSupplement", 16: "claimNextPeriodObligation", 17: "closeoutAcceptedObligation", 18: "completeAcceptedObligation", 19: "completeUpload", 20: "createBuild", 21: "createComputePlan", 22: "createGatewayKey", 23: "createNamespace", 24: "createPackage", 25: "createPricePolicyVersion", 26: "createPublisherNamespace", 27: "createQuote", 28: "createRefundPolicyVersion", 29: "createRetentionPolicyVersion", 30: "createStoragePlan", 31: "createTenant", 32: "createUpload", 33: "createUploadPart", 34: "createWorkspace", 35: "deleteCapabilityVersion", 36: "deleteTenant", 37: "deleteWorkspace", 38: "executeScheduledPlanChange", 39: "fenceRouteEpoch", 40: "getAdminTenant", 41: "getBuild", 42: "getBuildRuntimePolicy", 43: "getCapabilityVersion", 44: "getDeployment", 45: "getLoginContext", 46: "getOperation", 47: "getPackage", 48: "getPackageVersion", 49: "getPlanChange", 50: "getQuote", 51: "getReceipt", 52: "getSession", 53: "getSubscription", 54: "getTenant", 55: "getTenantAssetCustody", 56: "getTenantLifecycleOperation", 57: "getUpload", 58: "getWallet", 59: "getWorkspace", 60: "getWorkspaceAccess", 61: "getWorkspaceDeletion", 62: "getWorkspaceModels", 63: "inviteMember", 64: "issueAcceptedOperationGrant", 65: "listAdminOperations", 66: "listAuditEvents", 67: "listBuildLogs", 68: "listBuilds", 69: "listCapabilityVersions", 70: "listComputePlans", 71: "listDeployments", 72: "listGatewayKeys", 73: "listInvitations", 74: "listMembers", 75: "listModels", 76: "listNamespaces", 77: "listPackageVersions", 78: "listPackages", 79: "listPlanChanges", 80: "listPricePolicyVersions", 81: "listPublisherNamespaces", 82: "listQualifications", 83: "listReceipts", 84: "listRechargeRecords", 85: "listRefundPolicyVersions", 86: "listRetentionPolicyVersions", 87: "listRuntimeVersions", 88: "listStoragePlans", 89: "listTenants", 90: "listUsage", 91: "listWebuiVersions", 92: "listWorkspaceTransactions", 93: "listWorkspaces", 94: "login", 95: "logout", 96: "observeResources", 97: "observeRoute", 98: "provisionAcceptedResources", 99: "publishOfficialPackage", 100: "readApplicationCredentials", 101: "readApprovedPlanTransition", 102: "readArtifact", 103: "readAuthorizationContext", 104: "readClaimUsage", 105: "readNextPeriodObligation", 106: "readOwnerCommit", 107: "readRenewalConsent", 108: "readSubscriptionPlanState", 109: "readWalletAction", 110: "reconcileOperation", 111: "reenableTenant", 112: "refundConfirmedDeletion", 113: "refundPlanChangeCompensation", 114: "refundSupplementOnDeletion", 115: "registerRuntimeVersion", 116: "registerWebuiVersion", 117: "releaseReference", 118: "removeMember", 119: "renewAcceptedResources", 120: "renewWorkspace", 121: "reserveRuntime", 122: "resizeAcceptedResources", 123: "resizeWorkspace", 124: "resolveBuildInput", 125: "resolvePublisherContract", 126: "restoreTenant", 127: "resumeTenantWorkspaces", 128: "retireRuntime", 129: "retryBuild", 130: "revealGatewayKey", 131: "revealWorkspaceApplicationCredentials", 132: "revokeGatewayKey", 133: "revokeInvitation", 134: "revokePublisherNamespace", 135: "rollbackRoute", 136: "rollbackWorkspace", 137: "setBuildRuntimePolicy", 138: "setComputePlanAvailability", 139: "setRuntimeVersionStatus", 140: "setStoragePlanAvailability", 141: "setWebuiVersionStatus", 142: "suspendTenant", 143: "updateMemberRole", 144: "updateNamespace", 145: "updatePackage", 146: "updateRenewalSettings", 147: "updateWorkspaceModels", 148: "updateWorkspaceVersion", 149: "readExecutionPlan", 150: "restoreAfterResourceChange", 151: "debitScheduledPeriod", 152: "readPlanChangeFailure"},
	"opl.cloud.api.ServiceIdentityEnum":                                 {1: "console_bff", 2: "capability", 3: "build", 4: "workspace", 5: "runtime_control", 6: "fabric", 7: "gateway_integration", 8: "resource_catalog", 9: "ledger"},
	"opl.cloud.api.WorkspaceApplicationCredentialKindEnum":              {1: "workspace_admin_password", 2: "workspace_session_secret", 3: "gateway_key"},
	"opl.cloud.api.WorkspaceApplicationPortProtocolEnum":                {1: "TCP", 2: "UDP"},
	"opl.cloud.api.WorkspaceApplicationDependencyHealthCheckTypeEnum":   {1: "tcp", 2: "http", 3: "exec"},
	"opl.cloud.api.WorkspaceApplicationRevisionExposurePolicyEnum":      {1: "anonymous", 2: "application", 3: "cloud_private"},
	"opl.cloud.api.ApplicationOwnedAccessContractModeEnum":              {1: "application"},
	"opl.cloud.api.CloudPrivateAccessContractModeEnum":                  {1: "cloud_private"},
	"opl.cloud.api.CloudPrivateAccessContractEntryContractEnum":         {1: "WorkspaceApplicationEntry"},
	"opl.cloud.api.AnonymousAccessContractModeEnum":                     {1: "anonymous"},
	"opl.cloud.api.TenantWorkspaceActionActionEnum":                     {1: "suspend", 2: "resume", 3: "delete"},
	"opl.cloud.api.TenantWorkspaceActionOperationOwnerEnum":             {1: "workspace"},
	"opl.cloud.api.TenantWorkspaceActionStatusEnum":                     {1: "accepted", 2: "running", 3: "awaiting_confirmation", 4: "succeeded", 5: "failed", 6: "needs_attention", 7: "cancelled"},
	"opl.cloud.api.TenantWorkspaceSkipReasonEnum":                       {1: "not_suspended_by_tenant", 2: "paid_period_expired", 3: "already_deleted", 4: "resources_absent", 5: "resources_unknown", 6: "operation_in_progress"},
	"opl.cloud.api.TenantLifecycleProgressAccessStatusEnum":             {1: "enabled", 2: "revoked"},
	"opl.cloud.api.UpdateRenewalSettingsRequestRenewalModeEnum":         {1: "manual", 2: "automatic"},
	"opl.cloud.api.PackageFormatContractReferenceOwnerEnum":             {1: "framework"},
	"opl.cloud.api.UpgradePlanRulesKindEnum":                            {1: "upgrade_immediate"},
	"opl.cloud.api.UpgradePlanRulesEffectiveWhenEnum":                   {1: "resource_and_runtime_readback_confirmed"},
	"opl.cloud.api.UpgradePlanRulesOldPriceSourceEnum":                  {1: "accepted_applied_subscription_plan"},
	"opl.cloud.api.UpgradePlanRulesChargeClockEnum":                     {1: "quote_pricing_basis_at_frozen_on_acceptance"},
	"opl.cloud.api.UpgradePlanRulesTimeUnitEnum":                        {1: "utc_integer_milliseconds"},
	"opl.cloud.api.UpgradePlanRulesChargeRoundingEnum":                  {1: "ceil_once_usd_micro"},
	"opl.cloud.api.UpgradePlanRulesZeroChargeEnum":                      {1: "record_evidence_skip_gateway"},
	"opl.cloud.api.UpgradePlanRulesKnownFailureCompensationEnum":        {1: "full_unrefunded_original_supplement"},
	"opl.cloud.api.UpgradePlanRulesUnknownOutcomeEnum":                  {1: "read_original_action_no_refund"},
	"opl.cloud.api.UpgradePlanRulesIrreversibleResidualCostOwnerEnum":   {1: "platform"},
	"opl.cloud.api.UpgradePlanRulesSupplementDeleteRefundEnum":          {1: "floor_unused_supplement_coverage"},
	"opl.cloud.api.DowngradePlanRulesKindEnum":                          {1: "downgrade_next_period"},
	"opl.cloud.api.DowngradePlanRulesPlannedBoundaryEnum":               {1: "original_paid_through"},
	"opl.cloud.api.DowngradePlanRulesCurrentPeriodRefundEnum":           {1: "none"},
	"opl.cloud.api.DowngradePlanRulesNextPeriodPriceEnum":               {1: "accepted_target_plan_quote"},
	"opl.cloud.api.DowngradePlanRulesCancelBeforeEnum":                  {1: "next_period_payment_obligation_accepted"},
	"opl.cloud.api.DowngradePlanRulesEarlyPaidChangeEnum":               {1: "do_not_reduce_resources_before_original_paid_through"},
	"opl.cloud.api.DowngradePlanRulesManualUnpaidBoundaryEnum":          {1: "awaiting_payment_suspend_unpaid_usage"},
	"opl.cloud.api.DowngradePlanRulesKnownFailureCompensationEnum":      {1: "full_unrefunded_target_period_charge"},
	"opl.cloud.api.DowngradePlanRulesFallbackEnum":                      {1: "none_no_old_price_renewal_or_sku_substitution"},
	"opl.cloud.api.PlanChangePolicyVersionEnum":                         {1: "workspace-plan-change-v1"},
	"opl.cloud.api.PlanChangePolicyApprovalStatusEnum":                  {1: "approved"},
	"opl.cloud.api.PlanChangePolicyClassificationEnum":                  {1: "approved_comparable_resources_not_price_or_sku_name"},
	"opl.cloud.api.PlanChangePolicyMixedOrIncomparableTransitionEnum":   {1: "reject"},
	"opl.cloud.api.PlanChangePolicyNoOpTransitionEnum":                  {1: "reject"},
	"opl.cloud.api.PlanChangePolicyStorageShrinkEnum":                   {1: "reject_unless_owner_supported_transition"},
	"opl.cloud.api.PlanChangePolicyConcurrencyEnum":                     {1: "one_unfinished_plan_change_per_workspace"},
	"opl.cloud.api.PlanChangePolicyCancelAndReplaceEnum":                {1: "explicit_cancel_then_new_quote"},
	"opl.cloud.api.PlanChangePolicyBaseRefundPolicyEnum":                {1: "preserve_original_base_order_policy"},
	"opl.cloud.api.PlanChangePolicyProviderExecutionPlanEnum":           {1: "approved_strategy_frozen_before_quote"},
	"opl.cloud.api.UpgradeProrationRoundingEnum":                        {1: "ceil_once_usd_micro"},
	"opl.cloud.api.PlanChangeCalculationPolicyVersionEnum":              {1: "workspace-plan-change-v1"},
	"opl.cloud.api.PlanChangeCalculationKindEnum":                       {1: "upgrade_immediate", 2: "downgrade_next_period"},
	"opl.cloud.api.PlanChangeKindEnum":                                  {1: "upgrade_immediate", 2: "downgrade_next_period"},
	"opl.cloud.api.PlanChangeStatusEnum":                                {1: "requested", 2: "scheduled", 3: "awaiting_payment", 4: "applying", 5: "applied", 6: "failed", 7: "needs_attention", 8: "cancelled"},
	"opl.cloud.api.PlanChangeChargeStatusEnum":                          {1: "not_required", 2: "not_requested", 3: "requested", 4: "confirmed", 5: "rejected", 6: "unknown"},
	"opl.cloud.api.PlanChangeNextPeriodChargeStatusEnum":                {1: "not_required", 2: "not_requested", 3: "requested", 4: "confirmed", 5: "rejected", 6: "unknown"},
	"opl.cloud.api.PlanChangeObservationResultEnum":                     {1: "confirmed", 2: "rejected", 3: "unknown"},
	"opl.cloud.api.PlanChangeDeliveryOutcomeEnum":                       {1: "pending", 2: "applied", 3: "failed", 4: "unknown"},
	"opl.cloud.api.PlanChangeResourceOutcomeEnum":                       {1: "unchanged", 2: "target_confirmed", 3: "restored", 4: "irreversible_residual", 5: "unknown"},
	"opl.cloud.api.PlanChangeRuntimeReadbackRequirementEnum":            {1: "required", 2: "not_applicable"},
	"opl.cloud.api.PlanChangeCurrentRequirementValidationEnum":          {1: "valid", 2: "at_risk", 3: "not_checked"},
	"opl.cloud.api.PlanChangeEvidenceKindEnum":                          {1: "upgrade_immediate", 2: "downgrade_next_period"},
	"opl.cloud.api.PlanChangeEvidencePolicyVersionEnum":                 {1: "workspace-plan-change-v1"},
	"opl.cloud.api.PlanChangeEvidenceOutcomeEnum":                       {1: "scheduled", 2: "applied", 3: "failed", 4: "needs_attention", 5: "cancelled"},
	"opl.cloud.api.PlanChangeEvidenceDeliveryOutcomeEnum":               {1: "pending", 2: "applied", 3: "failed", 4: "unknown"},
	"opl.cloud.api.PlanChangeEvidenceResourceOutcomeEnum":               {1: "unchanged", 2: "target_confirmed", 3: "restored", 4: "irreversible_residual", 5: "unknown"},
	"opl.cloud.api.PlanChangeEvidenceRuntimeReadbackRequirementEnum":    {1: "required", 2: "not_applicable"},
	"opl.cloud.api.SupplementalRefundEvidencePurposeEnum":               {1: "upgrade_failure_full", 2: "supplement_delete_unused", 3: "next_period_plan_failure_full"},
	"opl.cloud.api.SupplementalRefundEvidencePolicyVersionEnum":         {1: "workspace-plan-change-v1"},
}

var required = map[protoreflect.Name]map[string]bool{
	"FieldError":                                {"field": true, "code": true, "message": true},
	"Error":                                     {"code": true, "message": true, "requestId": true},
	"Operation":                                 {"operationId": true, "owner": true, "kind": true, "resourceId": true, "status": true, "stage": true, "requestId": true, "createdAt": true, "updatedAt": true},
	"LoginContext":                              {"csrfToken": true, "expiresAt": true},
	"LoginRequest":                              {"username": true, "password": true},
	"Session":                                   {"actorId": true, "displayName": true, "permissions": true, "csrfToken": true, "expiresAt": true},
	"Tenant":                                    {"id": true, "name": true, "status": true, "assetCustodyStatus": true, "createdAt": true, "updatedAt": true},
	"CreateTenantRequest":                       {"name": true, "billingSub2apiUserId": true, "ownerGatewaySubjectId": true},
	"BindTenantWalletRequest":                   {"billingSub2apiUserId": true, "expectedBindingVersion": true},
	"Member":                                    {"id": true, "actorId": true, "displayName": true, "role": true, "status": true, "createdAt": true},
	"Invitation":                                {"id": true, "inviteeGatewaySubjectId": true, "role": true, "status": true, "expiresAt": true, "createdAt": true},
	"InviteMemberRequest":                       {"inviteeGatewaySubjectId": true, "role": true},
	"UpdateMemberRoleRequest":                   {"role": true},
	"TenantActionRequest":                       {"reason": true},
	"DeleteTenantRequest":                       {"confirmationName": true, "reason": true},
	"AssetCustody":                              {"tenantId": true, "status": true, "packageCount": true, "buildCount": true, "workspaceDeletionOperationIds": true},
	"Namespace":                                 {"id": true, "name": true, "isDefault": true, "status": true, "createdAt": true},
	"NamespaceWriteRequest":                     {"name": true},
	"Package":                                   {"id": true, "namespaceId": true, "name": true, "description": true, "visibility": true, "status": true, "createdAt": true, "updatedAt": true},
	"CreatePackageRequest":                      {"namespaceId": true, "name": true, "description": true},
	"UpdatePackageRequest":                      {"namespaceId": true, "name": true, "description": true},
	"PublishPackageRequest":                     {"admissionReceiptId": true},
	"PackageVersion":                            {"id": true, "packageId": true, "versionLabel": true, "status": true, "sha256": true, "sizeBytes": true, "createdAt": true},
	"CreateUploadRequest":                       {"versionLabel": true, "fileName": true, "sizeBytes": true, "sha256": true},
	"UploadPart":                                {"partNumber": true, "etag": true, "sizeBytes": true, "sha256": true},
	"UploadSession":                             {"id": true, "packageVersionId": true, "status": true, "sizeBytes": true, "sha256": true, "partSizeBytes": true, "completedParts": true, "expiresAt": true},
	"CreateUploadPartRequest":                   {"partNumber": true, "sizeBytes": true, "sha256": true},
	"UploadPartAuthorization":                   {"uploadId": true, "partNumber": true, "method": true, "url": true, "contentType": true, "requiredChecksumHeaderName": true, "requiredChecksumHeaderValue": true, "expiresAt": true},
	"CompleteUploadRequest":                     {"parts": true},
	"ModelRequirement":                          {"slot": true, "required": true, "capability": true, "allowedModelIds": true},
	"DataCompatibility":                         {"dataSchemaVersion": true, "compatibleFromVersions": true, "rollbackSafe": true, "migrationRequired": true},
	"CapabilityVersion":                         {"id": true, "versionLabel": true, "artifactDigest": true, "status": true, "modelRequirements": true, "dataCompatibility": true, "referenceCount": true, "createdAt": true, "provenance": true, "artifact": true, "deploymentDescriptor": true, "deploymentDescriptorDigest": true, "deploymentDescriptorObjectRef": true},
	"BuildJob":                                  {"id": true, "operationId": true, "packageVersionId": true, "runtimeVersionId": true, "webuiVersionId": true, "status": true, "stage": true, "createdAt": true, "updatedAt": true, "retryAllowed": true},
	"CreateBuildRequest":                        {"packageVersionId": true, "webuiVersionId": true},
	"BuildLog":                                  {"id": true, "buildJobId": true, "sequence": true, "stage": true, "level": true, "message": true, "createdAt": true},
	"RuntimeVersion":                            {"id": true, "name": true, "versionLabel": true, "artifactDigest": true, "status": true, "runtimeAbiVersion": true, "packageFormatVersions": true, "defaultForNewBuilds": true, "admissionReceiptId": true, "createdAt": true, "publisherNamespaceId": true, "publisherContractDigest": true, "publisherContract": true, "publisherContractObjectRef": true},
	"WebuiVersion":                              {"id": true, "name": true, "versionLabel": true, "artifactDigest": true, "status": true, "runtimeAbiVersions": true, "uiProtocolVersion": true, "admissionReceiptId": true, "createdAt": true, "publisherNamespaceId": true, "publisherContractDigest": true, "publisherContract": true, "publisherContractObjectRef": true},
	"RegisterRuntimeVersionRequest":             {"name": true, "versionLabel": true, "publisherNamespaceId": true, "publisherContract": true, "admissionReceiptId": true},
	"RegisterWebuiVersionRequest":               {"name": true, "versionLabel": true, "publisherNamespaceId": true, "publisherContract": true, "admissionReceiptId": true},
	"CatalogStatusRequest":                      {"status": true, "reason": true},
	"ComputePlan":                               {"id": true, "name": true, "vcpus": true, "memoryMiB": true, "availability": true, "billingMode": true, "providerCapabilityVersion": true, "validFrom": true, "createdAt": true},
	"StoragePlan":                               {"id": true, "name": true, "capacityGiB": true, "availability": true, "billingMode": true, "shrinkSupported": true, "validFrom": true, "createdAt": true},
	"CreateComputePlanRequest":                  {"name": true, "vcpus": true, "memoryMiB": true, "providerProfileId": true, "providerSkuId": true, "providerCapabilityVersion": true, "validFrom": true},
	"CreateStoragePlanRequest":                  {"name": true, "capacityGiB": true, "providerProfileId": true, "providerSkuId": true, "shrinkSupported": true, "validFrom": true},
	"PlanAvailabilityRequest":                   {"availability": true, "reason": true},
	"PricePolicyVersion":                        {"id": true, "versionLabel": true, "currency": true, "periodMonths": true, "computeMonthlyUSDMicros": true, "storageMonthlyUSDMicros": true, "productMonthlyUSDMicros": true, "validFrom": true, "createdAt": true, "computePlanId": true, "storagePlanId": true, "renewalPolicy": true, "planChangePolicyVersion": true, "planChangePolicy": true},
	"CreatePricePolicyRequest":                  {"versionLabel": true, "periodMonths": true, "computeMonthlyUSDMicros": true, "storageMonthlyUSDMicros": true, "productMonthlyUSDMicros": true, "validFrom": true, "computePlanId": true, "storagePlanId": true, "renewalPolicy": true, "planChangePolicyVersion": true},
	"RefundPolicyVersion":                       {"id": true, "versionLabel": true, "algorithm": true, "retentionPolicyVersionId": true, "customerTerms": true, "validFrom": true, "createdAt": true},
	"CreateRefundPolicyRequest":                 {"versionLabel": true, "algorithm": true, "retentionPolicyVersionId": true, "customerTerms": true, "validFrom": true},
	"RetentionPolicyVersion":                    {"id": true, "versionLabel": true, "workspaceDataDisposition": true, "packageHistoryDisposition": true, "buildHistoryDisposition": true, "tenantRestoreDays": true, "customerTerms": true, "createdAt": true},
	"CreateRetentionPolicyRequest":              {"versionLabel": true, "customerTerms": true},
	"Model":                                     {"id": true, "name": true, "capabilities": true, "available": true, "inputPricePerMillionTokensUSDMicros": true, "outputPricePerMillionTokensUSDMicros": true, "priceSource": true, "fetchedAt": true},
	"ModelSelection":                            {"slot": true, "modelId": true},
	"QuoteRequest":                              {"purpose": true, "computePlanId": true, "storagePlanId": true, "modelSelections": true, "periodMonths": true},
	"QuoteLine":                                 {"kind": true, "description": true, "quantity": true, "amountUSDMicros": true},
	"Quote":                                     {"id": true, "purpose": true, "computePlanId": true, "storagePlanId": true, "modelSelections": true, "periodMonths": true, "periodStart": true, "periodEnd": true, "pricePolicyVersionId": true, "refundPolicyVersionId": true, "retentionPolicyVersionId": true, "refundTerms": true, "retentionTerms": true, "expectedInterruption": true, "lineItems": true, "totalUSDMicros": true, "status": true, "expiresAt": true, "createdAt": true, "runtimeReadbackRequirement": true},
	"Workspace":                                 {"id": true, "name": true, "computePlanId": true, "storagePlanId": true, "status": true, "deliveryModel": true, "resourceReadiness": true, "applicationAvailability": true, "modelConfigurationVersion": true, "createdAt": true, "updatedAt": true, "version": true},
	"CreateWorkspaceRequest":                    {"name": true, "quoteId": true, "renewalMode": true},
	"WorkspaceAccess":                           {"workspaceId": true, "url": true, "authenticationMode": true, "expiresAt": true},
	"ModelConfiguration":                        {"workspaceId": true, "version": true, "selections": true, "status": true, "updatedAt": true},
	"UpdateWorkspaceModelsRequest":              {"expectedVersion": true, "selections": true},
	"Deployment":                                {"id": true, "workspaceId": true, "capabilityVersionId": true, "status": true, "dataCompatibility": true, "createdAt": true, "updatedAt": true},
	"UpdateWorkspaceVersionRequest":             {"capabilityVersionId": true, "expectedCurrentDeploymentId": true},
	"RollbackWorkspaceRequest":                  {"targetDeploymentId": true, "expectedCurrentDeploymentId": true},
	"ApplyQuoteRequest":                         {"quoteId": true},
	"DeleteWorkspaceRequest":                    {"confirmationName": true, "acknowledgeDataDestruction": true},
	"WorkspaceDeletion":                         {"workspaceId": true, "operationId": true, "resourceDeletionStatus": true, "dataDeletionStatus": true, "refundStatus": true, "updatedAt": true},
	"Subscription":                              {"id": true, "workspaceId": true, "currentPeriodStart": true, "currentPeriodEnd": true, "periodMonths": true, "status": true, "createdAt": true, "provenance": true, "renewalMode": true, "renewalSettingsVersion": true, "version": true},
	"WalletOperation":                           {"id": true, "kind": true, "amountUSDMicros": true, "status": true, "createdAt": true, "updatedAt": true},
	"Wallet":                                    {"source": true, "status": true, "balanceUSDMicros": true, "currency": true, "fetchedAt": true},
	"Usage":                                     {"id": true, "modelId": true, "periodStart": true, "periodEnd": true, "inputTokens": true, "outputTokens": true, "costUSDMicros": true, "source": true, "createdAt": true},
	"GatewayKey":                                {"id": true, "name": true, "fingerprint": true, "purpose": true, "status": true, "modelIds": true, "createdAt": true},
	"CreateGatewayKeyRequest":                   {"name": true, "modelIds": true},
	"GatewayKeySecret":                          {"key": true, "secret": true},
	"AuditEvent":                                {"id": true, "actorId": true, "action": true, "resourceId": true, "outcome": true, "requestId": true, "createdAt": true},
	"Receipt":                                   {"id": true, "kind": true, "owner": true, "outcome": true, "evidenceSummary": true, "createdAt": true},
	"ReconcileOperationRequest":                 {"reason": true},
	"AdminOperation":                            {"operation": true, "tenantId": true},
	"Qualification":                             {"id": true, "candidateSourceSha": true, "artifactDigest": true, "status": true, "createdAt": true},
	"MemberPage":                                {"items": true},
	"InvitationPage":                            {"items": true},
	"NamespacePage":                             {"items": true},
	"PackagePage":                               {"items": true},
	"PackageVersionPage":                        {"items": true},
	"CapabilityVersionPage":                     {"items": true},
	"BuildJobPage":                              {"items": true},
	"BuildLogPage":                              {"items": true},
	"RuntimeVersionPage":                        {"items": true},
	"WebuiVersionPage":                          {"items": true},
	"ComputePlanPage":                           {"items": true},
	"StoragePlanPage":                           {"items": true},
	"PricePolicyVersionPage":                    {"items": true},
	"RefundPolicyVersionPage":                   {"items": true},
	"RetentionPolicyVersionPage":                {"items": true},
	"ModelPage":                                 {"items": true},
	"WorkspacePage":                             {"items": true},
	"DeploymentPage":                            {"items": true},
	"WalletOperationPage":                       {"items": true},
	"UsagePage":                                 {"items": true},
	"GatewayKeyPage":                            {"items": true},
	"TenantPage":                                {"items": true},
	"AuditEventPage":                            {"items": true},
	"ReceiptPage":                               {"items": true},
	"AdminOperationPage":                        {"items": true},
	"QualificationPage":                         {"items": true},
	"AdoptWorkspaceRequest":                     {"capabilityVersionId": true, "expectedWorkspaceVersion": true, "modelSelections": true},
	"BuildRuntimePolicy":                        {"id": true, "runtimeVersionId": true, "policyVersion": true, "effectiveAt": true, "createdAt": true},
	"SetBuildRuntimePolicyRequest":              {"runtimeVersionId": true},
	"ImagePlatform":                             {"os": true, "architecture": true},
	"ArtifactReference":                         {"repository": true, "digest": true, "platform": true},
	"RecipeArtifact":                            {"repository": true, "digest": true, "mediaType": true, "dockerfilePath": true},
	"PackageBuildInput":                         {"contextName": true, "formatVersion": true, "sourceRoot": true, "targetPath": true, "uid": true, "gid": true},
	"WebuiBuildInput":                           {"contextName": true, "sourcePath": true, "targetPath": true, "uid": true, "gid": true},
	"BuildRecipeContract":                       {"version": true, "frontend": true, "recipe": true, "runtimeContextName": true, "packageInput": true, "webuiInput": true, "networkPolicy": true, "outputPlatform": true, "outputImageCommand": true},
	"BuildRecipeContractOutputImageCommand":     {"entrypoint": true, "cmd": true},
	"ModelConfigurationContract":                {"protocol": true, "portName": true, "applyPath": true, "readbackPath": true, "requestFields": true, "readbackFields": true, "authorizationSecretInputName": true},
	"DataUpgradeContract":                       {"mode": true, "compatibleFromSchemaVersions": true, "backupRequired": true},
	"DataRollbackContract":                      {"safe": true, "compatibleSchemaVersions": true},
	"DataContract":                              {"schemaVersion": true, "upgrade": true, "rollback": true, "mountPolicies": true},
	"RuntimePublisherContract":                  {"schemaVersion": true, "publisherNamespaceId": true, "image": true, "kind": true, "runtimeAbiVersion": true, "packageFormatVersions": true, "buildRecipe": true, "modelConfiguration": true, "applicationAccess": true, "data": true, "applicationRevisionTemplate": true, "packageFormatContracts": true},
	"WebuiPublisherContract":                    {"schemaVersion": true, "publisherNamespaceId": true, "image": true, "kind": true, "runtimeAbiVersions": true, "uiProtocolVersion": true, "integrationMode": true, "staticRoot": true, "entryFile": true, "assetBasePath": true, "apiBasePath": true, "authenticationProtocol": true, "supportsSse": true, "supportsWebsocket": true},
	"PublisherContractReference":                {"publisherNamespaceId": true, "versionId": true, "kind": true, "descriptorDigest": true, "descriptorObjectRef": true},
	"DeploymentDescriptor":                      {"schemaVersion": true, "artifact": true, "provenance": true, "applicationRevision": true},
	"PublisherNamespace":                        {"id": true, "name": true, "kind": true, "registryId": true, "repositoryPrefix": true, "admissionReceiptId": true, "status": true, "createdAt": true},
	"CreatePublisherNamespaceRequest":           {"name": true, "kind": true, "registryId": true, "repositoryPrefix": true, "admissionReceiptId": true},
	"RevokePublisherNamespaceRequest":           {"reason": true},
	"PublisherNamespacePage":                    {"items": true},
	"ReenableTenantRequest":                     {"reason": true},
	"RenewalPolicy":                             {"version": true, "trigger": true, "effectiveStart": true, "months": true, "usesAcceptedPriceSnapshot": true},
	"WorkspaceApplicationCredential":            {"name": true, "kind": true, "target": true},
	"WorkspaceApplicationPort":                  {"name": true, "port": true, "protocol": true},
	"WorkspaceApplicationHealthCheck":           {"port": true, "path": true},
	"WorkspaceApplicationMount":                 {"name": true, "mountPath": true},
	"WorkspaceApplicationSecretInput":           {"name": true},
	"WorkspaceApplicationConfigInput":           {"name": true, "target": true},
	"WorkspaceApplicationDependencyHealthCheck": {"type": true, "port": true},
	"WorkspaceApplicationDependency":            {"name": true, "image": true},
	"WorkspaceApplicationRevision":              {"schemaVersion": true, "applicationId": true, "version": true, "platform": true, "image": true, "exposurePolicy": true},
	"DataMountPolicy":                           {"mountName": true, "concurrentWritersSupported": true},
	"ApplicationOwnedAccessContract":            {"mode": true, "loginPath": true, "logoutPath": true},
	"CloudPrivateAccessContract":                {"mode": true, "entryContract": true, "admissionReceiptId": true},
	"AnonymousAccessContract":                   {"mode": true},
	"CreditSource":                              {"originalWalletOperationId": true, "originalSubscriptionPeriodId": true, "policyVersionId": true, "creditReceiptId": true, "amountUSDMicros": true},
	"TenantWorkspaceAction":                     {"workspaceId": true, "action": true, "operationId": true, "operationOwner": true, "status": true},
	"TenantWorkspaceSkip":                       {"workspaceId": true, "reason": true},
	"TenantLifecycleProgress":                   {"tenantId": true, "operation": true, "accessStatus": true, "workspaceActions": true, "skipped": true},
	"UpdateRenewalSettingsRequest":              {"renewalMode": true, "expectedRenewalSettingsVersion": true},
	"PackageFormatContractReference":            {"owner": true, "formatVersion": true, "schemaObjectRef": true, "schemaDigest": true, "validatorArtifact": true, "admissionReceiptId": true},
	"WorkspaceApplicationCredentials":           {"workspaceId": true, "runtimeInstanceId": true, "username": true, "password": true},
	"UpgradePlanRules":                          {"kind": true, "effectiveWhen": true, "preservePaidPeriod": true, "oldPriceSource": true, "chargeClock": true, "timeUnit": true, "chargeRounding": true, "zeroCharge": true, "knownFailureCompensation": true, "unknownOutcome": true, "irreversibleResidualCostOwner": true, "supplementDeleteRefund": true},
	"DowngradePlanRules":                        {"kind": true, "plannedBoundary": true, "currentPeriodRefund": true, "nextPeriodPrice": true, "requiresConfirmedNextPeriodPayment": true, "cancelBefore": true, "earlyPaidChange": true, "manualUnpaidBoundary": true, "knownFailureCompensation": true, "fallback": true},
	"PlanChangePolicy":                          {"version": true, "approvalStatus": true, "upgrade": true, "downgrade": true, "classification": true, "mixedOrIncomparableTransition": true, "noOpTransition": true, "storageShrink": true, "concurrency": true, "cancelAndReplace": true, "baseRefundPolicy": true, "providerExecutionPlan": true},
	"UpgradeProration":                          {"periodMilliseconds": true, "remainingMilliseconds": true, "priceDeltaUSDMicros": true, "rounding": true},
	"NextPeriodPlanQuote":                       {"periodStart": true, "periodEnd": true, "totalUSDMicros": true, "pricePolicyVersionId": true},
	"PlanChangeCalculation":                     {"policyVersion": true, "kind": true, "transitionId": true, "sourceSubscriptionId": true, "sourceSubscriptionVersion": true, "sourcePeriodId": true, "sourceComputePlanId": true, "sourceStoragePlanId": true, "targetComputePlanId": true, "targetStoragePlanId": true, "sourcePricePolicyVersionId": true, "targetPricePolicyVersionId": true, "sourceMonthlyUSDMicros": true, "targetMonthlyUSDMicros": true, "quoteAt": true, "periodStart": true, "periodEnd": true, "chargeUSDMicros": true, "plannedEffectiveAt": true, "executionPlanId": true, "executionPlanDigest": true, "quoteAtMilliseconds": true, "periodStartMilliseconds": true, "periodEndMilliseconds": true, "sourceFinancialSnapshotDigest": true},
	"PlanChange":                                {"id": true, "workspaceId": true, "kind": true, "status": true, "sourceComputePlanId": true, "sourceStoragePlanId": true, "targetComputePlanId": true, "targetStoragePlanId": true, "sourcePricePolicyVersionId": true, "targetPricePolicyVersionId": true, "sourceSubscriptionId": true, "sourceSubscriptionVersion": true, "sourcePeriodId": true, "sourceMonthlyUSDMicros": true, "targetMonthlyUSDMicros": true, "quoteId": true, "policyVersion": true, "quoteAt": true, "periodStart": true, "periodEnd": true, "chargeUSDMicros": true, "plannedEffectiveAt": true, "operationId": true, "chargeStatus": true, "refundOperationIds": true, "scheduleVersion": true, "observationResult": true, "cancellable": true, "createdAt": true, "updatedAt": true, "deliveryOutcome": true, "resourceOutcome": true, "runtimeReadbackRequirement": true, "currentRequirementValidation": true, "executionPlanId": true, "executionPlanDigest": true, "quoteAtMilliseconds": true, "periodStartMilliseconds": true, "periodEndMilliseconds": true, "sourceFinancialSnapshotDigest": true},
	"PlanChangePage":                            {"items": true},
	"CancelPlanChangeRequest":                   {"expectedScheduleVersion": true, "reason": true},
	"PlanChangeEvidence":                        {"schemaVersion": true, "planChangeId": true, "workspaceId": true, "kind": true, "policyVersion": true, "quoteId": true, "sourceSubscriptionId": true, "sourceSubscriptionVersion": true, "sourcePeriodId": true, "sourceComputePlanId": true, "sourceStoragePlanId": true, "targetComputePlanId": true, "targetStoragePlanId": true, "sourcePricePolicyVersionId": true, "targetPricePolicyVersionId": true, "quoteAt": true, "periodStart": true, "periodEnd": true, "chargeUSDMicros": true, "outcome": true, "retainedIrreversibleResources": true, "deliveryOutcome": true, "resourceOutcome": true, "runtimeReadbackRequirement": true, "quoteAtMilliseconds": true, "periodStartMilliseconds": true, "periodEndMilliseconds": true, "sourceFinancialSnapshotDigest": true},
	"SupplementalRefundEvidence":                {"schemaVersion": true, "purpose": true, "workspaceId": true, "planChangeId": true, "originalChargeOperationId": true, "originalChargeReceiptId": true, "originalConfirmedUSDMicros": true, "requestedRefundUSDMicros": true, "policyVersion": true, "coverageStart": true, "coverageEnd": true, "coverageStartMilliseconds": true, "coverageEndMilliseconds": true},
}
