// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccountID, v))
}

// OwnerAccountID applies equality check predicate on the "owner_account_id" field. It's identical to OwnerAccountIDEQ.
func OwnerAccountID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldOwnerAccountID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldOwnerUserID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldURL, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldState, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldStatus, v))
}

// PurchaseReceiptID applies equality check predicate on the "purchase_receipt_id" field. It's identical to PurchaseReceiptIDEQ.
func PurchaseReceiptID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPurchaseReceiptID, v))
}

// BillingStateJSON applies equality check predicate on the "billing_state_json" field. It's identical to BillingStateJSONEQ.
func BillingStateJSON(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldBillingStateJSON, v))
}

// StorageID applies equality check predicate on the "storage_id" field. It's identical to StorageIDEQ.
func StorageID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldStorageID, v))
}

// CurrentComputeAllocationID applies equality check predicate on the "current_compute_allocation_id" field. It's identical to CurrentComputeAllocationIDEQ.
func CurrentComputeAllocationID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCurrentComputeAllocationID, v))
}

// CurrentAttachmentID applies equality check predicate on the "current_attachment_id" field. It's identical to CurrentAttachmentIDEQ.
func CurrentAttachmentID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCurrentAttachmentID, v))
}

// RuntimeID applies equality check predicate on the "runtime_id" field. It's identical to RuntimeIDEQ.
func RuntimeID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRuntimeID, v))
}

// RuntimeServiceName applies equality check predicate on the "runtime_service_name" field. It's identical to RuntimeServiceNameEQ.
func RuntimeServiceName(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameRoot applies equality check predicate on the "runtime_service_name_root" field. It's identical to RuntimeServiceNameRootEQ.
func RuntimeServiceNameRoot(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRuntimeServiceNameRoot, v))
}

// ServiceName applies equality check predicate on the "service_name" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldServiceName, v))
}

// WorkspaceAPIKeyID applies equality check predicate on the "workspace_api_key_id" field. It's identical to WorkspaceAPIKeyIDEQ.
func WorkspaceAPIKeyID(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldWorkspaceAPIKeyID, v))
}

// AccessTokenStatus applies equality check predicate on the "access_token_status" field. It's identical to AccessTokenStatusEQ.
func AccessTokenStatus(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessTokenStatus, v))
}

// AccessAccount applies equality check predicate on the "access_account" field. It's identical to AccessAccountEQ.
func AccessAccount(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessAccount, v))
}

// AccessUsername applies equality check predicate on the "access_username" field. It's identical to AccessUsernameEQ.
func AccessUsername(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessUsername, v))
}

// CredentialStatus applies equality check predicate on the "credential_status" field. It's identical to CredentialStatusEQ.
func CredentialStatus(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCredentialStatus, v))
}

// CredentialVersion applies equality check predicate on the "credential_version" field. It's identical to CredentialVersionEQ.
func CredentialVersion(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCredentialVersion, v))
}

// CredentialSecretRef applies equality check predicate on the "credential_secret_ref" field. It's identical to CredentialSecretRefEQ.
func CredentialSecretRef(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCredentialSecretRef, v))
}

// AccessRequiresLogin applies equality check predicate on the "access_requires_login" field. It's identical to AccessRequiresLoginEQ.
func AccessRequiresLogin(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessRequiresLogin, v))
}

// VerificationSlotID applies equality check predicate on the "verification_slot_id" field. It's identical to VerificationSlotIDEQ.
func VerificationSlotID(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldVerificationSlotID, v))
}

// CustomerProduct applies equality check predicate on the "customer_product" field. It's identical to CustomerProductEQ.
func CustomerProduct(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCustomerProduct, v))
}

// ApplicationBinding applies equality check predicate on the "application_binding" field. It's identical to ApplicationBindingEQ.
func ApplicationBinding(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldApplicationBinding, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldAccountID, v))
}

// OwnerAccountIDEQ applies the EQ predicate on the "owner_account_id" field.
func OwnerAccountIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDNEQ applies the NEQ predicate on the "owner_account_id" field.
func OwnerAccountIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDIn applies the In predicate on the "owner_account_id" field.
func OwnerAccountIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDNotIn applies the NotIn predicate on the "owner_account_id" field.
func OwnerAccountIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDGT applies the GT predicate on the "owner_account_id" field.
func OwnerAccountIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldOwnerAccountID, v))
}

// OwnerAccountIDGTE applies the GTE predicate on the "owner_account_id" field.
func OwnerAccountIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldOwnerAccountID, v))
}

// OwnerAccountIDLT applies the LT predicate on the "owner_account_id" field.
func OwnerAccountIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldOwnerAccountID, v))
}

// OwnerAccountIDLTE applies the LTE predicate on the "owner_account_id" field.
func OwnerAccountIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldOwnerAccountID, v))
}

// OwnerAccountIDContains applies the Contains predicate on the "owner_account_id" field.
func OwnerAccountIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldOwnerAccountID, v))
}

// OwnerAccountIDHasPrefix applies the HasPrefix predicate on the "owner_account_id" field.
func OwnerAccountIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldOwnerAccountID, v))
}

// OwnerAccountIDHasSuffix applies the HasSuffix predicate on the "owner_account_id" field.
func OwnerAccountIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldOwnerAccountID, v))
}

// OwnerAccountIDEqualFold applies the EqualFold predicate on the "owner_account_id" field.
func OwnerAccountIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldOwnerAccountID, v))
}

// OwnerAccountIDContainsFold applies the ContainsFold predicate on the "owner_account_id" field.
func OwnerAccountIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldOwnerAccountID, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldOwnerUserID, v))
}

// OwnerUserIDContains applies the Contains predicate on the "owner_user_id" field.
func OwnerUserIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldOwnerUserID, v))
}

// OwnerUserIDHasPrefix applies the HasPrefix predicate on the "owner_user_id" field.
func OwnerUserIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldOwnerUserID, v))
}

// OwnerUserIDHasSuffix applies the HasSuffix predicate on the "owner_user_id" field.
func OwnerUserIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldOwnerUserID, v))
}

// OwnerUserIDEqualFold applies the EqualFold predicate on the "owner_user_id" field.
func OwnerUserIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldOwnerUserID, v))
}

// OwnerUserIDContainsFold applies the ContainsFold predicate on the "owner_user_id" field.
func OwnerUserIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldOwnerUserID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldName, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldURL, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldState, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldStatus, v))
}

// PurchaseReceiptIDEQ applies the EQ predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDNEQ applies the NEQ predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDIn applies the In predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldPurchaseReceiptID, vs...))
}

// PurchaseReceiptIDNotIn applies the NotIn predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldPurchaseReceiptID, vs...))
}

// PurchaseReceiptIDGT applies the GT predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDGTE applies the GTE predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDLT applies the LT predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDLTE applies the LTE predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDContains applies the Contains predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDHasPrefix applies the HasPrefix predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDHasSuffix applies the HasSuffix predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDEqualFold applies the EqualFold predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldPurchaseReceiptID, v))
}

// PurchaseReceiptIDContainsFold applies the ContainsFold predicate on the "purchase_receipt_id" field.
func PurchaseReceiptIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldPurchaseReceiptID, v))
}

// BillingStateJSONEQ applies the EQ predicate on the "billing_state_json" field.
func BillingStateJSONEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldBillingStateJSON, v))
}

// BillingStateJSONNEQ applies the NEQ predicate on the "billing_state_json" field.
func BillingStateJSONNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldBillingStateJSON, v))
}

// BillingStateJSONIn applies the In predicate on the "billing_state_json" field.
func BillingStateJSONIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldBillingStateJSON, vs...))
}

// BillingStateJSONNotIn applies the NotIn predicate on the "billing_state_json" field.
func BillingStateJSONNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldBillingStateJSON, vs...))
}

// BillingStateJSONGT applies the GT predicate on the "billing_state_json" field.
func BillingStateJSONGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldBillingStateJSON, v))
}

// BillingStateJSONGTE applies the GTE predicate on the "billing_state_json" field.
func BillingStateJSONGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldBillingStateJSON, v))
}

// BillingStateJSONLT applies the LT predicate on the "billing_state_json" field.
func BillingStateJSONLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldBillingStateJSON, v))
}

// BillingStateJSONLTE applies the LTE predicate on the "billing_state_json" field.
func BillingStateJSONLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldBillingStateJSON, v))
}

// BillingStateJSONContains applies the Contains predicate on the "billing_state_json" field.
func BillingStateJSONContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldBillingStateJSON, v))
}

// BillingStateJSONHasPrefix applies the HasPrefix predicate on the "billing_state_json" field.
func BillingStateJSONHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldBillingStateJSON, v))
}

// BillingStateJSONHasSuffix applies the HasSuffix predicate on the "billing_state_json" field.
func BillingStateJSONHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldBillingStateJSON, v))
}

// BillingStateJSONEqualFold applies the EqualFold predicate on the "billing_state_json" field.
func BillingStateJSONEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldBillingStateJSON, v))
}

// BillingStateJSONContainsFold applies the ContainsFold predicate on the "billing_state_json" field.
func BillingStateJSONContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldBillingStateJSON, v))
}

// StorageIDEQ applies the EQ predicate on the "storage_id" field.
func StorageIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldStorageID, v))
}

// StorageIDNEQ applies the NEQ predicate on the "storage_id" field.
func StorageIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldStorageID, v))
}

// StorageIDIn applies the In predicate on the "storage_id" field.
func StorageIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldStorageID, vs...))
}

// StorageIDNotIn applies the NotIn predicate on the "storage_id" field.
func StorageIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldStorageID, vs...))
}

// StorageIDGT applies the GT predicate on the "storage_id" field.
func StorageIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldStorageID, v))
}

// StorageIDGTE applies the GTE predicate on the "storage_id" field.
func StorageIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldStorageID, v))
}

// StorageIDLT applies the LT predicate on the "storage_id" field.
func StorageIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldStorageID, v))
}

// StorageIDLTE applies the LTE predicate on the "storage_id" field.
func StorageIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldStorageID, v))
}

// StorageIDContains applies the Contains predicate on the "storage_id" field.
func StorageIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldStorageID, v))
}

// StorageIDHasPrefix applies the HasPrefix predicate on the "storage_id" field.
func StorageIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldStorageID, v))
}

// StorageIDHasSuffix applies the HasSuffix predicate on the "storage_id" field.
func StorageIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldStorageID, v))
}

// StorageIDEqualFold applies the EqualFold predicate on the "storage_id" field.
func StorageIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldStorageID, v))
}

// StorageIDContainsFold applies the ContainsFold predicate on the "storage_id" field.
func StorageIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldStorageID, v))
}

// CurrentComputeAllocationIDEQ applies the EQ predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDNEQ applies the NEQ predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDIn applies the In predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCurrentComputeAllocationID, vs...))
}

// CurrentComputeAllocationIDNotIn applies the NotIn predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCurrentComputeAllocationID, vs...))
}

// CurrentComputeAllocationIDGT applies the GT predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDGTE applies the GTE predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDLT applies the LT predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDLTE applies the LTE predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDContains applies the Contains predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDHasPrefix applies the HasPrefix predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDHasSuffix applies the HasSuffix predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDEqualFold applies the EqualFold predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldCurrentComputeAllocationID, v))
}

// CurrentComputeAllocationIDContainsFold applies the ContainsFold predicate on the "current_compute_allocation_id" field.
func CurrentComputeAllocationIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldCurrentComputeAllocationID, v))
}

// CurrentAttachmentIDEQ applies the EQ predicate on the "current_attachment_id" field.
func CurrentAttachmentIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDNEQ applies the NEQ predicate on the "current_attachment_id" field.
func CurrentAttachmentIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDIn applies the In predicate on the "current_attachment_id" field.
func CurrentAttachmentIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCurrentAttachmentID, vs...))
}

// CurrentAttachmentIDNotIn applies the NotIn predicate on the "current_attachment_id" field.
func CurrentAttachmentIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCurrentAttachmentID, vs...))
}

// CurrentAttachmentIDGT applies the GT predicate on the "current_attachment_id" field.
func CurrentAttachmentIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDGTE applies the GTE predicate on the "current_attachment_id" field.
func CurrentAttachmentIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDLT applies the LT predicate on the "current_attachment_id" field.
func CurrentAttachmentIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDLTE applies the LTE predicate on the "current_attachment_id" field.
func CurrentAttachmentIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDContains applies the Contains predicate on the "current_attachment_id" field.
func CurrentAttachmentIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDHasPrefix applies the HasPrefix predicate on the "current_attachment_id" field.
func CurrentAttachmentIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDHasSuffix applies the HasSuffix predicate on the "current_attachment_id" field.
func CurrentAttachmentIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDEqualFold applies the EqualFold predicate on the "current_attachment_id" field.
func CurrentAttachmentIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldCurrentAttachmentID, v))
}

// CurrentAttachmentIDContainsFold applies the ContainsFold predicate on the "current_attachment_id" field.
func CurrentAttachmentIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldCurrentAttachmentID, v))
}

// RuntimeIDEQ applies the EQ predicate on the "runtime_id" field.
func RuntimeIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRuntimeID, v))
}

// RuntimeIDNEQ applies the NEQ predicate on the "runtime_id" field.
func RuntimeIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldRuntimeID, v))
}

// RuntimeIDIn applies the In predicate on the "runtime_id" field.
func RuntimeIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldRuntimeID, vs...))
}

// RuntimeIDNotIn applies the NotIn predicate on the "runtime_id" field.
func RuntimeIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldRuntimeID, vs...))
}

// RuntimeIDGT applies the GT predicate on the "runtime_id" field.
func RuntimeIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldRuntimeID, v))
}

// RuntimeIDGTE applies the GTE predicate on the "runtime_id" field.
func RuntimeIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldRuntimeID, v))
}

// RuntimeIDLT applies the LT predicate on the "runtime_id" field.
func RuntimeIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldRuntimeID, v))
}

// RuntimeIDLTE applies the LTE predicate on the "runtime_id" field.
func RuntimeIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldRuntimeID, v))
}

// RuntimeIDContains applies the Contains predicate on the "runtime_id" field.
func RuntimeIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldRuntimeID, v))
}

// RuntimeIDHasPrefix applies the HasPrefix predicate on the "runtime_id" field.
func RuntimeIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldRuntimeID, v))
}

// RuntimeIDHasSuffix applies the HasSuffix predicate on the "runtime_id" field.
func RuntimeIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldRuntimeID, v))
}

// RuntimeIDEqualFold applies the EqualFold predicate on the "runtime_id" field.
func RuntimeIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldRuntimeID, v))
}

// RuntimeIDContainsFold applies the ContainsFold predicate on the "runtime_id" field.
func RuntimeIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldRuntimeID, v))
}

// RuntimeServiceNameEQ applies the EQ predicate on the "runtime_service_name" field.
func RuntimeServiceNameEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameNEQ applies the NEQ predicate on the "runtime_service_name" field.
func RuntimeServiceNameNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameIn applies the In predicate on the "runtime_service_name" field.
func RuntimeServiceNameIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldRuntimeServiceName, vs...))
}

// RuntimeServiceNameNotIn applies the NotIn predicate on the "runtime_service_name" field.
func RuntimeServiceNameNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldRuntimeServiceName, vs...))
}

// RuntimeServiceNameGT applies the GT predicate on the "runtime_service_name" field.
func RuntimeServiceNameGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameGTE applies the GTE predicate on the "runtime_service_name" field.
func RuntimeServiceNameGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameLT applies the LT predicate on the "runtime_service_name" field.
func RuntimeServiceNameLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameLTE applies the LTE predicate on the "runtime_service_name" field.
func RuntimeServiceNameLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameContains applies the Contains predicate on the "runtime_service_name" field.
func RuntimeServiceNameContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameHasPrefix applies the HasPrefix predicate on the "runtime_service_name" field.
func RuntimeServiceNameHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameHasSuffix applies the HasSuffix predicate on the "runtime_service_name" field.
func RuntimeServiceNameHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameEqualFold applies the EqualFold predicate on the "runtime_service_name" field.
func RuntimeServiceNameEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameContainsFold applies the ContainsFold predicate on the "runtime_service_name" field.
func RuntimeServiceNameContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldRuntimeServiceName, v))
}

// RuntimeServiceNameRootEQ applies the EQ predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootNEQ applies the NEQ predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootIn applies the In predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldRuntimeServiceNameRoot, vs...))
}

// RuntimeServiceNameRootNotIn applies the NotIn predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldRuntimeServiceNameRoot, vs...))
}

// RuntimeServiceNameRootGT applies the GT predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootGTE applies the GTE predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootLT applies the LT predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootLTE applies the LTE predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootContains applies the Contains predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootHasPrefix applies the HasPrefix predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootHasSuffix applies the HasSuffix predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootEqualFold applies the EqualFold predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldRuntimeServiceNameRoot, v))
}

// RuntimeServiceNameRootContainsFold applies the ContainsFold predicate on the "runtime_service_name_root" field.
func RuntimeServiceNameRootContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldRuntimeServiceNameRoot, v))
}

// ServiceNameEQ applies the EQ predicate on the "service_name" field.
func ServiceNameEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "service_name" field.
func ServiceNameNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "service_name" field.
func ServiceNameIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "service_name" field.
func ServiceNameNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "service_name" field.
func ServiceNameGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "service_name" field.
func ServiceNameGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "service_name" field.
func ServiceNameLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "service_name" field.
func ServiceNameLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "service_name" field.
func ServiceNameContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "service_name" field.
func ServiceNameHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "service_name" field.
func ServiceNameHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "service_name" field.
func ServiceNameEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "service_name" field.
func ServiceNameContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldServiceName, v))
}

// WorkspaceAPIKeyIDEQ applies the EQ predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDEQ(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldWorkspaceAPIKeyID, v))
}

// WorkspaceAPIKeyIDNEQ applies the NEQ predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDNEQ(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldWorkspaceAPIKeyID, v))
}

// WorkspaceAPIKeyIDIn applies the In predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDIn(vs ...int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldWorkspaceAPIKeyID, vs...))
}

// WorkspaceAPIKeyIDNotIn applies the NotIn predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDNotIn(vs ...int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldWorkspaceAPIKeyID, vs...))
}

// WorkspaceAPIKeyIDGT applies the GT predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDGT(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldWorkspaceAPIKeyID, v))
}

// WorkspaceAPIKeyIDGTE applies the GTE predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDGTE(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldWorkspaceAPIKeyID, v))
}

// WorkspaceAPIKeyIDLT applies the LT predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDLT(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldWorkspaceAPIKeyID, v))
}

// WorkspaceAPIKeyIDLTE applies the LTE predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDLTE(v int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldWorkspaceAPIKeyID, v))
}

// WorkspaceAPIKeyIDIsNil applies the IsNil predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDIsNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldIsNull(FieldWorkspaceAPIKeyID))
}

// WorkspaceAPIKeyIDNotNil applies the NotNil predicate on the "workspace_api_key_id" field.
func WorkspaceAPIKeyIDNotNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldNotNull(FieldWorkspaceAPIKeyID))
}

// AccessTokenStatusEQ applies the EQ predicate on the "access_token_status" field.
func AccessTokenStatusEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessTokenStatus, v))
}

// AccessTokenStatusNEQ applies the NEQ predicate on the "access_token_status" field.
func AccessTokenStatusNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldAccessTokenStatus, v))
}

// AccessTokenStatusIn applies the In predicate on the "access_token_status" field.
func AccessTokenStatusIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldAccessTokenStatus, vs...))
}

// AccessTokenStatusNotIn applies the NotIn predicate on the "access_token_status" field.
func AccessTokenStatusNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldAccessTokenStatus, vs...))
}

// AccessTokenStatusGT applies the GT predicate on the "access_token_status" field.
func AccessTokenStatusGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldAccessTokenStatus, v))
}

// AccessTokenStatusGTE applies the GTE predicate on the "access_token_status" field.
func AccessTokenStatusGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldAccessTokenStatus, v))
}

// AccessTokenStatusLT applies the LT predicate on the "access_token_status" field.
func AccessTokenStatusLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldAccessTokenStatus, v))
}

// AccessTokenStatusLTE applies the LTE predicate on the "access_token_status" field.
func AccessTokenStatusLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldAccessTokenStatus, v))
}

// AccessTokenStatusContains applies the Contains predicate on the "access_token_status" field.
func AccessTokenStatusContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldAccessTokenStatus, v))
}

// AccessTokenStatusHasPrefix applies the HasPrefix predicate on the "access_token_status" field.
func AccessTokenStatusHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldAccessTokenStatus, v))
}

// AccessTokenStatusHasSuffix applies the HasSuffix predicate on the "access_token_status" field.
func AccessTokenStatusHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldAccessTokenStatus, v))
}

// AccessTokenStatusEqualFold applies the EqualFold predicate on the "access_token_status" field.
func AccessTokenStatusEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldAccessTokenStatus, v))
}

// AccessTokenStatusContainsFold applies the ContainsFold predicate on the "access_token_status" field.
func AccessTokenStatusContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldAccessTokenStatus, v))
}

// AccessAccountEQ applies the EQ predicate on the "access_account" field.
func AccessAccountEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessAccount, v))
}

// AccessAccountNEQ applies the NEQ predicate on the "access_account" field.
func AccessAccountNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldAccessAccount, v))
}

// AccessAccountIn applies the In predicate on the "access_account" field.
func AccessAccountIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldAccessAccount, vs...))
}

// AccessAccountNotIn applies the NotIn predicate on the "access_account" field.
func AccessAccountNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldAccessAccount, vs...))
}

// AccessAccountGT applies the GT predicate on the "access_account" field.
func AccessAccountGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldAccessAccount, v))
}

// AccessAccountGTE applies the GTE predicate on the "access_account" field.
func AccessAccountGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldAccessAccount, v))
}

// AccessAccountLT applies the LT predicate on the "access_account" field.
func AccessAccountLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldAccessAccount, v))
}

// AccessAccountLTE applies the LTE predicate on the "access_account" field.
func AccessAccountLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldAccessAccount, v))
}

// AccessAccountContains applies the Contains predicate on the "access_account" field.
func AccessAccountContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldAccessAccount, v))
}

// AccessAccountHasPrefix applies the HasPrefix predicate on the "access_account" field.
func AccessAccountHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldAccessAccount, v))
}

// AccessAccountHasSuffix applies the HasSuffix predicate on the "access_account" field.
func AccessAccountHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldAccessAccount, v))
}

// AccessAccountEqualFold applies the EqualFold predicate on the "access_account" field.
func AccessAccountEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldAccessAccount, v))
}

// AccessAccountContainsFold applies the ContainsFold predicate on the "access_account" field.
func AccessAccountContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldAccessAccount, v))
}

// AccessUsernameEQ applies the EQ predicate on the "access_username" field.
func AccessUsernameEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessUsername, v))
}

// AccessUsernameNEQ applies the NEQ predicate on the "access_username" field.
func AccessUsernameNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldAccessUsername, v))
}

// AccessUsernameIn applies the In predicate on the "access_username" field.
func AccessUsernameIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldAccessUsername, vs...))
}

// AccessUsernameNotIn applies the NotIn predicate on the "access_username" field.
func AccessUsernameNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldAccessUsername, vs...))
}

// AccessUsernameGT applies the GT predicate on the "access_username" field.
func AccessUsernameGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldAccessUsername, v))
}

// AccessUsernameGTE applies the GTE predicate on the "access_username" field.
func AccessUsernameGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldAccessUsername, v))
}

// AccessUsernameLT applies the LT predicate on the "access_username" field.
func AccessUsernameLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldAccessUsername, v))
}

// AccessUsernameLTE applies the LTE predicate on the "access_username" field.
func AccessUsernameLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldAccessUsername, v))
}

// AccessUsernameContains applies the Contains predicate on the "access_username" field.
func AccessUsernameContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldAccessUsername, v))
}

// AccessUsernameHasPrefix applies the HasPrefix predicate on the "access_username" field.
func AccessUsernameHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldAccessUsername, v))
}

// AccessUsernameHasSuffix applies the HasSuffix predicate on the "access_username" field.
func AccessUsernameHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldAccessUsername, v))
}

// AccessUsernameEqualFold applies the EqualFold predicate on the "access_username" field.
func AccessUsernameEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldAccessUsername, v))
}

// AccessUsernameContainsFold applies the ContainsFold predicate on the "access_username" field.
func AccessUsernameContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldAccessUsername, v))
}

// CredentialStatusEQ applies the EQ predicate on the "credential_status" field.
func CredentialStatusEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCredentialStatus, v))
}

// CredentialStatusNEQ applies the NEQ predicate on the "credential_status" field.
func CredentialStatusNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCredentialStatus, v))
}

// CredentialStatusIn applies the In predicate on the "credential_status" field.
func CredentialStatusIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCredentialStatus, vs...))
}

// CredentialStatusNotIn applies the NotIn predicate on the "credential_status" field.
func CredentialStatusNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCredentialStatus, vs...))
}

// CredentialStatusGT applies the GT predicate on the "credential_status" field.
func CredentialStatusGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCredentialStatus, v))
}

// CredentialStatusGTE applies the GTE predicate on the "credential_status" field.
func CredentialStatusGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCredentialStatus, v))
}

// CredentialStatusLT applies the LT predicate on the "credential_status" field.
func CredentialStatusLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCredentialStatus, v))
}

// CredentialStatusLTE applies the LTE predicate on the "credential_status" field.
func CredentialStatusLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCredentialStatus, v))
}

// CredentialStatusContains applies the Contains predicate on the "credential_status" field.
func CredentialStatusContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldCredentialStatus, v))
}

// CredentialStatusHasPrefix applies the HasPrefix predicate on the "credential_status" field.
func CredentialStatusHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldCredentialStatus, v))
}

// CredentialStatusHasSuffix applies the HasSuffix predicate on the "credential_status" field.
func CredentialStatusHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldCredentialStatus, v))
}

// CredentialStatusEqualFold applies the EqualFold predicate on the "credential_status" field.
func CredentialStatusEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldCredentialStatus, v))
}

// CredentialStatusContainsFold applies the ContainsFold predicate on the "credential_status" field.
func CredentialStatusContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldCredentialStatus, v))
}

// CredentialVersionEQ applies the EQ predicate on the "credential_version" field.
func CredentialVersionEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCredentialVersion, v))
}

// CredentialVersionNEQ applies the NEQ predicate on the "credential_version" field.
func CredentialVersionNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCredentialVersion, v))
}

// CredentialVersionIn applies the In predicate on the "credential_version" field.
func CredentialVersionIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCredentialVersion, vs...))
}

// CredentialVersionNotIn applies the NotIn predicate on the "credential_version" field.
func CredentialVersionNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCredentialVersion, vs...))
}

// CredentialVersionGT applies the GT predicate on the "credential_version" field.
func CredentialVersionGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCredentialVersion, v))
}

// CredentialVersionGTE applies the GTE predicate on the "credential_version" field.
func CredentialVersionGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCredentialVersion, v))
}

// CredentialVersionLT applies the LT predicate on the "credential_version" field.
func CredentialVersionLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCredentialVersion, v))
}

// CredentialVersionLTE applies the LTE predicate on the "credential_version" field.
func CredentialVersionLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCredentialVersion, v))
}

// CredentialVersionContains applies the Contains predicate on the "credential_version" field.
func CredentialVersionContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldCredentialVersion, v))
}

// CredentialVersionHasPrefix applies the HasPrefix predicate on the "credential_version" field.
func CredentialVersionHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldCredentialVersion, v))
}

// CredentialVersionHasSuffix applies the HasSuffix predicate on the "credential_version" field.
func CredentialVersionHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldCredentialVersion, v))
}

// CredentialVersionEqualFold applies the EqualFold predicate on the "credential_version" field.
func CredentialVersionEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldCredentialVersion, v))
}

// CredentialVersionContainsFold applies the ContainsFold predicate on the "credential_version" field.
func CredentialVersionContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldCredentialVersion, v))
}

// CredentialSecretRefEQ applies the EQ predicate on the "credential_secret_ref" field.
func CredentialSecretRefEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCredentialSecretRef, v))
}

// CredentialSecretRefNEQ applies the NEQ predicate on the "credential_secret_ref" field.
func CredentialSecretRefNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCredentialSecretRef, v))
}

// CredentialSecretRefIn applies the In predicate on the "credential_secret_ref" field.
func CredentialSecretRefIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCredentialSecretRef, vs...))
}

// CredentialSecretRefNotIn applies the NotIn predicate on the "credential_secret_ref" field.
func CredentialSecretRefNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCredentialSecretRef, vs...))
}

// CredentialSecretRefGT applies the GT predicate on the "credential_secret_ref" field.
func CredentialSecretRefGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCredentialSecretRef, v))
}

// CredentialSecretRefGTE applies the GTE predicate on the "credential_secret_ref" field.
func CredentialSecretRefGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCredentialSecretRef, v))
}

// CredentialSecretRefLT applies the LT predicate on the "credential_secret_ref" field.
func CredentialSecretRefLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCredentialSecretRef, v))
}

// CredentialSecretRefLTE applies the LTE predicate on the "credential_secret_ref" field.
func CredentialSecretRefLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCredentialSecretRef, v))
}

// CredentialSecretRefContains applies the Contains predicate on the "credential_secret_ref" field.
func CredentialSecretRefContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldCredentialSecretRef, v))
}

// CredentialSecretRefHasPrefix applies the HasPrefix predicate on the "credential_secret_ref" field.
func CredentialSecretRefHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldCredentialSecretRef, v))
}

// CredentialSecretRefHasSuffix applies the HasSuffix predicate on the "credential_secret_ref" field.
func CredentialSecretRefHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldCredentialSecretRef, v))
}

// CredentialSecretRefEqualFold applies the EqualFold predicate on the "credential_secret_ref" field.
func CredentialSecretRefEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldCredentialSecretRef, v))
}

// CredentialSecretRefContainsFold applies the ContainsFold predicate on the "credential_secret_ref" field.
func CredentialSecretRefContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldCredentialSecretRef, v))
}

// AccessRequiresLoginEQ applies the EQ predicate on the "access_requires_login" field.
func AccessRequiresLoginEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldAccessRequiresLogin, v))
}

// AccessRequiresLoginNEQ applies the NEQ predicate on the "access_requires_login" field.
func AccessRequiresLoginNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldAccessRequiresLogin, v))
}

// VerificationSlotIDEQ applies the EQ predicate on the "verification_slot_id" field.
func VerificationSlotIDEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldVerificationSlotID, v))
}

// VerificationSlotIDNEQ applies the NEQ predicate on the "verification_slot_id" field.
func VerificationSlotIDNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldVerificationSlotID, v))
}

// VerificationSlotIDIn applies the In predicate on the "verification_slot_id" field.
func VerificationSlotIDIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldVerificationSlotID, vs...))
}

// VerificationSlotIDNotIn applies the NotIn predicate on the "verification_slot_id" field.
func VerificationSlotIDNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldVerificationSlotID, vs...))
}

// VerificationSlotIDGT applies the GT predicate on the "verification_slot_id" field.
func VerificationSlotIDGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldVerificationSlotID, v))
}

// VerificationSlotIDGTE applies the GTE predicate on the "verification_slot_id" field.
func VerificationSlotIDGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldVerificationSlotID, v))
}

// VerificationSlotIDLT applies the LT predicate on the "verification_slot_id" field.
func VerificationSlotIDLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldVerificationSlotID, v))
}

// VerificationSlotIDLTE applies the LTE predicate on the "verification_slot_id" field.
func VerificationSlotIDLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldVerificationSlotID, v))
}

// VerificationSlotIDContains applies the Contains predicate on the "verification_slot_id" field.
func VerificationSlotIDContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldVerificationSlotID, v))
}

// VerificationSlotIDHasPrefix applies the HasPrefix predicate on the "verification_slot_id" field.
func VerificationSlotIDHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldVerificationSlotID, v))
}

// VerificationSlotIDHasSuffix applies the HasSuffix predicate on the "verification_slot_id" field.
func VerificationSlotIDHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldVerificationSlotID, v))
}

// VerificationSlotIDEqualFold applies the EqualFold predicate on the "verification_slot_id" field.
func VerificationSlotIDEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldVerificationSlotID, v))
}

// VerificationSlotIDContainsFold applies the ContainsFold predicate on the "verification_slot_id" field.
func VerificationSlotIDContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldVerificationSlotID, v))
}

// CustomerProductEQ applies the EQ predicate on the "customer_product" field.
func CustomerProductEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCustomerProduct, v))
}

// CustomerProductNEQ applies the NEQ predicate on the "customer_product" field.
func CustomerProductNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCustomerProduct, v))
}

// ApplicationBindingEQ applies the EQ predicate on the "application_binding" field.
func ApplicationBindingEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldApplicationBinding, v))
}

// ApplicationBindingNEQ applies the NEQ predicate on the "application_binding" field.
func ApplicationBindingNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldApplicationBinding, v))
}

// ApplicationBindingIn applies the In predicate on the "application_binding" field.
func ApplicationBindingIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldApplicationBinding, vs...))
}

// ApplicationBindingNotIn applies the NotIn predicate on the "application_binding" field.
func ApplicationBindingNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldApplicationBinding, vs...))
}

// ApplicationBindingGT applies the GT predicate on the "application_binding" field.
func ApplicationBindingGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldApplicationBinding, v))
}

// ApplicationBindingGTE applies the GTE predicate on the "application_binding" field.
func ApplicationBindingGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldApplicationBinding, v))
}

// ApplicationBindingLT applies the LT predicate on the "application_binding" field.
func ApplicationBindingLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldApplicationBinding, v))
}

// ApplicationBindingLTE applies the LTE predicate on the "application_binding" field.
func ApplicationBindingLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldApplicationBinding, v))
}

// ApplicationBindingContains applies the Contains predicate on the "application_binding" field.
func ApplicationBindingContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldApplicationBinding, v))
}

// ApplicationBindingHasPrefix applies the HasPrefix predicate on the "application_binding" field.
func ApplicationBindingHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldApplicationBinding, v))
}

// ApplicationBindingHasSuffix applies the HasSuffix predicate on the "application_binding" field.
func ApplicationBindingHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldApplicationBinding, v))
}

// ApplicationBindingEqualFold applies the EqualFold predicate on the "application_binding" field.
func ApplicationBindingEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldApplicationBinding, v))
}

// ApplicationBindingContainsFold applies the ContainsFold predicate on the "application_binding" field.
func ApplicationBindingContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldApplicationBinding, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.NotPredicates(p))
}
