// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ControlPlaneAccountsColumns holds the columns for the "control_plane_accounts" table.
	ControlPlaneAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "owner_user_id", Type: field.TypeString, Unique: true},
		{Name: "sub2api_user_id", Type: field.TypeInt64, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "workspace_purchase_enabled", Type: field.TypeBool, Default: false},
	}
	// ControlPlaneAccountsTable holds the schema information for the "control_plane_accounts" table.
	ControlPlaneAccountsTable = &schema.Table{
		Name:       "control_plane_accounts",
		Columns:    ControlPlaneAccountsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneAccountsColumns[0]},
	}
	// ControlPlaneAdminAuditEventsColumns holds the columns for the "control_plane_admin_audit_events" table.
	ControlPlaneAdminAuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "actor_user_id", Type: field.TypeString, Default: ""},
		{Name: "actor_role", Type: field.TypeString, Default: ""},
		{Name: "actor_account_id", Type: field.TypeString, Default: ""},
		{Name: "target_account_id", Type: field.TypeString, Default: ""},
		{Name: "action", Type: field.TypeString, Default: ""},
		{Name: "resource_kind", Type: field.TypeString, Default: ""},
		{Name: "resource_id", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "before_json", Type: field.TypeString, Default: ""},
		{Name: "after_json", Type: field.TypeString, Default: ""},
		{Name: "result", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneAdminAuditEventsTable holds the schema information for the "control_plane_admin_audit_events" table.
	ControlPlaneAdminAuditEventsTable = &schema.Table{
		Name:       "control_plane_admin_audit_events",
		Columns:    ControlPlaneAdminAuditEventsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneAdminAuditEventsColumns[0]},
	}
	// ControlPlaneAnnouncementsColumns holds the columns for the "control_plane_announcements" table.
	ControlPlaneAnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "draft"},
		{Name: "starts_at", Type: field.TypeString, Default: ""},
		{Name: "ends_at", Type: field.TypeString, Default: ""},
		{Name: "published_at", Type: field.TypeString, Default: ""},
		{Name: "created_by_user_id", Type: field.TypeString},
		{Name: "updated_by_user_id", Type: field.TypeString},
	}
	// ControlPlaneAnnouncementsTable holds the schema information for the "control_plane_announcements" table.
	ControlPlaneAnnouncementsTable = &schema.Table{
		Name:       "control_plane_announcements",
		Columns:    ControlPlaneAnnouncementsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneAnnouncementsColumns[0]},
	}
	// ControlPlaneAnnouncementReadsColumns holds the columns for the "control_plane_announcement_reads" table.
	ControlPlaneAnnouncementReadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "announcement_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "read_at", Type: field.TypeString},
	}
	// ControlPlaneAnnouncementReadsTable holds the schema information for the "control_plane_announcement_reads" table.
	ControlPlaneAnnouncementReadsTable = &schema.Table{
		Name:       "control_plane_announcement_reads",
		Columns:    ControlPlaneAnnouncementReadsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneAnnouncementReadsColumns[0]},
	}
	// ControlPlaneArchivedAdminAuditEventsColumns holds the columns for the "control_plane_archived_admin_audit_events" table.
	ControlPlaneArchivedAdminAuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "actor_user_id", Type: field.TypeString, Default: ""},
		{Name: "actor_role", Type: field.TypeString, Default: ""},
		{Name: "actor_account_id", Type: field.TypeString, Default: ""},
		{Name: "target_account_id", Type: field.TypeString, Default: ""},
		{Name: "action", Type: field.TypeString, Default: ""},
		{Name: "resource_kind", Type: field.TypeString, Default: ""},
		{Name: "resource_id", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "before_json", Type: field.TypeString, Default: ""},
		{Name: "after_json", Type: field.TypeString, Default: ""},
		{Name: "result", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneArchivedAdminAuditEventsTable holds the schema information for the "control_plane_archived_admin_audit_events" table.
	ControlPlaneArchivedAdminAuditEventsTable = &schema.Table{
		Name:       "control_plane_archived_admin_audit_events",
		Columns:    ControlPlaneArchivedAdminAuditEventsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneArchivedAdminAuditEventsColumns[0]},
	}
	// ControlPlaneAuthAttemptsColumns holds the columns for the "control_plane_auth_attempts" table.
	ControlPlaneAuthAttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "reason", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneAuthAttemptsTable holds the schema information for the "control_plane_auth_attempts" table.
	ControlPlaneAuthAttemptsTable = &schema.Table{
		Name:       "control_plane_auth_attempts",
		Columns:    ControlPlaneAuthAttemptsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneAuthAttemptsColumns[0]},
	}
	// ControlPlaneBillingReconciliationColumns holds the columns for the "control_plane_billing_reconciliation" table.
	ControlPlaneBillingReconciliationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "guard_status", Type: field.TypeString, Default: ""},
		{Name: "guard_reason", Type: field.TypeString, Default: ""},
		{Name: "message_author", Type: field.TypeString, Default: ""},
		{Name: "message_text", Type: field.TypeString, Default: ""},
		{Name: "message_created_at", Type: field.TypeString, Default: ""},
		{Name: "guard_block_new_workspaces", Type: field.TypeBool, Default: false},
		{Name: "reports", Type: field.TypeInt64, Default: 0},
	}
	// ControlPlaneBillingReconciliationTable holds the schema information for the "control_plane_billing_reconciliation" table.
	ControlPlaneBillingReconciliationTable = &schema.Table{
		Name:       "control_plane_billing_reconciliation",
		Columns:    ControlPlaneBillingReconciliationColumns,
		PrimaryKey: []*schema.Column{ControlPlaneBillingReconciliationColumns[0]},
	}
	// ControlPlaneComputeAllocationsColumns holds the columns for the "control_plane_compute_allocations" table.
	ControlPlaneComputeAllocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeString},
		{Name: "owner_user_id", Type: field.TypeString, Default: ""},
		{Name: "workspace_id", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "package_id", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "provider_resource_id", Type: field.TypeString, Default: ""},
		{Name: "provider_request_id", Type: field.TypeString, Default: ""},
		{Name: "operation_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "desired_status", Type: field.TypeString, Default: ""},
		{Name: "provider_status", Type: field.TypeString, Default: ""},
		{Name: "last_provider_sync_at", Type: field.TypeString, Default: ""},
		{Name: "last_provider_sync_error", Type: field.TypeString, Default: ""},
		{Name: "external_deleted_at", Type: field.TypeString, Default: ""},
		{Name: "billing_status", Type: field.TypeString, Default: ""},
		{Name: "pricing_version", Type: field.TypeString, Default: ""},
		{Name: "billing_operation_id", Type: field.TypeString, Default: ""},
		{Name: "billing_state_json", Type: field.TypeString, Default: "{}"},
		{Name: "evidence_id", Type: field.TypeString, Default: ""},
		{Name: "cvm_instance_id", Type: field.TypeString, Default: ""},
		{Name: "instance_id", Type: field.TypeString, Default: ""},
		{Name: "node_name", Type: field.TypeString, Default: ""},
		{Name: "machine_name", Type: field.TypeString, Default: ""},
		{Name: "cpu", Type: field.TypeFloat64, Default: 0},
		{Name: "memory_gb", Type: field.TypeFloat64, Default: 0},
		{Name: "disk_gb", Type: field.TypeFloat64, Default: 0},
	}
	// ControlPlaneComputeAllocationsTable holds the schema information for the "control_plane_compute_allocations" table.
	ControlPlaneComputeAllocationsTable = &schema.Table{
		Name:       "control_plane_compute_allocations",
		Columns:    ControlPlaneComputeAllocationsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneComputeAllocationsColumns[0]},
	}
	// ControlPlaneProductionE2eRecordsColumns holds the columns for the "control_plane_production_e2e_records" table.
	ControlPlaneProductionE2eRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeString, Default: ""},
		{Name: "workspace_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "result", Type: field.TypeString, Default: ""},
		{Name: "reason", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneProductionE2eRecordsTable holds the schema information for the "control_plane_production_e2e_records" table.
	ControlPlaneProductionE2eRecordsTable = &schema.Table{
		Name:       "control_plane_production_e2e_records",
		Columns:    ControlPlaneProductionE2eRecordsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneProductionE2eRecordsColumns[0]},
	}
	// ControlPlaneProjectTaskSyncHeadsColumns holds the columns for the "control_plane_project_task_sync_heads" table.
	ControlPlaneProjectTaskSyncHeadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "kind", Type: field.TypeString},
		{Name: "organization_id", Type: field.TypeString},
		{Name: "workspace_id", Type: field.TypeString},
		{Name: "project_id", Type: field.TypeString, Default: ""},
		{Name: "local_alias_id", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeInt64, Default: 1},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// ControlPlaneProjectTaskSyncHeadsTable holds the schema information for the "control_plane_project_task_sync_heads" table.
	ControlPlaneProjectTaskSyncHeadsTable = &schema.Table{
		Name:       "control_plane_project_task_sync_heads",
		Columns:    ControlPlaneProjectTaskSyncHeadsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneProjectTaskSyncHeadsColumns[0]},
	}
	// ControlPlaneRuntimeOperationsColumns holds the columns for the "control_plane_runtime_operations" table.
	ControlPlaneRuntimeOperationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "operation_id", Type: field.TypeString, Default: ""},
		{Name: "account_id", Type: field.TypeString, Default: ""},
		{Name: "workspace_id", Type: field.TypeString, Default: ""},
		{Name: "period_start", Type: field.TypeString, Default: ""},
		{Name: "resource_id", Type: field.TypeString, Default: ""},
		{Name: "resource_kind", Type: field.TypeString, Default: ""},
		{Name: "action", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "provider_request_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "result", Type: field.TypeString, Default: ""},
		{Name: "compute_allocation_id", Type: field.TypeString, Default: ""},
		{Name: "storage_id", Type: field.TypeString, Default: ""},
		{Name: "attachment_id", Type: field.TypeString, Default: ""},
		{Name: "runtime_service_name", Type: field.TypeString, Default: ""},
		{Name: "cvm_instance_id", Type: field.TypeString, Default: ""},
		{Name: "instance_id", Type: field.TypeString, Default: ""},
		{Name: "node_name", Type: field.TypeString, Default: ""},
		{Name: "machine_name", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneRuntimeOperationsTable holds the schema information for the "control_plane_runtime_operations" table.
	ControlPlaneRuntimeOperationsTable = &schema.Table{
		Name:       "control_plane_runtime_operations",
		Columns:    ControlPlaneRuntimeOperationsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneRuntimeOperationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "runtimeoperation_action_status_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneRuntimeOperationsColumns[9], ControlPlaneRuntimeOperationsColumns[12], ControlPlaneRuntimeOperationsColumns[1], ControlPlaneRuntimeOperationsColumns[0]},
			},
			{
				Name:    "runtimeoperation_account_id_action_status_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneRuntimeOperationsColumns[4], ControlPlaneRuntimeOperationsColumns[9], ControlPlaneRuntimeOperationsColumns[12], ControlPlaneRuntimeOperationsColumns[1], ControlPlaneRuntimeOperationsColumns[0]},
			},
			{
				Name:    "runtimeoperation_workspace_id_action_status_period_start_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneRuntimeOperationsColumns[5], ControlPlaneRuntimeOperationsColumns[9], ControlPlaneRuntimeOperationsColumns[12], ControlPlaneRuntimeOperationsColumns[6], ControlPlaneRuntimeOperationsColumns[1], ControlPlaneRuntimeOperationsColumns[0]},
			},
		},
	}
	// ControlPlaneSessionsColumns holds the columns for the "control_plane_sessions" table.
	ControlPlaneSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
		{Name: "csrf", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeString},
	}
	// ControlPlaneSessionsTable holds the schema information for the "control_plane_sessions" table.
	ControlPlaneSessionsTable = &schema.Table{
		Name:       "control_plane_sessions",
		Columns:    ControlPlaneSessionsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_id",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneSessionsColumns[3]},
			},
		},
	}
	// ControlPlaneStorageAttachmentsColumns holds the columns for the "control_plane_storage_attachments" table.
	ControlPlaneStorageAttachmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeString},
		{Name: "workspace_id", Type: field.TypeString, Default: ""},
		{Name: "compute_allocation_id", Type: field.TypeString, Default: ""},
		{Name: "storage_id", Type: field.TypeString, Default: ""},
		{Name: "volume_id", Type: field.TypeString, Default: ""},
		{Name: "operation_id", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "provider_request_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "mount_path", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneStorageAttachmentsTable holds the schema information for the "control_plane_storage_attachments" table.
	ControlPlaneStorageAttachmentsTable = &schema.Table{
		Name:       "control_plane_storage_attachments",
		Columns:    ControlPlaneStorageAttachmentsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneStorageAttachmentsColumns[0]},
	}
	// ControlPlaneStorageVolumesColumns holds the columns for the "control_plane_storage_volumes" table.
	ControlPlaneStorageVolumesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeString},
		{Name: "owner_user_id", Type: field.TypeString, Default: ""},
		{Name: "workspace_id", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "package_id", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "provider_resource_id", Type: field.TypeString, Default: ""},
		{Name: "provider_request_id", Type: field.TypeString, Default: ""},
		{Name: "operation_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "desired_status", Type: field.TypeString, Default: ""},
		{Name: "provider_status", Type: field.TypeString, Default: ""},
		{Name: "last_provider_sync_at", Type: field.TypeString, Default: ""},
		{Name: "last_provider_sync_error", Type: field.TypeString, Default: ""},
		{Name: "external_deleted_at", Type: field.TypeString, Default: ""},
		{Name: "billing_status", Type: field.TypeString, Default: ""},
		{Name: "pricing_version", Type: field.TypeString, Default: ""},
		{Name: "billing_operation_id", Type: field.TypeString, Default: ""},
		{Name: "billing_state_json", Type: field.TypeString, Default: "{}"},
		{Name: "mount_path", Type: field.TypeString, Default: ""},
		{Name: "size_gb", Type: field.TypeFloat64, Default: 0},
	}
	// ControlPlaneStorageVolumesTable holds the schema information for the "control_plane_storage_volumes" table.
	ControlPlaneStorageVolumesTable = &schema.Table{
		Name:       "control_plane_storage_volumes",
		Columns:    ControlPlaneStorageVolumesColumns,
		PrimaryKey: []*schema.Column{ControlPlaneStorageVolumesColumns[0]},
	}
	// ControlPlaneUsersColumns holds the columns for the "control_plane_users" table.
	ControlPlaneUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeString, Default: "owner"},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "password_hash", Type: field.TypeString, Default: ""},
		{Name: "disabled_at", Type: field.TypeString, Default: ""},
		{Name: "disabled_by", Type: field.TypeString, Default: ""},
		{Name: "disabled_reason", Type: field.TypeString, Default: ""},
		{Name: "deleted_at", Type: field.TypeString, Default: ""},
		{Name: "deleted_by", Type: field.TypeString, Default: ""},
		{Name: "delete_reason", Type: field.TypeString, Default: ""},
	}
	// ControlPlaneUsersTable holds the schema information for the "control_plane_users" table.
	ControlPlaneUsersTable = &schema.Table{
		Name:       "control_plane_users",
		Columns:    ControlPlaneUsersColumns,
		PrimaryKey: []*schema.Column{ControlPlaneUsersColumns[0]},
	}
	// ControlPlaneWorkspacesColumns holds the columns for the "control_plane_workspaces" table.
	ControlPlaneWorkspacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeString, Default: ""},
		{Name: "owner_account_id", Type: field.TypeString, Default: ""},
		{Name: "owner_user_id", Type: field.TypeString, Default: ""},
		{Name: "user_id", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "purchase_receipt_id", Type: field.TypeString, Default: ""},
		{Name: "billing_state_json", Type: field.TypeString, Default: "{}"},
		{Name: "storage_id", Type: field.TypeString, Default: ""},
		{Name: "current_compute_allocation_id", Type: field.TypeString, Default: ""},
		{Name: "current_attachment_id", Type: field.TypeString, Default: ""},
		{Name: "runtime_id", Type: field.TypeString, Default: ""},
		{Name: "runtime_service_name", Type: field.TypeString, Default: ""},
		{Name: "runtime_service_name_root", Type: field.TypeString, Default: ""},
		{Name: "service_name", Type: field.TypeString, Default: ""},
		{Name: "workspace_api_key_id", Type: field.TypeInt64, Nullable: true},
		{Name: "access_token_status", Type: field.TypeString, Default: ""},
		{Name: "access_account", Type: field.TypeString, Default: ""},
		{Name: "access_username", Type: field.TypeString, Default: ""},
		{Name: "credential_status", Type: field.TypeString, Default: ""},
		{Name: "credential_version", Type: field.TypeString, Default: ""},
		{Name: "credential_secret_ref", Type: field.TypeString, Default: ""},
		{Name: "access_requires_login", Type: field.TypeBool, Default: false},
		{Name: "verification_slot_id", Type: field.TypeString, Default: ""},
		{Name: "customer_product", Type: field.TypeBool, Default: true},
	}
	// ControlPlaneWorkspacesTable holds the schema information for the "control_plane_workspaces" table.
	ControlPlaneWorkspacesTable = &schema.Table{
		Name:       "control_plane_workspaces",
		Columns:    ControlPlaneWorkspacesColumns,
		PrimaryKey: []*schema.Column{ControlPlaneWorkspacesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "workspace_customer_product_id",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneWorkspacesColumns[29], ControlPlaneWorkspacesColumns[0]},
			},
		},
	}
	// ControlPlaneWorkspaceSyncEventsColumns holds the columns for the "control_plane_workspace_sync_events" table.
	ControlPlaneWorkspaceSyncEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "operation_id", Type: field.TypeString},
		{Name: "workspace_id", Type: field.TypeString},
		{Name: "cursor", Type: field.TypeInt64},
		{Name: "entity_kind", Type: field.TypeString},
		{Name: "project_id", Type: field.TypeString},
		{Name: "task_id", Type: field.TypeString, Default: ""},
		{Name: "client_id", Type: field.TypeString},
		{Name: "actor_user_id", Type: field.TypeString},
		{Name: "base_version", Type: field.TypeInt64},
		{Name: "server_version", Type: field.TypeInt64},
		{Name: "operation", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "payload_json", Type: field.TypeString, Default: "{}"},
		{Name: "content_digest", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Unique: true},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "conflict_id", Type: field.TypeString, Default: ""},
		{Name: "occurred_at", Type: field.TypeTime},
	}
	// ControlPlaneWorkspaceSyncEventsTable holds the schema information for the "control_plane_workspace_sync_events" table.
	ControlPlaneWorkspaceSyncEventsTable = &schema.Table{
		Name:       "control_plane_workspace_sync_events",
		Columns:    ControlPlaneWorkspaceSyncEventsColumns,
		PrimaryKey: []*schema.Column{ControlPlaneWorkspaceSyncEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "workspacesyncevent_workspace_id_cursor",
				Unique:  true,
				Columns: []*schema.Column{ControlPlaneWorkspaceSyncEventsColumns[4], ControlPlaneWorkspaceSyncEventsColumns[5]},
			},
			{
				Name:    "workspacesyncevent_workspace_id_operation_id",
				Unique:  true,
				Columns: []*schema.Column{ControlPlaneWorkspaceSyncEventsColumns[4], ControlPlaneWorkspaceSyncEventsColumns[3]},
			},
			{
				Name:    "workspacesyncevent_workspace_id_entity_kind_project_id_task_id_cursor",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneWorkspaceSyncEventsColumns[4], ControlPlaneWorkspaceSyncEventsColumns[6], ControlPlaneWorkspaceSyncEventsColumns[7], ControlPlaneWorkspaceSyncEventsColumns[8], ControlPlaneWorkspaceSyncEventsColumns[5]},
			},
			{
				Name:    "workspacesyncevent_workspace_id_conflict_id",
				Unique:  false,
				Columns: []*schema.Column{ControlPlaneWorkspaceSyncEventsColumns[4], ControlPlaneWorkspaceSyncEventsColumns[19]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ControlPlaneAccountsTable,
		ControlPlaneAdminAuditEventsTable,
		ControlPlaneAnnouncementsTable,
		ControlPlaneAnnouncementReadsTable,
		ControlPlaneArchivedAdminAuditEventsTable,
		ControlPlaneAuthAttemptsTable,
		ControlPlaneBillingReconciliationTable,
		ControlPlaneComputeAllocationsTable,
		ControlPlaneProductionE2eRecordsTable,
		ControlPlaneProjectTaskSyncHeadsTable,
		ControlPlaneRuntimeOperationsTable,
		ControlPlaneSessionsTable,
		ControlPlaneStorageAttachmentsTable,
		ControlPlaneStorageVolumesTable,
		ControlPlaneUsersTable,
		ControlPlaneWorkspacesTable,
		ControlPlaneWorkspaceSyncEventsTable,
	}
)

func init() {
	ControlPlaneAccountsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_accounts",
	}
	ControlPlaneAdminAuditEventsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_admin_audit_events",
	}
	ControlPlaneAnnouncementsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_announcements",
	}
	ControlPlaneAnnouncementReadsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_announcement_reads",
	}
	ControlPlaneArchivedAdminAuditEventsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_archived_admin_audit_events",
	}
	ControlPlaneAuthAttemptsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_auth_attempts",
	}
	ControlPlaneBillingReconciliationTable.Annotation = &entsql.Annotation{
		Table: "control_plane_billing_reconciliation",
	}
	ControlPlaneComputeAllocationsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_compute_allocations",
	}
	ControlPlaneProductionE2eRecordsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_production_e2e_records",
	}
	ControlPlaneProjectTaskSyncHeadsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_project_task_sync_heads",
	}
	ControlPlaneRuntimeOperationsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_runtime_operations",
	}
	ControlPlaneSessionsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_sessions",
	}
	ControlPlaneStorageAttachmentsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_storage_attachments",
	}
	ControlPlaneStorageVolumesTable.Annotation = &entsql.Annotation{
		Table: "control_plane_storage_volumes",
	}
	ControlPlaneUsersTable.Annotation = &entsql.Annotation{
		Table: "control_plane_users",
	}
	ControlPlaneWorkspacesTable.Annotation = &entsql.Annotation{
		Table: "control_plane_workspaces",
	}
	ControlPlaneWorkspaceSyncEventsTable.Annotation = &entsql.Annotation{
		Table: "control_plane_workspace_sync_events",
	}
}
