#!/usr/bin/env python3
"""Generate the fixed aggregate identity of every versioned owner event.

The specification owns the mapping: contracts/events.json carries
`x-aggregate-identity` per exact (eventType, schemaVersion). The Outbox and Inbox
columns `aggregate_type` and `aggregate_id` must agree with it, so the mapping is
derived here rather than hand-written or accepted as a free-form string.

Usage:  python3 generate_event_identity.py <events.json> <out.go>
"""
import json
import sys
from pathlib import Path


def load(path):
    document = json.loads(Path(path).read_text())
    identities = []
    for entry in document["oneOf"]:
        properties = entry["properties"]
        identity = entry.get("x-aggregate-identity")
        if identity is None:
            raise SystemExit(f"event without x-aggregate-identity: {properties['eventType']['const']}")
        identities.append(
            {
                "eventType": properties["eventType"]["const"],
                "schemaVersion": properties["schemaVersion"]["const"],
                "owner": properties["owner"]["const"],
                "consumers": sorted(entry["x-consumers"]),
                "aggregateType": identity["type"],
                "aggregateIDField": identity["idPayloadField"],
            }
        )
    identities.sort(key=lambda item: (item["eventType"], item["schemaVersion"]))
    return identities


def render(identities):
    lines = [
        "// Code generated by proto/generate_event_identity.py. DO NOT EDIT.",
        "//",
        "// Source: the specification's contracts/events.json `x-aggregate-identity`, which",
        "// fixes the aggregate type and the payload field supplying its id for every exact",
        "// (eventType, schemaVersion). Regenerate with packages/contracts/proto/generate_event_identity.py.",
        "",
        "package contracts",
        "",
        "import (",
        '\t"encoding/json"',
        '\t"errors"',
        '\t"fmt"',
        ")",
        "",
        "// ErrEventIdentityUnknown reports an event version the specification does not define.",
        "var ErrEventIdentityUnknown = errors.New(\"unknown event type or schema version\")",
        "",
        "// ErrEventAggregateIdentityMismatch reports an event whose recorded aggregate",
        "// identity does not agree with the payload it carries.",
        "var ErrEventAggregateIdentityMismatch = errors.New(\"event aggregate identity does not match its payload\")",
        "",
        "// EventIdentity is the aggregate identity the specification fixes for one exact",
        "// event version. Outbox and Inbox rows must record exactly this aggregate type and",
        "// the aggregate id carried by this payload field; the value is never free-form.",
        "type EventIdentity struct {",
        "\tEventType        string",
        "\tSchemaVersion    int32",
        "\tOwner            string",
        "\tConsumers        []string",
        "\tAggregateType    string",
        "\tAggregateIDField string",
        "}",
        "",
        "// EventIdentities lists every event version the specification defines.",
        "var EventIdentities = []EventIdentity{",
    ]
    for identity in identities:
        lines.append(
            "\t{EventType: %s, SchemaVersion: %d, Owner: %s, Consumers: []string{%s}, AggregateType: %s, AggregateIDField: %s},"
            % (
                json.dumps(identity["eventType"]),
                identity["schemaVersion"],
                json.dumps(identity["owner"]),
                ", ".join(json.dumps(owner) for owner in identity["consumers"]),
                json.dumps(identity["aggregateType"]),
                json.dumps(identity["aggregateIDField"]),
            )
        )
    lines += [
        "}",
        "",
        "var eventIdentityIndex = func() map[eventIdentityKey]EventIdentity {",
        "\tindex := make(map[eventIdentityKey]EventIdentity, len(EventIdentities))",
        "\tfor _, identity := range EventIdentities {",
        "\t\tindex[eventIdentityKey{eventType: identity.EventType, schemaVersion: identity.SchemaVersion}] = identity",
        "\t}",
        "\treturn index",
        "}()",
        "",
        "type eventIdentityKey struct {",
        "\teventType     string",
        "\tschemaVersion int32",
        "}",
        "",
        "// LookupEventIdentity returns the fixed identity for one exact event version.",
        "func LookupEventIdentity(eventType string, schemaVersion int32) (EventIdentity, bool) {",
        "\tidentity, ok := eventIdentityIndex[eventIdentityKey{eventType: eventType, schemaVersion: schemaVersion}]",
        "\treturn identity, ok",
        "}",
        "",
        "// Subscribed reports whether owner is listed in this exact event version's x-consumers.",
        "func (identity EventIdentity) Subscribed(owner string) bool {",
        "\tfor _, consumer := range identity.Consumers {",
        "\t\tif consumer == owner {",
        "\t\t\treturn true",
        "\t\t}",
        "\t}",
        "\treturn false",
        "}",
        "",
        "// AggregateIDFromPayload reads this identity's aggregate id from the exact payload",
        "// bytes recorded for the event. A payload that omits the field, carries a non-string",
        "// value, or carries an empty value is rejected instead of being coerced.",
        "func (identity EventIdentity) AggregateIDFromPayload(payload []byte) (string, error) {",
        "\tif len(payload) == 0 {",
        "\t\treturn \"\", fmt.Errorf(\"%w: empty payload\", ErrEventAggregateIdentityMismatch)",
        "\t}",
        "\tvar decoded map[string]json.RawMessage",
        "\tif err := json.Unmarshal(payload, &decoded); err != nil {",
        "\t\treturn \"\", fmt.Errorf(\"%w: %v\", ErrEventAggregateIdentityMismatch, err)",
        "\t}",
        "\traw, ok := decoded[identity.AggregateIDField]",
        "\tif !ok {",
        "\t\treturn \"\", fmt.Errorf(\"%w: payload has no %s\", ErrEventAggregateIdentityMismatch, identity.AggregateIDField)",
        "\t}",
        "\tvar value string",
        "\tif err := json.Unmarshal(raw, &value); err != nil {",
        "\t\treturn \"\", fmt.Errorf(\"%w: %s is not a string\", ErrEventAggregateIdentityMismatch, identity.AggregateIDField)",
        "\t}",
        "\tif value == \"\" {",
        "\t\treturn \"\", fmt.Errorf(\"%w: %s is empty\", ErrEventAggregateIdentityMismatch, identity.AggregateIDField)",
        "\t}",
        "\treturn value, nil",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    identities = load(sys.argv[1])
    Path(sys.argv[2]).write_text(render(identities))
    print(f"generated {len(identities)} event identities")


if __name__ == "__main__":
    main()
