#!/usr/bin/env python3
"""Generate the fixed owner and consumer set of every versioned owner event.

The contract owns the mapping: packages/contracts/proto/events.json carries
`owner`, `schemaVersion`, and `x-consumers` per exact event type. Outbox
producers and Inbox consumers must agree with it, so the mapping is derived here
rather than hand-written or accepted as a free-form string. The contract fixes no
aggregate-type vocabulary, so it is not invented here.

Usage:  python3 generate_event_identity.py <events.json> <out.go>
"""
import json
import sys
from pathlib import Path


def load(path):
    document = json.loads(Path(path).read_text())
    identities = []
    for entry in document["oneOf"]:
        properties = entry["properties"]
        identities.append(
            {
                "eventType": properties["eventType"]["const"],
                "schemaVersion": properties["schemaVersion"]["const"],
                "owner": properties["owner"]["const"],
                "consumers": sorted(entry["x-consumers"]),
            }
        )
    identities.sort(key=lambda item: (item["eventType"], item["schemaVersion"]))
    return identities


def render(identities):
    lines = [
        "// Code generated by proto/generate_event_identity.py. DO NOT EDIT.",
        "//",
        "// Source: packages/contracts/proto/events.json, which fixes `owner`,",
        "// `schemaVersion`, and `x-consumers` for every exact event type. Regenerate with",
        "// packages/contracts/proto/generate_event_identity.py.",
        "",
        "package contracts",
        "",
        "// EventIdentity is the fixed producer and consumer set the contract defines",
        "// for one exact event version. An Outbox producer and an Inbox consumer must",
        "// agree with it; the owner of an event version is never caller-supplied.",
        "type EventIdentity struct {",
        "\tEventType     string",
        "\tSchemaVersion int32",
        "\tOwner         string",
        "\tConsumers     []string",
        "}",
        "",
        "// EventIdentities lists every event version the contract defines.",
        "var EventIdentities = []EventIdentity{",
    ]
    for identity in identities:
        lines.append(
            "\t{EventType: %s, SchemaVersion: %d, Owner: %s, Consumers: []string{%s}},"
            % (
                json.dumps(identity["eventType"]),
                identity["schemaVersion"],
                json.dumps(identity["owner"]),
                ", ".join(json.dumps(owner) for owner in identity["consumers"]),
            )
        )
    lines += [
        "}",
        "",
        "var eventIdentityIndex = func() map[eventIdentityKey]EventIdentity {",
        "\tindex := make(map[eventIdentityKey]EventIdentity, len(EventIdentities))",
        "\tfor _, identity := range EventIdentities {",
        "\t\tindex[eventIdentityKey{eventType: identity.EventType, schemaVersion: identity.SchemaVersion}] = identity",
        "\t}",
        "\treturn index",
        "}()",
        "",
        "type eventIdentityKey struct {",
        "\teventType     string",
        "\tschemaVersion int32",
        "}",
        "",
        "// LookupEventIdentity returns the fixed identity for one exact event version.",
        "func LookupEventIdentity(eventType string, schemaVersion int32) (EventIdentity, bool) {",
        "\tidentity, ok := eventIdentityIndex[eventIdentityKey{eventType: eventType, schemaVersion: schemaVersion}]",
        "\treturn identity, ok",
        "}",
        "",
        "// Subscribed reports whether owner is listed in this exact event version's x-consumers.",
        "func (identity EventIdentity) Subscribed(owner string) bool {",
        "\tfor _, consumer := range identity.Consumers {",
        "\t\tif consumer == owner {",
        "\t\t\treturn true",
        "\t\t}",
        "\t}",
        "\treturn false",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    identities = load(sys.argv[1])
    Path(sys.argv[2]).write_text(render(identities))
    print(f"generated {len(identities)} event identities")


if __name__ == "__main__":
    main()
