// Code generated by ent, DO NOT EDIT.

package applicationrevision

import (
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldUpdatedAt, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldApplicationID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldVersion, v))
}

// Digest applies equality check predicate on the "digest" field. It's identical to DigestEQ.
func Digest(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldDigest, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldPayload, v))
}

// AdmittedByUserID applies equality check predicate on the "admitted_by_user_id" field. It's identical to AdmittedByUserIDEQ.
func AdmittedByUserID(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldAdmittedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldUpdatedAt, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldApplicationID, vs...))
}

// ApplicationIDGT applies the GT predicate on the "application_id" field.
func ApplicationIDGT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldApplicationID, v))
}

// ApplicationIDGTE applies the GTE predicate on the "application_id" field.
func ApplicationIDGTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldApplicationID, v))
}

// ApplicationIDLT applies the LT predicate on the "application_id" field.
func ApplicationIDLT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldApplicationID, v))
}

// ApplicationIDLTE applies the LTE predicate on the "application_id" field.
func ApplicationIDLTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldApplicationID, v))
}

// ApplicationIDContains applies the Contains predicate on the "application_id" field.
func ApplicationIDContains(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContains(FieldApplicationID, v))
}

// ApplicationIDHasPrefix applies the HasPrefix predicate on the "application_id" field.
func ApplicationIDHasPrefix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasPrefix(FieldApplicationID, v))
}

// ApplicationIDHasSuffix applies the HasSuffix predicate on the "application_id" field.
func ApplicationIDHasSuffix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasSuffix(FieldApplicationID, v))
}

// ApplicationIDEqualFold applies the EqualFold predicate on the "application_id" field.
func ApplicationIDEqualFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEqualFold(FieldApplicationID, v))
}

// ApplicationIDContainsFold applies the ContainsFold predicate on the "application_id" field.
func ApplicationIDContainsFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContainsFold(FieldApplicationID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContainsFold(FieldVersion, v))
}

// DigestEQ applies the EQ predicate on the "digest" field.
func DigestEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldDigest, v))
}

// DigestNEQ applies the NEQ predicate on the "digest" field.
func DigestNEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldDigest, v))
}

// DigestIn applies the In predicate on the "digest" field.
func DigestIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldDigest, vs...))
}

// DigestNotIn applies the NotIn predicate on the "digest" field.
func DigestNotIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldDigest, vs...))
}

// DigestGT applies the GT predicate on the "digest" field.
func DigestGT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldDigest, v))
}

// DigestGTE applies the GTE predicate on the "digest" field.
func DigestGTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldDigest, v))
}

// DigestLT applies the LT predicate on the "digest" field.
func DigestLT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldDigest, v))
}

// DigestLTE applies the LTE predicate on the "digest" field.
func DigestLTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldDigest, v))
}

// DigestContains applies the Contains predicate on the "digest" field.
func DigestContains(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContains(FieldDigest, v))
}

// DigestHasPrefix applies the HasPrefix predicate on the "digest" field.
func DigestHasPrefix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasPrefix(FieldDigest, v))
}

// DigestHasSuffix applies the HasSuffix predicate on the "digest" field.
func DigestHasSuffix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasSuffix(FieldDigest, v))
}

// DigestEqualFold applies the EqualFold predicate on the "digest" field.
func DigestEqualFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEqualFold(FieldDigest, v))
}

// DigestContainsFold applies the ContainsFold predicate on the "digest" field.
func DigestContainsFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContainsFold(FieldDigest, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContainsFold(FieldPayload, v))
}

// AdmittedByUserIDEQ applies the EQ predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEQ(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDNEQ applies the NEQ predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDNEQ(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNEQ(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDIn applies the In predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldIn(FieldAdmittedByUserID, vs...))
}

// AdmittedByUserIDNotIn applies the NotIn predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDNotIn(vs ...string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldNotIn(FieldAdmittedByUserID, vs...))
}

// AdmittedByUserIDGT applies the GT predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDGT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGT(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDGTE applies the GTE predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDGTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldGTE(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDLT applies the LT predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDLT(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLT(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDLTE applies the LTE predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDLTE(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldLTE(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDContains applies the Contains predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDContains(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContains(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDHasPrefix applies the HasPrefix predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDHasPrefix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasPrefix(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDHasSuffix applies the HasSuffix predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDHasSuffix(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldHasSuffix(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDEqualFold applies the EqualFold predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDEqualFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldEqualFold(FieldAdmittedByUserID, v))
}

// AdmittedByUserIDContainsFold applies the ContainsFold predicate on the "admitted_by_user_id" field.
func AdmittedByUserIDContainsFold(v string) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.FieldContainsFold(FieldAdmittedByUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApplicationRevision) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApplicationRevision) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApplicationRevision) predicate.ApplicationRevision {
	return predicate.ApplicationRevision(sql.NotPredicates(p))
}
