import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, realpathSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// The plan task book and its JSON projection are generated from frozen contracts.
// This gate regenerates them into an isolated tree and byte-compares against the
// checked-in artifacts, then runs the semantic validator read-only. It never
// rewrites the working tree and never opens a database, network or browser.
export const generatedPlanArtifacts = [
  "docs/spec/target/checks/development_plan.json",
  "docs/spec/target/14_implementation_work_packages.md"
] as const;

// Drop the volatile provenance field so a fresh render at a new HEAD is not reported
// as a semantic change; key order is normalized by JSON.stringify of a sorted rebuild.
function stablePlanJson(text: string): string {
  const parsed: any = JSON.parse(text);
  if (parsed && typeof parsed === "object") delete parsed.sourceSHA;
  return JSON.stringify(parsed);
}

export type PlanRunner = (command: string, args: string[], env: NodeJS.ProcessEnv, root: string) =>
  { status: number | null; stderr: string; stdout: string; error?: string };

export function runPlanGenerator(command: string, args: string[], env: NodeJS.ProcessEnv, root = repositoryRoot): ReturnType<PlanRunner> {
  const result = spawnSync(command, args, { cwd: root, env, encoding: "utf8", timeout: 120_000, maxBuffer: 8 * 1024 * 1024 });
  return { status: result.status, stdout: result.stdout ?? "", stderr: result.stderr ?? "", ...(result.error ? { error: result.error.message } : {}) };
}

/** Regenerate into a scratch tree, byte-compare the checked-in plan artifacts, then validate semantics read-only. */
export function verifyDevelopmentPlan({ root = repositoryRoot, runner = runPlanGenerator }: { root?: string; runner?: PlanRunner } = {}) {
  root = resolve(root);
  const out = mkdtempSync(join(tmpdir(), "opl-development-plan-"));
  try {
    const generated = runner("python3", ["docs/spec/target/checks/render_development_plan.py", "--check"], { ...process.env, OPL_DEVELOPMENT_PLAN_OUT: out, PYTHONDONTWRITEBYTECODE: "1" }, root);
    if (generated.status !== 0) throw new Error(`plan renderer failed: ${generated.error ?? generated.status}\n${generated.stderr}${generated.stdout}`.trim());
    for (const artifact of generatedPlanArtifacts) {
      const checkedIn = join(root, artifact);
      const regenerated = join(out, artifact.replace(/^docs\/spec\/target\//u, ""));
      if (!existsSync(checkedIn)) throw new Error(`checked-in plan artifact missing: ${artifact}`);
      if (!existsSync(regenerated)) throw new Error(`renderer did not emit: ${artifact}`);
      // JSON carries a provenance-only sourceSHA that changes with every commit; it is
      // not part of the generated plan semantics. Compare everything else exactly, and
      // compare non-JSON artifacts byte-for-byte.
      const equal = artifact.endsWith(".json")
        ? stablePlanJson(readFileSync(checkedIn, "utf8")) === stablePlanJson(readFileSync(regenerated, "utf8"))
        : readFileSync(checkedIn).equals(readFileSync(regenerated));
      if (!equal) {
        throw new Error(`stale generated plan artifact: ${artifact} (regeneration differs; run docs/spec/target/checks/render_development_plan.py and commit the regenerated bytes)`);
      }
    }
    const checked = runner("python3", ["docs/spec/target/checks/validate_development_plan.py", "--check"], { ...process.env, PYTHONDONTWRITEBYTECODE: "1" }, root);
    if (checked.status !== 0) throw new Error(`development plan validation failed: ${checked.error ?? checked.status}\n${checked.stderr}${checked.stdout}`.trim());
    return { artifacts: [...generatedPlanArtifacts] };
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
}

async function main() {
  verifyDevelopmentPlan();
  process.stdout.write("Development plan freshness: PASS\n");
}

if (process.argv[1] && existsSync(process.argv[1]) && pathToFileURL(realpathSync(process.argv[1])).href === import.meta.url) {
  main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
}
