// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AdminAuditEvent is the predicate function for adminauditevent builders.
type AdminAuditEvent func(*sql.Selector)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// AnnouncementRead is the predicate function for announcementread builders.
type AnnouncementRead func(*sql.Selector)

// ArchivedAdminAuditEvent is the predicate function for archivedadminauditevent builders.
type ArchivedAdminAuditEvent func(*sql.Selector)

// AuthAttempt is the predicate function for authattempt builders.
type AuthAttempt func(*sql.Selector)

// BillingReconciliation is the predicate function for billingreconciliation builders.
type BillingReconciliation func(*sql.Selector)

// ComputeAllocation is the predicate function for computeallocation builders.
type ComputeAllocation func(*sql.Selector)

// ProductionE2ERecord is the predicate function for productione2erecord builders.
type ProductionE2ERecord func(*sql.Selector)

// ProjectTaskSyncHead is the predicate function for projecttasksynchead builders.
type ProjectTaskSyncHead func(*sql.Selector)

// RuntimeOperation is the predicate function for runtimeoperation builders.
type RuntimeOperation func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// StorageAttachment is the predicate function for storageattachment builders.
type StorageAttachment func(*sql.Selector)

// StorageVolume is the predicate function for storagevolume builders.
type StorageVolume func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)

// WorkspaceSyncEvent is the predicate function for workspacesyncevent builders.
type WorkspaceSyncEvent func(*sql.Selector)
