const $ = (id) => document.getElementById(id);
const agentSelect = $("agent"), promptInput = $("prompt"), sendButton = $("send"), status = $("runtime-status"), hint = $("hint"), messages = $("messages"), diagnostics = $("diagnostics-body");
let csrfToken = null, state = null, agents = [], active = null, eventSource = null;
const json = async (url, init = {}) => { const headers = new Headers(init.headers || {}); if (init.method && init.method !== "GET" && csrfToken) headers.set("x-csrf-token", csrfToken); const response = await fetch(url, {...init, headers}); const body = await response.json().catch(() => null); if (!response.ok || body?.error) throw new Error(body?.error?.message || body?.detail || `HTTP ${response.status}`); return body; };
function setStatus(text, kind = "") { status.textContent = text; status.className = `status ${kind}`; }
function addMessage(role, text) { const empty = messages.querySelector(".empty"); empty?.remove(); const item = document.createElement("div"); item.className = `message ${role}`; item.textContent = text; messages.append(item); messages.scrollTop = messages.scrollHeight; return item; }
function actionFor(agent) { return agent?.available_actions?.find((entry) => entry.action_id === "invoke_agent_package_for_current_turn") || null; }
function compatibleAgents(value) { const entries = value?.app_state?.agent_packages?.directory?.entries || value?.agent_packages?.directory?.entries || []; return entries.filter((entry) => entry?.package_role === "standard_agent" && entry?.readiness?.operational_ready === true && actionFor(entry)); }
function connectEvents() { eventSource?.close(); eventSource = new EventSource("/api/opl-events"); eventSource.onopen = () => setStatus("Runtime connected", "ready"); eventSource.onerror = () => setStatus("Event stream unavailable", "error"); eventSource.onmessage = (event) => { let value; try { value = JSON.parse(event.data); } catch { return; } const params = value.params || value; const method = value.method || value.type || ""; if (!active) return; if (method === "item/agentMessage/delta") { active.text += params.delta || params.text || ""; active.node.textContent = active.text; } else if (method === "item/completed" && params.item?.type === "agentMessage") { active.text = params.item.text || active.text; active.node.textContent = active.text; } else if (method === "turn/completed") { finishSend(); } }; }
function finishSend() { if (!active) return; active = null; sendButton.disabled = false; agentSelect.disabled = false; promptInput.disabled = false; }
async function load() { try { const identity = await json("/api/auth/user"); csrfToken = typeof identity?.csrfToken === "string" ? identity.csrfToken : null; state = await json("/api/opl/state?profile=fast"); agents = compatibleAgents(state); agentSelect.replaceChildren(...agents.map((entry) => { const option = document.createElement("option"); option.value = entry.package_id; option.textContent = entry.display_name || entry.package_id; return option; })); if (!agents.length) throw new Error("Runtime did not project an operational Agent with invoke_agent_package_for_current_turn; no call was attempted."); agentSelect.disabled = false; promptInput.disabled = false; sendButton.disabled = false; hint.textContent = `${agents.length} Agent(s) available`; diagnostics.textContent = JSON.stringify({transport: {state: "/api/opl/state?profile=fast", events: "GET /api/opl-events", action: "POST /api/opl/action"}, agentIds: agents.map((entry) => entry.package_id)}, null, 2); setStatus("Runtime ready", "ready"); connectEvents(); } catch (error) { setStatus("Runtime unavailable", "error"); hint.textContent = error.message; diagnostics.textContent = error.stack || String(error); } }
$("composer").addEventListener("submit", async (event) => { event.preventDefault(); if (active) return; const prompt = promptInput.value.trim(); const agent = agents.find((entry) => entry.package_id === agentSelect.value); const action = actionFor(agent); if (!prompt || !agent || !action) return; addMessage("user", prompt); promptInput.value = ""; const node = addMessage("assistant", ""); active = {node, text: ""}; sendButton.disabled = true; agentSelect.disabled = true; promptInput.disabled = true; try { const payload = {...(action.payload || {}), input: {text: prompt}}; const receipt = await json("/api/opl/action", {method: "POST", headers: {"content-type": "application/json"}, body: JSON.stringify({actionId: action.action_id, payload, dryRun: false})}); if (receipt.status !== "executed") throw new Error(receipt.blockedReason || receipt.stderr || "Agent action was not executed"); } catch (error) { node.remove(); addMessage("error", error.message); finishSend(); } });
load();
